.macro .marubatsu,str
    .area 13,0xAF
        .strn str
    .endarea
.endmacro

/* 每条文本须遵守以下规则：
   1.必须以全角空格，即“　”结尾。
   2.文本长度不超过13（含“　”）。
   3.文本长度至少为4（含“　”），否则用“　”填充。
*/

.loadtable "marubatsu_tbl\marubatsu_chs_00.tbl"
.orga (0x0D01B4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "せいふく　"
    .marubatsu "制服　　　"
  ; .marubatsu "あかいふく　"
    .marubatsu "红衣服　　　"
  ; .marubatsu "あおいふく　"
    .marubatsu "蓝衣服　　　"
  ; .marubatsu "きいろいふく　"
    .marubatsu "黄衣服　　　　"
  ; .marubatsu "３かまえ　"
    .marubatsu "３天前　　"
  ; .marubatsu "４かまえ　"
    .marubatsu "４天前　　"
  ; .marubatsu "５かまえ　"
    .marubatsu "５天前　　"
  ; .marubatsu "６かまえ　"
    .marubatsu "６天前　　"
.orga (0x0D0250 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シネマ　"
    .marubatsu "电影院　"
  ; .marubatsu "トロピカルランド　"
    .marubatsu "多罗碧加　　　　　"
  ; .marubatsu "こうえん　"
    .marubatsu "公园　　　"
  ; .marubatsu "きょうかい　"
    .marubatsu "教会　　　　"
  ; .marubatsu "３かまえ　"
    .marubatsu "３天前　　"
  ; .marubatsu "４かまえ　"
    .marubatsu "４天前　　"
  ; .marubatsu "５かまえ　"
    .marubatsu "５天前　　"
  ; .marubatsu "６かまえ　"
    .marubatsu "６天前　　"

.loadtable "marubatsu_tbl\marubatsu_chs_01.tbl"
.orga (0x0D035E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "けいこ　"
    .marubatsu "惠子　　"
  ; .marubatsu "おくさん　"
    .marubatsu "夫人　　　"
  ; .marubatsu "ヒゲありのだんせい　"
    .marubatsu "胡子男　　　　　　　"
  ; .marubatsu "ヒゲなしのだんせい　"
    .marubatsu "没胡子男　　　　　　"
  ; .marubatsu "１ごうしつ　"
    .marubatsu "１号室　　　"
  ; .marubatsu "２ごうしつ　"
    .marubatsu "２号室　　　"
  ; .marubatsu "３ごうしつ　"
    .marubatsu "３号室　　　"
  ; .marubatsu "４ごうしつ　"
    .marubatsu "４号室　　　"
.orga (0x0D03FA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ピエトロしんぷ　"
    .marubatsu "彼得罗神父　　　"
  ; .marubatsu "トマスしんぷ　"
    .marubatsu "托马斯神父　　"
  ; .marubatsu "ポールしんぷ　"
    .marubatsu "保罗神父　　　"
  ; .marubatsu "ジョンしんぷ　"
    .marubatsu "约翰神父　　　"
  ; .marubatsu "１ごうしつ　"
    .marubatsu "１号室　　　"
  ; .marubatsu "２ごうしつ　"
    .marubatsu "２号室　　　"
  ; .marubatsu "３ごうしつ　"
    .marubatsu "３号室　　　"
  ; .marubatsu "４ごうしつ　"
    .marubatsu "４号室　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_02.tbl"
.orga (0x0D0508 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１项　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２项　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３项　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４项　　"
  ; .marubatsu "でんごんをかく　"
    .marubatsu "写留言　　　　　"
  ; .marubatsu "ほんをかえす　"
    .marubatsu "还书　　　　　"
  ; .marubatsu "チケットをかう　"
    .marubatsu "买票　　　　　　"
  ; .marubatsu "ケーキをかう　"
    .marubatsu "买蛋糕　　　　"
.orga (0x0D05A4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "としょかん　"
    .marubatsu "图书馆　　　"
  ; .marubatsu "べいかえき　"
    .marubatsu "米花站　　　"
  ; .marubatsu "カフエ　ロイヤル　"
    .marubatsu "罗伊尔　　　　　　"
  ; .marubatsu "トロピカルランド　"
    .marubatsu "多罗碧加　　　　　"
  ; .marubatsu "でんごんをかく　"
    .marubatsu "写留言　　　　　"
  ; .marubatsu "ほんをかえす　"
    .marubatsu "还书　　　　　"
  ; .marubatsu "チケットをかう　"
    .marubatsu "买票　　　　　　"
  ; .marubatsu "ケーキをかう　"
    .marubatsu "买蛋糕　　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_03.tbl"
.orga (0x0D06B2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "２２ばん　"
    .marubatsu "２２号　　"
  ; .marubatsu "２６ばん　"
    .marubatsu "２６号　　"
  ; .marubatsu "４３ばん　"
    .marubatsu "４３号　　"
  ; .marubatsu "４７ばん　"
    .marubatsu "４７号　　"
  ; .marubatsu "スペード　"
    .marubatsu "黑桃　　　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "方片　　"
  ; .marubatsu "ハート　"
    .marubatsu "红桃　　"
  ; .marubatsu "クラブ　"
    .marubatsu "梅花　　"
.orga (0x0D074E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "らん　　"
    .marubatsu "兰　　　"
  ; .marubatsu "けいこ　"
    .marubatsu "惠子　　"
  ; .marubatsu "ポールしんぷ　"
    .marubatsu "保罗神父　　　"
  ; .marubatsu "りょうこ　"
    .marubatsu "良子　　　"
  ; .marubatsu "スペード　"
    .marubatsu "黑桃　　　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "方片　　"
  ; .marubatsu "ハート　"
    .marubatsu "红心　　"
  ; .marubatsu "クラブ　"
    .marubatsu "梅花　　"

.loadtable "marubatsu_tbl\marubatsu_chs_04.tbl"
.orga (0x0D085C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヒロイン　"
    .marubatsu "女主角　　"
  ; .marubatsu "ライバル　"
    .marubatsu "情敌　　　"
  ; .marubatsu "かれし　"
    .marubatsu "男友　　"
  ; .marubatsu "ようぎしゃ　"
    .marubatsu "嫌疑人　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１出场　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２出场　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３出场　"
  ; .marubatsu "ぜんぶ　"
    .marubatsu "全部出场　"
.orga (0x0D08F8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "洋子　　"
  ; .marubatsu "きょうこ　"
    .marubatsu "京子　　　"
  ; .marubatsu "ようじ　"
    .marubatsu "洋二　　"
  ; .marubatsu "としき　"
    .marubatsu "俊树　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１出场　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２出场　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３出场　"
  ; .marubatsu "ぜんぶ　"
    .marubatsu "全部出场　"

.loadtable "marubatsu_tbl\marubatsu_chs_05.tbl"
.orga (0x0D0A06 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "４じ３０にでた　"
    .marubatsu "４点３０　　　　"
  ; .marubatsu "５じにでた　"
    .marubatsu "５点　　　　"
  ; .marubatsu "５じ３０にでた　"
    .marubatsu "５点３０　　　　"
  ; .marubatsu "６じにでた　"
    .marubatsu "６点　　　　"
  ; .marubatsu "２じ３０にでた　"
    .marubatsu "２点３０　　　　"
  ; .marubatsu "３じにでた　"
    .marubatsu "３点　　　　"
  ; .marubatsu "３じ３０にでた　"
    .marubatsu "３点３０　　　　"
  ; .marubatsu "４じにでた　"
    .marubatsu "４点　　　　"
.orga (0x0D0AA2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "洋子　　"
  ; .marubatsu "ようじ　"
    .marubatsu "洋二　　"
  ; .marubatsu "としき　"
    .marubatsu "俊树　　"
  ; .marubatsu "カントク　"
    .marubatsu "导演　　　"
  ; .marubatsu "２じ３０にでた　"
    .marubatsu "２点３０　　　　"
  ; .marubatsu "３じにでた　"
    .marubatsu "３点　　　　"
  ; .marubatsu "３じ３０にでた　"
    .marubatsu "３点３０　　　　"
  ; .marubatsu "４じにでた　"
    .marubatsu "４点　　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_06.tbl"
.orga (0x0D0BB0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シネマ　"
    .marubatsu "电影院　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
  ; .marubatsu "デパート　"
    .marubatsu "百货大楼　"
  ; .marubatsu "がっこう　"
    .marubatsu "学校　　　"
  ; .marubatsu "こどもばんぐみ　"
    .marubatsu "儿童节目　　　　　"
  ; .marubatsu "グルメばんぐみ　"
    .marubatsu "美食节目　　　　"
  ; .marubatsu "しゅざい　"
    .marubatsu "采访　　　"
  ; .marubatsu "あいさつ　"
    .marubatsu "见面会　　"
.orga (0x0D0C4C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "洋子　　"
  ; .marubatsu "ようじ　"
    .marubatsu "洋二　　"
  ; .marubatsu "としき　"
    .marubatsu "俊树　　"
  ; .marubatsu "カントク　"
    .marubatsu "导演　　　"
  ; .marubatsu "こどもばんぐみ　"
    .marubatsu "儿童节目　　　　"
  ; .marubatsu "グルメばんぐみ　"
    .marubatsu "美食节目　　　　"
  ; .marubatsu "しゅざい　"
    .marubatsu "采访　　　"
  ; .marubatsu "あいさつ　"
    .marubatsu "见面会　　"

.loadtable "marubatsu_tbl\marubatsu_chs_07.tbl"
.orga (0x0D0D5A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ねんまえ　"
    .marubatsu "１年前　　　"
  ; .marubatsu "２ねんまえ　"
    .marubatsu "２年前　　　"
  ; .marubatsu "３ねんまえ　"
    .marubatsu "３年前　　　"
  ; .marubatsu "４ねんまえ　"
    .marubatsu "４年前　　　"
  ; .marubatsu "しごとをとられた　"
    .marubatsu "工作被抢　　　　　"
  ; .marubatsu "おかねをとられた　"
    .marubatsu "钱被骗　　　　　　"
  ; .marubatsu "こいびとがじさつ　"
    .marubatsu "恋人自杀　　　　　"
  ; .marubatsu "きょうこにふられた　"
    .marubatsu "被甩了　　　　　　　"
.orga (0x0D0DF6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "洋子　　"
  ; .marubatsu "ようじ　"
    .marubatsu "洋二　　"
  ; .marubatsu "としき　"
    .marubatsu "俊树　　"
  ; .marubatsu "カントク　"
    .marubatsu "导演　　　"
  ; .marubatsu "しごとをとられた　"
    .marubatsu "工作被抢　　　　　"
  ; .marubatsu "おかねをとられた　"
    .marubatsu "钱被骗　　　　　　"
  ; .marubatsu "こいびとがじさつ　"
    .marubatsu "恋人自杀　　　　　"
  ; .marubatsu "きょうこにふられた　"
    .marubatsu "被甩了　　　　　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_08.tbl"
.orga (0x0D0F04 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "むじのカサ　"
    .marubatsu "单色伞　　　"
  ; .marubatsu "みずたまのカサ　"
    .marubatsu "雨点伞　　　　　"
  ; .marubatsu "チエックのカサ　"
    .marubatsu "格子伞　　　　　"
  ; .marubatsu "たてじまのカサ　"
    .marubatsu "条纹伞　　　　　"
  ; .marubatsu "ビニールぶくろ　"
    .marubatsu "塑料袋　　　　　"
  ; .marubatsu "カメラ　"
    .marubatsu "相机　　"
  ; .marubatsu "アイスボックス　"
    .marubatsu "冰块盒　　　　　"
  ; .marubatsu "リュック　"
    .marubatsu "帆布背包　"
.orga (0x0D0FA0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "洋子　　"
  ; .marubatsu "ようじ　"
    .marubatsu "洋二　　"
  ; .marubatsu "としき　"
    .marubatsu "俊树　　"
  ; .marubatsu "カントク　"
    .marubatsu "导演　　　"
  ; .marubatsu "ビニールぶくろ　"
    .marubatsu "塑料袋　　　　　"
  ; .marubatsu "カメラ　"
    .marubatsu "相机　　"
  ; .marubatsu "アイスボックス　"
    .marubatsu "冰块盒　　　　　"
  ; .marubatsu "リュック　"
    .marubatsu "帆布背包　"

.loadtable "marubatsu_tbl\marubatsu_chs_09.tbl"
.orga (0x0D10AE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アメリカしゃ　"
    .marubatsu "美国车　　　　"
  ; .marubatsu "ニホンしゃ　"
    .marubatsu "日本车　　　"
  ; .marubatsu "ドイツしゃ　"
    .marubatsu "德国车　　　"
  ; .marubatsu "イギリスしゃ　"
    .marubatsu "英国车　　　　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
  ; .marubatsu "デパート　"
    .marubatsu "百货大楼　"
  ; .marubatsu "こうえん　"
    .marubatsu "公园　　　"
  ; .marubatsu "シネマ　"
    .marubatsu "电影院　"
  ; .marubatsu "ナイフ　"
    .marubatsu "小刀　　"
  ; .marubatsu "きり　　"
    .marubatsu "雾　　　"
  ; .marubatsu "なぞ　　"
    .marubatsu "谜　　　"
  ; .marubatsu "よる　　"
    .marubatsu "夜　　　"
.orga (0x0D114A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しんいち　"
    .marubatsu "新一　　　"
  ; .marubatsu "へいじ　"
    .marubatsu "平次　　"
  ; .marubatsu "こごろう　"
    .marubatsu "小五郎　　"
  ; .marubatsu "ジャック　"
    .marubatsu "杰克　　　"
  ; .marubatsu "ナイフ　"
    .marubatsu "小刀　　"
  ; .marubatsu "きり　　"
    .marubatsu "雾　　　"
  ; .marubatsu "なぞ　　"
    .marubatsu "谜　　　"
  ; .marubatsu "よる　　"
    .marubatsu "夜　　　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
  ; .marubatsu "デパート　"
    .marubatsu "百货大楼　"
  ; .marubatsu "こうえん　"
    .marubatsu "公园　　　"
  ; .marubatsu "シネマ　"
    .marubatsu "电影院　"

.loadtable "marubatsu_tbl\marubatsu_chs_0A.tbl"
.orga (0x0D1258 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "せんさいのつれご　"
    .marubatsu "前妻带的　　　　　"
  ; .marubatsu "ごさいのつれご　"
    .marubatsu "后妻带的　　　　"
  ; .marubatsu "せんさいのじっし　"
    .marubatsu "前妻生的　　　　　"
  ; .marubatsu "ごさいのじっし　"
    .marubatsu "后妻生的　　　　"
  ; .marubatsu "いしゃ　"
    .marubatsu "医生　　"
  ; .marubatsu "じょせい　"
    .marubatsu "女性　　　"
  ; .marubatsu "きぞく　"
    .marubatsu "贵族　　"
  ; .marubatsu "けいかん　"
    .marubatsu "警官　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "老大　　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "老二　　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "老三　　　"
  ; .marubatsu "すえっこ　"
    .marubatsu "老四　　　"
.orga (0x0D12F4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しゃく　"
    .marubatsu "爵　　　"
  ; .marubatsu "りん　　"
    .marubatsu "伦　　　"
  ; .marubatsu "とし　　"
    .marubatsu "利　　　"
  ; .marubatsu "あつし　"
    .marubatsu "敦　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "老大　　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "老二　　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "老三　　　"
  ; .marubatsu "すえっこ　"
    .marubatsu "老四　　　"
  ; .marubatsu "いしゃ　"
    .marubatsu "医生　　"
  ; .marubatsu "じょせい　"
    .marubatsu "女性　　　"
  ; .marubatsu "きぞく　"
    .marubatsu "贵族　　"
  ; .marubatsu "けいかん　"
    .marubatsu "警官　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_0B.tbl"
.orga (0x0D1402 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "やしき　"
    .marubatsu "宅邸　　"
  ; .marubatsu "べってい　"
    .marubatsu "别墅　　　"
  ; .marubatsu "かぶけん　"
    .marubatsu "股票　　　"
  ; .marubatsu "コレクション　"
    .marubatsu "收藏　　　　　"
  ; .marubatsu "２０おくえん　"
    .marubatsu "２０亿　　　　"
  ; .marubatsu "１５おくえん　"
    .marubatsu "１５亿　　　　"
  ; .marubatsu "１３おくえん　"
    .marubatsu "１３亿　　　　"
  ; .marubatsu "１２おくえん　"
    .marubatsu "１２亿　　　　"
.orga (0x0D149E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しゃく　"
    .marubatsu "爵　　　"
  ; .marubatsu "りん　　"
    .marubatsu "伦　　　"
  ; .marubatsu "とし　　"
    .marubatsu "利　　　"
  ; .marubatsu "あつし　"
    .marubatsu "敦　　　"
  ; .marubatsu "２０おくえん　"
    .marubatsu "２０亿　　　　"
  ; .marubatsu "１５おくえん　"
    .marubatsu "１５亿　　　　"
  ; .marubatsu "１３おくえん　"
    .marubatsu "１３亿　　　　"
  ; .marubatsu "１２おくえん　"
    .marubatsu "１２亿　　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_0C.tbl"
.orga (0x0D15AC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アーミーナイフ　"
    .marubatsu "军刀　　　　　　"
  ; .marubatsu "くだものナイフ　"
    .marubatsu "水果刀　　　　　"
  ; .marubatsu "ちょうこくとう　"
    .marubatsu "雕刻刀　　　　　"
  ; .marubatsu "もてない　"
    .marubatsu "没拿东西　"
  ; .marubatsu "あえない　"
    .marubatsu "没见到　　"
  ; .marubatsu "どなられた　"
    .marubatsu "大叫　　　　"
  ; .marubatsu "わらった　"
    .marubatsu "笑了　　　"
  ; .marubatsu "コーヒーをとりに　"
    .marubatsu "去拿咖啡　　　　　"
  ; .marubatsu "１じ　　"
    .marubatsu "１点　　"
  ; .marubatsu "２じ　　"
    .marubatsu "２点　　"
  ; .marubatsu "３じ　　"
    .marubatsu "３点　　"
  ; .marubatsu "４じ　　"
    .marubatsu "４点　　"
.orga (0x0D1648 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しゃく　"
    .marubatsu "爵　　　"
  ; .marubatsu "りん　　"
    .marubatsu "伦　　　"
  ; .marubatsu "とし　　"
    .marubatsu "利　　　"
  ; .marubatsu "あつし　"
    .marubatsu "敦　　　"
  ; .marubatsu "１じ　　"
    .marubatsu "１点　　"
  ; .marubatsu "２じ　　"
    .marubatsu "２点　　"
  ; .marubatsu "３じ　　"
    .marubatsu "３点　　"
  ; .marubatsu "４じ　　"
    .marubatsu "４点　　"
  ; .marubatsu "あえない　"
    .marubatsu "没见到　　"
  ; .marubatsu "どなられた　"
    .marubatsu "大叫　　　　"
  ; .marubatsu "わらった　"
    .marubatsu "笑了　　　"
  ; .marubatsu "コーヒーをとりに　"
    .marubatsu "去拿咖啡　　　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_0D.tbl"
.orga (0x0D1756 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "３かまえ　"
    .marubatsu "３天前　　"
  ; .marubatsu "おととい　"
    .marubatsu "前天　　　"
  ; .marubatsu "ゆうべ　"
    .marubatsu "昨晚　　"
  ; .marubatsu "こんや　"
    .marubatsu "今晚　　"
  ; .marubatsu "はくぶつかん　"
    .marubatsu "博物馆　　　　"
  ; .marubatsu "びじゅつかん　"
    .marubatsu "美术馆　　　　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
  ; .marubatsu "きょうかい　"
    .marubatsu "教会　　　　"
.orga (0x0D17F2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "サフアイヤ　"
    .marubatsu "蓝宝石　　　"
  ; .marubatsu "エメラルド　"
    .marubatsu "绿宝石　　　"
  ; .marubatsu "オパール　"
    .marubatsu "蛋白石　　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "钻石　　"
  ; .marubatsu "はくぶつかん　"
    .marubatsu "博物馆　　　　"
  ; .marubatsu "びじゅつかん　"
    .marubatsu "美术馆　　　　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
  ; .marubatsu "きょうかい　"
    .marubatsu "教会　　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_0E.tbl"
.orga (0x0D1900 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "だい１てんじしつ　"
    .marubatsu "第１展厅　　　　　"
  ; .marubatsu "だい２てんじしつ　"
    .marubatsu "第２展厅　　　　　"
  ; .marubatsu "だい３てんじしつ　"
    .marubatsu "第３展厅　　　　　"
  ; .marubatsu "だい４てんじしつ　"
    .marubatsu "第４展厅　　　　　"
  ; .marubatsu "かいが　"
    .marubatsu "绘画　　"
  ; .marubatsu "ちょうこく　"
    .marubatsu "雕刻　　　　"
  ; .marubatsu "げんだいアート　"
    .marubatsu "现代艺术　　　　"
  ; .marubatsu "ほうしょくひん　"
    .marubatsu "珠宝首饰　　　　"
  ; .marubatsu "いりぐちにちかい　"
    .marubatsu "离入口近　　　　　"
  ; .marubatsu "でぐちひとつ　"
    .marubatsu "一个入口　　　"
  ; .marubatsu "とびら３つ　"
    .marubatsu "３个入口　　"
  ; .marubatsu "ひじょうぐちあり　"
    .marubatsu "紧急出口　　　　　"
.orga (0x0D199C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こごろう　"
    .marubatsu "小五郎　　"
  ; .marubatsu "めぐれ　"
    .marubatsu "目暮　　"
  ; .marubatsu "なかもり　"
    .marubatsu "中森　　　"
  ; .marubatsu "しらとり　"
    .marubatsu "白鸟　　　"
  ; .marubatsu "いりぐちにちかい　"
    .marubatsu "离入口近　　　　　"
  ; .marubatsu "でぐちひとつ　"
    .marubatsu "一个入口　　　"
  ; .marubatsu "とびら３つ　"
    .marubatsu "３个入口　　"
  ; .marubatsu "ひじょうぐちあり　"
    .marubatsu "紧急出口　　　　　"
  ; .marubatsu "かいが　"
    .marubatsu "绘画　　"
  ; .marubatsu "ちょうこく　"
    .marubatsu "雕刻　　　　"
  ; .marubatsu "げんだいアート　"
    .marubatsu "现代艺术　　　　"
  ; .marubatsu "ほうしょくひん　"
    .marubatsu "珠宝首饰　　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_0F.tbl"
.orga (0x0D1AAA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "６じ００にでた　"
    .marubatsu "出６点００　　　"
  ; .marubatsu "６じ０５にでた　"
    .marubatsu "出６点０５　　　"
  ; .marubatsu "６じ１０にでた　"
    .marubatsu "出６点１０　　　"
  ; .marubatsu "６じ１５にでた　"
    .marubatsu "出６点１５　　　"
  ; .marubatsu "５じ４５にはいった　"
    .marubatsu "进５点４５　　　　　"
  ; .marubatsu "５じ５５にはいった　"
    .marubatsu "进５点５５　　　　　"
  ; .marubatsu "６じ０５にはいった　"
    .marubatsu "进６点０５　　　　　"
  ; .marubatsu "６じ１０にはいった　"
    .marubatsu "进６点１０　　　　　"
.orga (0x0D1B46 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こごろう　"
    .marubatsu "小五郎　　"
  ; .marubatsu "めぐれ　"
    .marubatsu "目暮　　"
  ; .marubatsu "なかもり　"
    .marubatsu "中森　　　"
  ; .marubatsu "おおくぼ　"
    .marubatsu "大久保　　"
  ; .marubatsu "５じ４５にはいった　"
    .marubatsu "进５点４５　　　　　"
  ; .marubatsu "５じ５５にはいった　"
    .marubatsu "进５点５５　　　　　"
  ; .marubatsu "６じ０５にはいった　"
    .marubatsu "进６点０５　　　　　"
  ; .marubatsu "６じ１０にはいった　"
    .marubatsu "进６点１０　　　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_10.tbl"
.orga (0x0D1C54 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あか　　"
    .marubatsu "红　　　"
  ; .marubatsu "あお　　"
    .marubatsu "蓝　　　"
  ; .marubatsu "きいろ　"
    .marubatsu "黄　　　"
  ; .marubatsu "むしょく　"
    .marubatsu "透明　　　"
  ; .marubatsu "みぎ　　"
    .marubatsu "右　　　"
  ; .marubatsu "ひだり　"
    .marubatsu "左　　　"
  ; .marubatsu "おく　　"
    .marubatsu "深处　　"
  ; .marubatsu "ちゅうおう　"
    .marubatsu "中央　　　　"
.orga (0x0D1CF0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かわいいあおバラ　"
    .marubatsu "萌蓝玫瑰　　　　　"
  ; .marubatsu "あくまのなみだ　"
    .marubatsu "泪眼恶魔　　　　"
  ; .marubatsu "ソロモンのカギ　"
    .marubatsu "所罗门钥匙　　　"
  ; .marubatsu "ヴイーナスのひとみ　"
    .marubatsu "维纳斯之眼　　　　　"
  ; .marubatsu "みぎ　　"
    .marubatsu "右　　　"
  ; .marubatsu "ひだり　"
    .marubatsu "左　　　"
  ; .marubatsu "おく　　"
    .marubatsu "深处　　"
  ; .marubatsu "ちゅうおう　"
    .marubatsu "中央　　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_11.tbl"
.orga (0x0D1DFE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１もじめ　"
    .marubatsu "第１个字　"
  ; .marubatsu "２もじめ　"
    .marubatsu "第２个字　"
  ; .marubatsu "３もじめ　"
    .marubatsu "第３个字　"
  ; .marubatsu "４もじめ　"
    .marubatsu "第４个字　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１个读　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２个读　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３个读　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４个读　"
.orga (0x0D1E9A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かわいいあおバラ　"
    .marubatsu "萌蓝玫瑰　　　　　"
  ; .marubatsu "あくまのなみだ　"
    .marubatsu "泪眼恶魔　　　　"
  ; .marubatsu "ソロモンのカギ　"
    .marubatsu "所罗门钥匙　　　"
  ; .marubatsu "ヴイーナスのひとみ　"
    .marubatsu "维纳斯之眼　　　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１个读　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２个读　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３个读　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４个读　"

.loadtable "marubatsu_tbl\marubatsu_chs_12.tbl"
.orga (0x0D1FA8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ベンチのした　"
    .marubatsu "长椅下面　　　"
  ; .marubatsu "ごみばこのちかく　"
    .marubatsu "垃圾桶旁　　　　　"
  ; .marubatsu "みずのみば　"
    .marubatsu "饮水处　　　"
  ; .marubatsu "きのした　"
    .marubatsu "树下　　　"
  ; .marubatsu "あか　　"
    .marubatsu "红　　　"
  ; .marubatsu "あお　　"
    .marubatsu "蓝　　　"
  ; .marubatsu "きいろ　"
    .marubatsu "黄　　　"
  ; .marubatsu "みどり　"
    .marubatsu "绿　　　"
.orga (0x0D2044 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あゆみ　"
    .marubatsu "步美　　"
  ; .marubatsu "げんた　"
    .marubatsu "元太　　"
  ; .marubatsu "みつひこ　"
    .marubatsu "光彦　　　"
  ; .marubatsu "コナン　"
    .marubatsu "柯南　　"
  ; .marubatsu "あか　　"
    .marubatsu "红　　　"
  ; .marubatsu "あお　　"
    .marubatsu "蓝　　　"
  ; .marubatsu "きいろ　"
    .marubatsu "黄　　　"
  ; .marubatsu "みどり　"
    .marubatsu "绿　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_13.tbl"
.orga (0x0D2152 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "マリブのかいぞく　"
    .marubatsu "海盗船　　　　　　"
  ; .marubatsu "カップ　"
    .marubatsu "茶杯　　"
  ; .marubatsu "コースター　"
    .marubatsu "云霄飞车　　"
  ; .marubatsu "かんらんしゃ　"
    .marubatsu "摩天轮　　　　"
  ; .marubatsu "くちのなか　"
    .marubatsu "口中　　　　"
  ; .marubatsu "さらのした　"
    .marubatsu "盘子下面　　"
  ; .marubatsu "ランタンのした　"
    .marubatsu "壁灯下面　　　　"
  ; .marubatsu "けんばいきのよこ　"
    .marubatsu "售票机旁　　　　　"
.orga (0x0D21EE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルビー　"
    .marubatsu "红宝石　"
  ; .marubatsu "サフアイヤ　"
    .marubatsu "蓝宝石　　　"
  ; .marubatsu "エメラルド　"
    .marubatsu "绿宝石　　　"
  ; .marubatsu "アメジスト　"
    .marubatsu "紫水晶　　　"
  ; .marubatsu "くちのなか　"
    .marubatsu "口中　　　　"
  ; .marubatsu "さらのした　"
    .marubatsu "盘子下面　　"
  ; .marubatsu "ランタンのした　"
    .marubatsu "壁灯下面　　　　"
  ; .marubatsu "けんばいきのよこ　"
    .marubatsu "售票机旁　　　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_14.tbl"
.orga (0x0D22FC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スペード　"
    .marubatsu "黑桃　　　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "方片　　"
  ; .marubatsu "ハート　"
    .marubatsu "红桃　　"
  ; .marubatsu "クラブ　"
    .marubatsu "梅花　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　　"
  ; .marubatsu "みぎ　　"
    .marubatsu "右　　　"
  ; .marubatsu "ひだり　"
    .marubatsu "左　　　"
  ; .marubatsu "うえ　　"
    .marubatsu "上　　　"
  ; .marubatsu "した　　"
    .marubatsu "下　　　"
.orga (0x0D2398 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルビー　"
    .marubatsu "红宝石　"
  ; .marubatsu "サフアイヤ　"
    .marubatsu "蓝宝石　　　"
  ; .marubatsu "エメラルド　"
    .marubatsu "绿宝石　　　"
  ; .marubatsu "アメジスト　"
    .marubatsu "紫水晶　　　"
  ; .marubatsu "みぎ　　"
    .marubatsu "右　　　"
  ; .marubatsu "ひだり　"
    .marubatsu "左　　　"
  ; .marubatsu "うえ　　"
    .marubatsu "上　　　"
  ; .marubatsu "した　　"
    .marubatsu "下　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_15.tbl"
.orga (0x0D24A6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "おす　　"
    .marubatsu "推　　　"
  ; .marubatsu "ひく　　"
    .marubatsu "拉　　　"
  ; .marubatsu "はずす　"
    .marubatsu "取下　　　"
  ; .marubatsu "さかさま　"
    .marubatsu "颠倒　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　　"
.orga (0x0D2542 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ジイ　　"
    .marubatsu "g　　　"
  ; .marubatsu "アイ　　"
    .marubatsu "i　　　"
  ; .marubatsu "エムエー　"
    .marubatsu "Ma　　　"
  ; .marubatsu "シー　　"
    .marubatsu "c　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_16.tbl"
.orga (0x0D2650 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルビー　"
    .marubatsu "ルビー　"
  ; .marubatsu "サフアイヤ　"
    .marubatsu "サフアイヤ　"
  ; .marubatsu "エメラルド　"
    .marubatsu "エメラルド　"
  ; .marubatsu "アメジスト　"
    .marubatsu "アメジスト　"
  ; .marubatsu "よこ１　"
    .marubatsu "よこ１　"
  ; .marubatsu "よこ２　"
    .marubatsu "よこ２　"
  ; .marubatsu "よこ３　"
    .marubatsu "よこ３　"
  ; .marubatsu "よこ４　"
    .marubatsu "よこ４　"
  ; .marubatsu "たに１　"
    .marubatsu "たに１　"
  ; .marubatsu "たに２　"
    .marubatsu "たに２　"
  ; .marubatsu "たに３　"
    .marubatsu "たに３　"
  ; .marubatsu "たに４　"
    .marubatsu "たに４　"
.orga (0x0D26EC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スペード　"
    .marubatsu "スペード　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "ダイヤ　"
  ; .marubatsu "ハート　"
    .marubatsu "ハート　"
  ; .marubatsu "クラブ　"
    .marubatsu "クラブ　"
  ; .marubatsu "たに１　"
    .marubatsu "たに１　"
  ; .marubatsu "たに２　"
    .marubatsu "たに２　"
  ; .marubatsu "たに３　"
    .marubatsu "たに３　"
  ; .marubatsu "たに４　"
    .marubatsu "たに４　"
  ; .marubatsu "よこ１　"
    .marubatsu "よこ１　"
  ; .marubatsu "よこ２　"
    .marubatsu "よこ２　"
  ; .marubatsu "よこ３　"
    .marubatsu "よこ３　"
  ; .marubatsu "よこ４　"
    .marubatsu "よこ４　"

.loadtable "marubatsu_tbl\marubatsu_chs_17.tbl"
.orga (0x0D27FA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スペード　"
    .marubatsu "スペード　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "ダイヤ　"
  ; .marubatsu "ハート　"
    .marubatsu "ハート　"
  ; .marubatsu "クラブ　"
    .marubatsu "クラブ　"
  ; .marubatsu "１かいめ　"
    .marubatsu "１かいめ　"
  ; .marubatsu "２かいめ　"
    .marubatsu "２かいめ　"
  ; .marubatsu "３かいめ　"
    .marubatsu "３かいめ　"
  ; .marubatsu "４かいめ　"
    .marubatsu "４かいめ　"
  ; .marubatsu "あとシー　"
    .marubatsu "あとシー　"
  ; .marubatsu "あとアイ　"
    .marubatsu "あとアイ　"
  ; .marubatsu "あとエイ　"
    .marubatsu "あとエイ　"
  ; .marubatsu "あとエヌ　"
    .marubatsu "あとエヌ　"
.orga (0x0D2896 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "まえエム　"
    .marubatsu "まえエム　"
  ; .marubatsu "まえエイ　"
    .marubatsu "まえエイ　"
  ; .marubatsu "まえジー　"
    .marubatsu "まえジー　"
  ; .marubatsu "まえアイ　"
    .marubatsu "まえアイ　"
  ; .marubatsu "あとシー　"
    .marubatsu "あとシー　"
  ; .marubatsu "あとアイ　"
    .marubatsu "あとアイ　"
  ; .marubatsu "あとエイ　"
    .marubatsu "あとエイ　"
  ; .marubatsu "あとエヌ　"
    .marubatsu "あとエヌ　"
  ; .marubatsu "１かいめ　"
    .marubatsu "１かいめ　"
  ; .marubatsu "２かいめ　"
    .marubatsu "２かいめ　"
  ; .marubatsu "３かいめ　"
    .marubatsu "３かいめ　"
  ; .marubatsu "４かいめ　"
    .marubatsu "４かいめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_18.tbl"
.orga (0x0D29A4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "みぎ　　"
    .marubatsu "みぎ　　"
  ; .marubatsu "ひだり　"
    .marubatsu "ひだり　"
  ; .marubatsu "うえ　　"
    .marubatsu "うえ　　"
  ; .marubatsu "した　　"
    .marubatsu "した　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
.orga (0x0D2A40 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "２　　　"
    .marubatsu "２　　　"
  ; .marubatsu "０　　　"
    .marubatsu "０　　　"
  ; .marubatsu "せい　　"
    .marubatsu "せい　　"
  ; .marubatsu "き　　　"
    .marubatsu "き　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_19.tbl"
.orga (0x0D2B4E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "みどり　"
    .marubatsu "みどり　"
  ; .marubatsu "ウラシマ　"
    .marubatsu "ウラシマ　"
  ; .marubatsu "ウサギ　"
    .marubatsu "ウサギ　"
  ; .marubatsu "ロケット　"
    .marubatsu "ロケット　"
  ; .marubatsu "げんた　"
    .marubatsu "げんた　"
  ; .marubatsu "あゆみ　"
    .marubatsu "あゆみ　"
  ; .marubatsu "コナン　"
    .marubatsu "コナン　"
  ; .marubatsu "みつひこ　"
    .marubatsu "みつひこ　"
.orga (0x0D2BEA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "コイ　　"
    .marubatsu "コイ　　"
  ; .marubatsu "カメ　　"
    .marubatsu "カメ　　"
  ; .marubatsu "うさぎ　"
    .marubatsu "うさぎ　"
  ; .marubatsu "ハト　　"
    .marubatsu "ハト　　"
  ; .marubatsu "げんた　"
    .marubatsu "げんた　"
  ; .marubatsu "あゆみ　"
    .marubatsu "あゆみ　"
  ; .marubatsu "コナン　"
    .marubatsu "コナン　"
  ; .marubatsu "みつひこ　"
    .marubatsu "みつひこ　"

.loadtable "marubatsu_tbl\marubatsu_chs_1A.tbl"
.orga (0x0D2CF8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
  ; .marubatsu "じむしょ　"
    .marubatsu "じむしょ　"
  ; .marubatsu "デパート　"
    .marubatsu "デパート　"
  ; .marubatsu "けいさつ　"
    .marubatsu "けいさつ　"
  ; .marubatsu "タワー　"
    .marubatsu "タワー　"
.orga (0x0D2D94 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シロ　　"
    .marubatsu "シロ　　"
  ; .marubatsu "クロ　　"
    .marubatsu "クロ　　"
  ; .marubatsu "トラ　　"
    .marubatsu "トラ　　"
  ; .marubatsu "ミケ　　"
    .marubatsu "ミケ　　"
  ; .marubatsu "じむしょ　"
    .marubatsu "じむしょ　"
  ; .marubatsu "デパート　"
    .marubatsu "デパート　"
  ; .marubatsu "けいさつ　"
    .marubatsu "けいさつ　"
  ; .marubatsu "タワー　"
    .marubatsu "タワー　"

.loadtable "marubatsu_tbl\marubatsu_chs_1B.tbl"
.orga (0x0D2EA2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "がくしゃ　"
    .marubatsu "がくしゃ　"
  ; .marubatsu "しょき　"
    .marubatsu "しょき　"
  ; .marubatsu "バイヤー　"
    .marubatsu "バイヤー　"
  ; .marubatsu "えいぞう　"
    .marubatsu "えいぞう　"
  ; .marubatsu "シングル　"
    .marubatsu "シングル　"
  ; .marubatsu "ダブル　"
    .marubatsu "ダブル　"
  ; .marubatsu "タイなし　"
    .marubatsu "タイなし　"
  ; .marubatsu "チャイナ　"
    .marubatsu "チャイナ　"
  ; .marubatsu "かいつけ　"
    .marubatsu "かいつけ　"
  ; .marubatsu "さつえい　"
    .marubatsu "さつえい　"
  ; .marubatsu "きぞう　"
    .marubatsu "きぞう　"
  ; .marubatsu "きょうみ　"
    .marubatsu "きょうみ　"
.orga (0x0D2F3E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "いぬい　"
    .marubatsu "いぬい　"
  ; .marubatsu "セルゲイ　"
    .marubatsu "セルゲイ　"
  ; .marubatsu "さがわ　"
    .marubatsu "さがわ　"
  ; .marubatsu "せいらん　"
    .marubatsu "せいらん　"
  ; .marubatsu "かいつけ　"
    .marubatsu "かいつけ　"
  ; .marubatsu "さつえい　"
    .marubatsu "さつえい　"
  ; .marubatsu "きぞう　"
    .marubatsu "きぞう　"
  ; .marubatsu "きょうみ　"
    .marubatsu "きょうみ　"
  ; .marubatsu "シングル　"
    .marubatsu "シングル　"
  ; .marubatsu "ダブル　"
    .marubatsu "ダブル　"
  ; .marubatsu "タイなし　"
    .marubatsu "タイなし　"
  ; .marubatsu "チャイナ　"
    .marubatsu "チャイナ　"

.loadtable "marubatsu_tbl\marubatsu_chs_1C.tbl"
.orga (0x0D304C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スミスアンドウエッソン　"
    .marubatsu "スミスアンドウエッソン　"
  ; .marubatsu "エム８９ビー　"
    .marubatsu "エム８９ビー　"
  ; .marubatsu "ワルサーピー３８　"
    .marubatsu "ワルサーピー３８　"
  ; .marubatsu "アダムス　"
    .marubatsu "アダムス　"
  ; .marubatsu "イギリスせい　"
    .marubatsu "イギリスせい　"
  ; .marubatsu "イタリアせい　"
    .marubatsu "イタリアせい　"
  ; .marubatsu "ドイツせい　"
    .marubatsu "ドイツせい　"
  ; .marubatsu "アメリカせい　"
    .marubatsu "アメリカせい　"
.orga (0x0D30E8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "もちづき　"
    .marubatsu "もちづき　"
  ; .marubatsu "こうの　"
    .marubatsu "こうの　"
  ; .marubatsu "はぎわら　"
    .marubatsu "はぎわら　"
  ; .marubatsu "いしざき　"
    .marubatsu "いしざき　"
  ; .marubatsu "イギリスせい　"
    .marubatsu "イギリスせい　"
  ; .marubatsu "イタリアせい　"
    .marubatsu "イタリアせい　"
  ; .marubatsu "ドイツせい　"
    .marubatsu "ドイツせい　"
  ; .marubatsu "アメリカせい　"
    .marubatsu "アメリカせい　"

.loadtable "marubatsu_tbl\marubatsu_chs_1D.tbl"
.orga (0x0D31F6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "コインロッカー　"
    .marubatsu "コインロッカー　"
  ; .marubatsu "かしきんこ　"
    .marubatsu "かしきんこ　"
  ; .marubatsu "そうこ　"
    .marubatsu "そうこ　"
  ; .marubatsu "じたく　"
    .marubatsu "じたく　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
.orga (0x0D3292 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ダイヤモンド　"
    .marubatsu "ダイヤモンド　"
  ; .marubatsu "サフアイア　"
    .marubatsu "サフアイア　"
  ; .marubatsu "エメラルド　"
    .marubatsu "エメラルド　"
  ; .marubatsu "ルビー　"
    .marubatsu "ルビー　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_1E.tbl"
.orga (0x0D33A0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ようじんあんさつ　"
    .marubatsu "ようじんあんさつ　"
  ; .marubatsu "じょせいさつがい　"
    .marubatsu "じょせいさつがい　"
  ; .marubatsu "けいさつかんさつがい　"
    .marubatsu "けいさつかんさつがい　"
  ; .marubatsu "みすい　ふうふさつがい　"
    .marubatsu "みすい　ふうふさつがい　"
  ; .marubatsu "１かげつまえ　"
    .marubatsu "１かげつまえ　"
  ; .marubatsu "はんとしまえ　"
    .marubatsu "はんとしまえ　"
  ; .marubatsu "いちねんまえ　"
    .marubatsu "いちねんまえ　"
  ; .marubatsu "にねんまえ　"
    .marubatsu "にねんまえ　"
.orga (0x0D343C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ベアー　"
    .marubatsu "ベアー　"
  ; .marubatsu "ウルフ　"
    .marubatsu "ウルフ　"
  ; .marubatsu "イーグル　"
    .marubatsu "イーグル　"
  ; .marubatsu "タイガー　"
    .marubatsu "タイガー　"
  ; .marubatsu "１かげつまえ　"
    .marubatsu "１かげつまえ　"
  ; .marubatsu "はんとしまえ　"
    .marubatsu "はんとしまえ　"
  ; .marubatsu "いちねんまえ　"
    .marubatsu "いちねんまえ　"
  ; .marubatsu "にねんまえ　"
    .marubatsu "にねんまえ　"

.loadtable "marubatsu_tbl\marubatsu_chs_1F.tbl"
.orga (0x0D354A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "はは　　"
    .marubatsu "はは　　"
  ; .marubatsu "あね　　"
    .marubatsu "あね　　"
  ; .marubatsu "あに　　"
    .marubatsu "あに　　"
  ; .marubatsu "おとうと　"
    .marubatsu "おとうと　"
  ; .marubatsu "２まんえん　"
    .marubatsu "２まんえん　"
  ; .marubatsu "１まんえん　"
    .marubatsu "１まんえん　"
  ; .marubatsu "６せんえん　"
    .marubatsu "６せんえん　"
  ; .marubatsu "３ぜんえん　"
    .marubatsu "３ぜんえん　"
  ; .marubatsu "きのう　"
    .marubatsu "きのう　"
  ; .marubatsu "けさ　　"
    .marubatsu "けさ　　"
  ; .marubatsu "ひる　　"
    .marubatsu "ひる　　"
  ; .marubatsu "よる　　"
    .marubatsu "よる　　"
.orga (0x0D35E6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１かん　"
    .marubatsu "１かん　"
  ; .marubatsu "２かん　"
    .marubatsu "２かん　"
  ; .marubatsu "３かん　"
    .marubatsu "３かん　"
  ; .marubatsu "４かん　"
    .marubatsu "４かん　"
  ; .marubatsu "きのう　"
    .marubatsu "きのう　"
  ; .marubatsu "けさ　　"
    .marubatsu "けさ　　"
  ; .marubatsu "ひる　　"
    .marubatsu "ひる　　"
  ; .marubatsu "よる　　"
    .marubatsu "よる　　"
  ; .marubatsu "２まんえん　"
    .marubatsu "２まんえん　"
  ; .marubatsu "１まんえん　"
    .marubatsu "１まんえん　"
  ; .marubatsu "６せんえん　"
    .marubatsu "６せんえん　"
  ; .marubatsu "３ぜんえん　"
    .marubatsu "３ぜんえん　"

.loadtable "marubatsu_tbl\marubatsu_chs_20.tbl"
.orga (0x0D36F4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こむぎこ　"
    .marubatsu "こむぎこ　"
  ; .marubatsu "ベーキングパウダー　"
    .marubatsu "ベーキングパウダー　"
  ; .marubatsu "たまご　"
    .marubatsu "たまご　"
  ; .marubatsu "さとう　"
    .marubatsu "さとう　"
  ; .marubatsu "１ばんめに　"
    .marubatsu "１ばんめに　"
  ; .marubatsu "２ばんめに　"
    .marubatsu "２ばんめに　"
  ; .marubatsu "３ばんめに　"
    .marubatsu "３ばんめに　"
  ; .marubatsu "４ばんめに　"
    .marubatsu "４ばんめに　"
  ; .marubatsu "５グラム　"
    .marubatsu "５グラム　"
  ; .marubatsu "５０グラム　"
    .marubatsu "５０グラム　"
  ; .marubatsu "５５グラム　"
    .marubatsu "５５グラム　"
  ; .marubatsu "１００グラム　"
    .marubatsu "１００グラム　"
.orga (0x0D3790 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あかいけ　"
    .marubatsu "あかいけ　"
  ; .marubatsu "ささもと　"
    .marubatsu "ささもと　"
  ; .marubatsu "なかざわ　"
    .marubatsu "なかざわ　"
  ; .marubatsu "たけむら　"
    .marubatsu "たけむら　"
  ; .marubatsu "５グラム　"
    .marubatsu "５グラム　"
  ; .marubatsu "５０グラム　"
    .marubatsu "５０グラム　"
  ; .marubatsu "５５グラム　"
    .marubatsu "５５グラム　"
  ; .marubatsu "１００グラム　"
    .marubatsu "１００グラム　"
  ; .marubatsu "１ばんめに　"
    .marubatsu "１ばんめに　"
  ; .marubatsu "２ばんめに　"
    .marubatsu "２ばんめに　"
  ; .marubatsu "３ばんめに　"
    .marubatsu "３ばんめに　"
  ; .marubatsu "４ばんめに　"
    .marubatsu "４ばんめに　"

.loadtable "marubatsu_tbl\marubatsu_chs_21.tbl"
.orga (0x0D389E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "まやく　"
    .marubatsu "まやく　"
  ; .marubatsu "ピストル　"
    .marubatsu "ピストル　"
  ; .marubatsu "ブラジャー　"
    .marubatsu "ブラジャー　"
  ; .marubatsu "ナイフ　"
    .marubatsu "ナイフ　"
  ; .marubatsu "デイパック　"
    .marubatsu "デイパック　"
  ; .marubatsu "ボストンバッグ　"
    .marubatsu "ボストンバッグ　"
  ; .marubatsu "セカンドバッグ　"
    .marubatsu "セカンドバッグ　"
  ; .marubatsu "スーツケース　"
    .marubatsu "スーツケース　"
.orga (0x0D393A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "おかだ　"
    .marubatsu "おかだ　"
  ; .marubatsu "もり　　"
    .marubatsu "もり　　"
  ; .marubatsu "やぎ　　"
    .marubatsu "やぎ　　"
  ; .marubatsu "まるやま　"
    .marubatsu "まるやま　"
  ; .marubatsu "デイパック　"
    .marubatsu "デイパック　"
  ; .marubatsu "ボストンバッグ　"
    .marubatsu "ボストンバッグ　"
  ; .marubatsu "セカンドバッグ　"
    .marubatsu "セカンドバッグ　"
  ; .marubatsu "スーツケース　"
    .marubatsu "スーツケース　"

.loadtable "marubatsu_tbl\marubatsu_chs_22.tbl"
.orga (0x0D3A48 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ロビーで　"
    .marubatsu "ロビーで　"
  ; .marubatsu "なかにわで　"
    .marubatsu "なかにわで　"
  ; .marubatsu "へやで　"
    .marubatsu "へやで　"
  ; .marubatsu "バーで　"
    .marubatsu "バーで　"
  ; .marubatsu "０９５０に　"
    .marubatsu "０９５０に　"
  ; .marubatsu "１０１０に　"
    .marubatsu "１０１０に　"
  ; .marubatsu "１０２０に　"
    .marubatsu "１０２０に　"
  ; .marubatsu "１０３０に　"
    .marubatsu "１０３０に　"
.orga (0x0D3AE4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "いけま　"
    .marubatsu "いけま　"
  ; .marubatsu "とくなが　"
    .marubatsu "とくなが　"
  ; .marubatsu "しまや　"
    .marubatsu "しまや　"
  ; .marubatsu "すながわ　"
    .marubatsu "すながわ　"
  ; .marubatsu "０９５０に　"
    .marubatsu "０９５０に　"
  ; .marubatsu "１０１０に　"
    .marubatsu "１０１０に　"
  ; .marubatsu "１０２０に　"
    .marubatsu "１０２０に　"
  ; .marubatsu "１０３０に　"
    .marubatsu "１０３０に　"

.loadtable "marubatsu_tbl\marubatsu_chs_23.tbl"
.orga (0x0D3BF2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シュークリーム　"
    .marubatsu "シュークリーム　"
  ; .marubatsu "チョコケーキ　"
    .marubatsu "チョコケーキ　"
  ; .marubatsu "イチゴショート　"
    .marubatsu "イチゴショート　"
  ; .marubatsu "チーズケーキ　"
    .marubatsu "チーズケーキ　"
  ; .marubatsu "３００えん　"
    .marubatsu "３００えん　"
  ; .marubatsu "４００えん　"
    .marubatsu "４００えん　"
  ; .marubatsu "５００えん　"
    .marubatsu "５００えん　"
  ; .marubatsu "６００えん　"
    .marubatsu "６００えん　"
.orga (0x0D3C8E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "うさぎや　"
    .marubatsu "うさぎや　"
  ; .marubatsu "フランセ　"
    .marubatsu "フランセ　"
  ; .marubatsu "ビーグル　"
    .marubatsu "ビーグル　"
  ; .marubatsu "パンダや　"
    .marubatsu "パンダや　"
  ; .marubatsu "３００えん　"
    .marubatsu "３００えん　"
  ; .marubatsu "４００えん　"
    .marubatsu "４００えん　"
  ; .marubatsu "５００えん　"
    .marubatsu "５００えん　"
  ; .marubatsu "６００えん　"
    .marubatsu "６００えん　"

.loadtable "marubatsu_tbl\marubatsu_chs_24.tbl"
.orga (0x0D3D9C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "そばや　"
    .marubatsu "そばや　"
  ; .marubatsu "きっさてん　"
    .marubatsu "きっさてん　"
  ; .marubatsu "ラーメンや　"
    .marubatsu "ラーメンや　"
  ; .marubatsu "カレーせんもんてん　"
    .marubatsu "カレーせんもんてん　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１ちょうめ　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２ちょうめ　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３ちょうめ　"
  ; .marubatsu "４ちょうめ　"
    .marubatsu "４ちょうめ　"
  ; .marubatsu "げつようび　"
    .marubatsu "げつようび　"
  ; .marubatsu "すいようび　"
    .marubatsu "すいようび　"
  ; .marubatsu "きんようび　"
    .marubatsu "きんようび　"
  ; .marubatsu "にちようび　"
    .marubatsu "にちようび　"
.orga (0x0D3E38 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "さくら　"
    .marubatsu "さくら　"
  ; .marubatsu "パンジー　"
    .marubatsu "パンジー　"
  ; .marubatsu "アイリス　"
    .marubatsu "アイリス　"
  ; .marubatsu "うめ　　"
    .marubatsu "うめ　　"
  ; .marubatsu "げつようび　"
    .marubatsu "げつようび　"
  ; .marubatsu "すいようび　"
    .marubatsu "すいようび　"
  ; .marubatsu "きんようび　"
    .marubatsu "きんようび　"
  ; .marubatsu "にちようび　"
    .marubatsu "にちようび　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１ちょうめ　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２ちょうめ　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３ちょうめ　"
  ; .marubatsu "４ちょうめ　"
    .marubatsu "４ちょうめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_25.tbl"
.orga (0x0D3F46 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "まさと　"
    .marubatsu "まさと　"
  ; .marubatsu "ゆか　　"
    .marubatsu "ゆか　　"
  ; .marubatsu "たかのり　"
    .marubatsu "たかのり　"
  ; .marubatsu "きょうこ　"
    .marubatsu "きょうこ　"
  ; .marubatsu "しょくひんうりば　"
    .marubatsu "しょくひんうりば　"
  ; .marubatsu "しんしふくうりば　"
    .marubatsu "しんしふくうりば　"
  ; .marubatsu "ふじんふくうりば　"
    .marubatsu "ふじんふくうりば　"
  ; .marubatsu "おもちゃうりば　"
    .marubatsu "おもちゃうりば　"
  ; .marubatsu "２さい　"
    .marubatsu "２さい　"
  ; .marubatsu "３さい　"
    .marubatsu "３さい　"
  ; .marubatsu "４さい　"
    .marubatsu "４さい　"
  ; .marubatsu "５さい　"
    .marubatsu "５さい　"
.orga (0x0D3FE2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "なかむら　"
    .marubatsu "なかむら　"
  ; .marubatsu "こうの　"
    .marubatsu "こうの　"
  ; .marubatsu "たけはら　"
    .marubatsu "たけはら　"
  ; .marubatsu "さいとう　"
    .marubatsu "さいとう　"
  ; .marubatsu "２さい　"
    .marubatsu "２さい　"
  ; .marubatsu "３さい　"
    .marubatsu "３さい　"
  ; .marubatsu "４さい　"
    .marubatsu "４さい　"
  ; .marubatsu "５さい　"
    .marubatsu "５さい　"
  ; .marubatsu "しょくひんうりば　"
    .marubatsu "しょくひんうりば　"
  ; .marubatsu "しんしふくうりば　"
    .marubatsu "しんしふくうりば　"
  ; .marubatsu "ふじんふくうりば　"
    .marubatsu "ふじんふくうりば　"
  ; .marubatsu "おもちゃうりば　"
    .marubatsu "おもちゃうりば　"

.loadtable "marubatsu_tbl\marubatsu_chs_26.tbl"
.orga (0x0D40F0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ロープ　"
    .marubatsu "ロープ　"
  ; .marubatsu "ジーパン　"
    .marubatsu "ジーパン　"
  ; .marubatsu "ナイフ　"
    .marubatsu "ナイフ　"
  ; .marubatsu "シャツ　"
    .marubatsu "シャツ　"
  ; .marubatsu "かわにすてた　"
    .marubatsu "かわにすてた　"
  ; .marubatsu "こうえんでもやした　"
    .marubatsu "こうえんでもやした　"
  ; .marubatsu "ごみすてばにすてた　"
    .marubatsu "ごみすてばにすてた　"
  ; .marubatsu "やまにうめた　"
    .marubatsu "やまにうめた　"
.orga (0x0D418C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめにすてた　"
    .marubatsu "１ばんめにすてた　"
  ; .marubatsu "２ばんめにすてた　"
    .marubatsu "２ばんめにすてた　"
  ; .marubatsu "３ばんめにすてた　"
    .marubatsu "３ばんめにすてた　"
  ; .marubatsu "４ばんめにすてた　"
    .marubatsu "４ばんめにすてた　"
  ; .marubatsu "かわにすてた　"
    .marubatsu "かわにすてた　"
  ; .marubatsu "こうえんでもやした　"
    .marubatsu "こうえんでもやした　"
  ; .marubatsu "ごみすてばにすてた　"
    .marubatsu "ごみすてばにすてた　"
  ; .marubatsu "やまにうめた　"
    .marubatsu "やまにうめた　"

.loadtable "marubatsu_tbl\marubatsu_chs_27.tbl"
.orga (0x0D429A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
  ; .marubatsu "やきもの　"
    .marubatsu "やきもの　"
  ; .marubatsu "ゴルフクラブ　"
    .marubatsu "ゴルフクラブ　"
  ; .marubatsu "にほんとう　"
    .marubatsu "にほんとう　"
  ; .marubatsu "ネクタイ　"
    .marubatsu "ネクタイ　"
.orga (0x0D4336 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "なかがわ　"
    .marubatsu "なかがわ　"
  ; .marubatsu "まき　　"
    .marubatsu "まき　　"
  ; .marubatsu "たむら　"
    .marubatsu "たむら　"
  ; .marubatsu "おおはし　"
    .marubatsu "おおはし　"
  ; .marubatsu "やきもの　"
    .marubatsu "やきもの　"
  ; .marubatsu "ゴルフクラブ　"
    .marubatsu "ゴルフクラブ　"
  ; .marubatsu "にほんとう　"
    .marubatsu "にほんとう　"
  ; .marubatsu "ネクタイ　"
    .marubatsu "ネクタイ　"

.loadtable "marubatsu_tbl\marubatsu_chs_28.tbl"
.orga (0x0D4444 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "トロのにぎり　"
    .marubatsu "トロのにぎり　"
  ; .marubatsu "アジのにぎり　"
    .marubatsu "アジのにぎり　"
  ; .marubatsu "タコのにぎり　"
    .marubatsu "タコのにぎり　"
  ; .marubatsu "サバのにぎり　"
    .marubatsu "サバのにぎり　"
  ; .marubatsu "きよし　"
    .marubatsu "きよし　"
  ; .marubatsu "あおい　"
    .marubatsu "あおい　"
  ; .marubatsu "のぶみち　"
    .marubatsu "のぶみち　"
  ; .marubatsu "たかひろ　"
    .marubatsu "たかひろ　"
.orga (0x0D44E0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "サヤカ　"
    .marubatsu "サヤカ　"
  ; .marubatsu "ノリコ　"
    .marubatsu "ノリコ　"
  ; .marubatsu "エリカ　"
    .marubatsu "エリカ　"
  ; .marubatsu "マキ　　"
    .marubatsu "マキ　　"
  ; .marubatsu "きよし　"
    .marubatsu "きよし　"
  ; .marubatsu "あおい　"
    .marubatsu "あおい　"
  ; .marubatsu "のぶみち　"
    .marubatsu "のぶみち　"
  ; .marubatsu "たかひろ　"
    .marubatsu "たかひろ　"

.loadtable "marubatsu_tbl\marubatsu_chs_29.tbl"
.orga (0x0D45EE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "たいようがもえもえ　"
    .marubatsu "たいようがもえもえ　"
  ; .marubatsu "かがやくきせつ　"
    .marubatsu "かがやくきせつ　"
  ; .marubatsu "かもね　"
    .marubatsu "かもね　"
  ; .marubatsu "だんごのおやこ　"
    .marubatsu "だんごのおやこ　"
  ; .marubatsu "ザ　モンキー　"
    .marubatsu "ザ　モンキー　"
  ; .marubatsu "かねこまみ　"
    .marubatsu "かねこまみ　"
  ; .marubatsu "ジョージながおか　"
    .marubatsu "ジョージながおか　"
  ; .marubatsu "ようこ　"
    .marubatsu "ようこ　"
  ; .marubatsu "ロック　"
    .marubatsu "ロック　"
  ; .marubatsu "えんか　"
    .marubatsu "えんか　"
  ; .marubatsu "ラップ　"
    .marubatsu "ラップ　"
  ; .marubatsu "アニメソング　"
    .marubatsu "アニメソング　"
.orga (0x0D468A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめのうた　"
    .marubatsu "１ばんめのうた　"
  ; .marubatsu "２ばんめのうた　"
    .marubatsu "２ばんめのうた　"
  ; .marubatsu "３ばんめのうた　"
    .marubatsu "３ばんめのうた　"
  ; .marubatsu "４ばんめのうた　"
    .marubatsu "４ばんめのうた　"
  ; .marubatsu "ロック　"
    .marubatsu "ロック　"
  ; .marubatsu "えんか　"
    .marubatsu "えんか　"
  ; .marubatsu "ラップ　"
    .marubatsu "ラップ　"
  ; .marubatsu "アニメソング　"
    .marubatsu "アニメソング　"
  ; .marubatsu "ザ　モンキー　"
    .marubatsu "ザ　モンキー　"
  ; .marubatsu "かねこまみ　"
    .marubatsu "かねこまみ　"
  ; .marubatsu "ジョージながおか　"
    .marubatsu "ジョージながおか　"
  ; .marubatsu "ようこ　"
    .marubatsu "ようこ　"

.loadtable "marubatsu_tbl\marubatsu_chs_2A.tbl"
.orga (0x0D4798 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１０００まんえん　"
    .marubatsu "１０００まんえん　"
  ; .marubatsu "２０００まんえん　"
    .marubatsu "２０００まんえん　"
  ; .marubatsu "３０００まんえん　"
    .marubatsu "３０００まんえん　"
  ; .marubatsu "４０００まんえん　"
    .marubatsu "４０００まんえん　"
  ; .marubatsu "くろいカバン　"
    .marubatsu "くろいカバン　"
  ; .marubatsu "あおいカバン　"
    .marubatsu "あおいカバン　"
  ; .marubatsu "しろいカバン　"
    .marubatsu "しろいカバン　"
  ; .marubatsu "あかいカバン　"
    .marubatsu "あかいカバン　"
  ; .marubatsu "でんわボックス　"
    .marubatsu "でんわボックス　"
  ; .marubatsu "コインロッカー　"
    .marubatsu "コインロッカー　"
  ; .marubatsu "こうしゅうトイレ　"
    .marubatsu "こうしゅうトイレ　"
  ; .marubatsu "こうえんのベンチ　"
    .marubatsu "こうえんのベンチ　"
.orga (0x0D4834 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ちちおや　"
    .marubatsu "ちちおや　"
  ; .marubatsu "ははおや　"
    .marubatsu "ははおや　"
  ; .marubatsu "あね　　"
    .marubatsu "あね　　"
  ; .marubatsu "あに　　"
    .marubatsu "あに　　"
  ; .marubatsu "でんわボックス　"
    .marubatsu "でんわボックス　"
  ; .marubatsu "コインロッカー　"
    .marubatsu "コインロッカー　"
  ; .marubatsu "こうしゅうトイレ　"
    .marubatsu "こうしゅうトイレ　"
  ; .marubatsu "こうえんのベンチ　"
    .marubatsu "こうえんのベンチ　"
  ; .marubatsu "くろいカバン　"
    .marubatsu "くろいカバン　"
  ; .marubatsu "あおいカバン　"
    .marubatsu "あおいカバン　"
  ; .marubatsu "しろいカバン　"
    .marubatsu "しろいカバン　"
  ; .marubatsu "あかいカバン　"
    .marubatsu "あかいカバン　"

.loadtable "marubatsu_tbl\marubatsu_chs_2B.tbl"
.orga (0x0D4942 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルパン　"
    .marubatsu "ルパン　"
  ; .marubatsu "ホームズ　"
    .marubatsu "ホームズ　"
  ; .marubatsu "ポアロ　"
    .marubatsu "ポアロ　"
  ; .marubatsu "マーブル　"
    .marubatsu "マーブル　"
  ; .marubatsu "１じに　"
    .marubatsu "１じに　"
  ; .marubatsu "２じに　"
    .marubatsu "２じに　"
  ; .marubatsu "３じに　"
    .marubatsu "３じに　"
  ; .marubatsu "４じに　"
    .marubatsu "４じに　"
.orga (0x0D49DE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こうえん　"
    .marubatsu "こうえん　"
  ; .marubatsu "デパート　"
    .marubatsu "デパート　"
  ; .marubatsu "ホテル　"
    .marubatsu "ホテル　"
  ; .marubatsu "こうこう　"
    .marubatsu "こうこう　"
  ; .marubatsu "１じに　"
    .marubatsu "１じに　"
  ; .marubatsu "２じに　"
    .marubatsu "２じに　"
  ; .marubatsu "３じに　"
    .marubatsu "３じに　"
  ; .marubatsu "４じに　"
    .marubatsu "４じに　"

.loadtable "marubatsu_tbl\marubatsu_chs_2C.tbl"
.orga (0x0D4AEC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ほし　　"
    .marubatsu "ほし　　"
  ; .marubatsu "タロット　"
    .marubatsu "タロット　"
  ; .marubatsu "てそう　"
    .marubatsu "てそう　"
  ; .marubatsu "にんそう　"
    .marubatsu "にんそう　"
  ; .marubatsu "１ばんにんき　"
    .marubatsu "１ばんにんき　"
  ; .marubatsu "２ばんにんき　"
    .marubatsu "２ばんにんき　"
  ; .marubatsu "３ばんにんき　"
    .marubatsu "３ばんにんき　"
  ; .marubatsu "４ばんにんき　"
    .marubatsu "４ばんにんき　"
.orga (0x0D4B88 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ひがしのへや　"
    .marubatsu "ひがしのへや　"
  ; .marubatsu "にしのへや　"
    .marubatsu "にしのへや　"
  ; .marubatsu "みなみのへや　"
    .marubatsu "みなみのへや　"
  ; .marubatsu "きたのへや　"
    .marubatsu "きたのへや　"
  ; .marubatsu "１ばんにんき　"
    .marubatsu "１ばんにんき　"
  ; .marubatsu "２ばんにんき　"
    .marubatsu "２ばんにんき　"
  ; .marubatsu "３ばんにんき　"
    .marubatsu "３ばんにんき　"
  ; .marubatsu "４ばんにんき　"
    .marubatsu "４ばんにんき　"

.loadtable "marubatsu_tbl\marubatsu_chs_2D.tbl"
.orga (0x0D4C96 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しょくどう　"
    .marubatsu "しょくどう　"
  ; .marubatsu "リビングルーム　"
    .marubatsu "リビングルーム　"
  ; .marubatsu "ベランダ　"
    .marubatsu "ベランダ　"
  ; .marubatsu "ベッドルーム　"
    .marubatsu "ベッドルーム　"
  ; .marubatsu "コーヒー　"
    .marubatsu "コーヒー　"
  ; .marubatsu "こうちゃ　"
    .marubatsu "こうちゃ　"
  ; .marubatsu "ばんちゃ　"
    .marubatsu "ばんちゃ　"
  ; .marubatsu "ホットミルク　"
    .marubatsu "ホットミルク　"
  ; .marubatsu "あさ　　"
    .marubatsu "あさ　　"
  ; .marubatsu "ひる　　"
    .marubatsu "ひる　　"
  ; .marubatsu "ゆうがた　"
    .marubatsu "ゆうがた　"
  ; .marubatsu "よる　　"
    .marubatsu "よる　　"
.orga (0x0D4D32 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あかいカップ　"
    .marubatsu "あかいカップ　"
  ; .marubatsu "しろいカップ　"
    .marubatsu "しろいカップ　"
  ; .marubatsu "くろいカップ　"
    .marubatsu "くろいカップ　"
  ; .marubatsu "みどりのカップ　"
    .marubatsu "みどりのカップ　"
  ; .marubatsu "あさ　　"
    .marubatsu "あさ　　"
  ; .marubatsu "ひる　　"
    .marubatsu "ひる　　"
  ; .marubatsu "ゆうがた　"
    .marubatsu "ゆうがた　"
  ; .marubatsu "よる　　"
    .marubatsu "よる　　"
  ; .marubatsu "コーヒー　"
    .marubatsu "コーヒー　"
  ; .marubatsu "こうちゃ　"
    .marubatsu "こうちゃ　"
  ; .marubatsu "ばんちゃ　"
    .marubatsu "ばんちゃ　"
  ; .marubatsu "ホットミルク　"
    .marubatsu "ホットミルク　"

.loadtable "marubatsu_tbl\marubatsu_chs_2E.tbl"
.orga (0x0D4E40 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１２じに　"
    .marubatsu "１２じに　"
  ; .marubatsu "１じに　"
    .marubatsu "１じに　"
  ; .marubatsu "２じに　"
    .marubatsu "２じに　"
  ; .marubatsu "３じに　"
    .marubatsu "３じに　"
  ; .marubatsu "ぎんこう　"
    .marubatsu "ぎんこう　"
  ; .marubatsu "スーパー　"
    .marubatsu "スーパー　"
  ; .marubatsu "がっこう　"
    .marubatsu "がっこう　"
  ; .marubatsu "アパート　"
    .marubatsu "アパート　"
  ; .marubatsu "ごみばこがもえた　"
    .marubatsu "ごみばこがもえた　"
  ; .marubatsu "くるまがもえた　"
    .marubatsu "くるまがもえた　"
  ; .marubatsu "ビニールがもえた　"
    .marubatsu "ビニールがもえた　"
  ; .marubatsu "ポスターがもえた　"
    .marubatsu "ポスターがもえた　"
.orga (0x0D4EDC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "くわはら　"
    .marubatsu "くわはら　"
  ; .marubatsu "のぐち　"
    .marubatsu "のぐち　"
  ; .marubatsu "えばた　"
    .marubatsu "えばた　"
  ; .marubatsu "なかはら　"
    .marubatsu "なかはら　"
  ; .marubatsu "ごみばこがもえた　"
    .marubatsu "ごみばこがもえた　"
  ; .marubatsu "くるまがもえた　"
    .marubatsu "くるまがもえた　"
  ; .marubatsu "ビニールがもえた　"
    .marubatsu "ビニールがもえた　"
  ; .marubatsu "ポスターがもえた　"
    .marubatsu "ポスターがもえた　"
  ; .marubatsu "ぎんこう　"
    .marubatsu "ぎんこう　"
  ; .marubatsu "スーパー　"
    .marubatsu "スーパー　"
  ; .marubatsu "がっこう　"
    .marubatsu "がっこう　"
  ; .marubatsu "アパート　"
    .marubatsu "アパート　"

.loadtable "marubatsu_tbl\marubatsu_chs_2F.tbl"
.orga (0x0D4FEA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "きんけん　"
    .marubatsu "きんけん　"
  ; .marubatsu "つぼ　　"
    .marubatsu "つぼ　　"
  ; .marubatsu "げんきん　"
    .marubatsu "げんきん　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "ダイヤ　"
  ; .marubatsu "５まんえん　"
    .marubatsu "５まんえん　"
  ; .marubatsu "１０まんえん　"
    .marubatsu "１０まんえん　"
  ; .marubatsu "３０まんえん　"
    .marubatsu "３０まんえん　"
  ; .marubatsu "８０まんえん　"
    .marubatsu "８０まんえん　"
  ; .marubatsu "きょう　"
    .marubatsu "きょう　"
  ; .marubatsu "きのう　"
    .marubatsu "きのう　"
  ; .marubatsu "５にちまえ　"
    .marubatsu "５にちまえ　"
  ; .marubatsu "７にちまえ　"
    .marubatsu "７にちまえ　"
.orga (0x0D5086 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "いしゃのいえ　"
    .marubatsu "いしゃのいえ　"
  ; .marubatsu "はいゆうのいえ　"
    .marubatsu "はいゆうのいえ　"
  ; .marubatsu "べんごしのいえ　"
    .marubatsu "べんごしのいえ　"
  ; .marubatsu "きょうしのいえ　"
    .marubatsu "きょうしのいえ　"
  ; .marubatsu "きょう　"
    .marubatsu "きょう　"
  ; .marubatsu "きのう　"
    .marubatsu "きのう　"
  ; .marubatsu "５にちまえ　"
    .marubatsu "５にちまえ　"
  ; .marubatsu "７にちまえ　"
    .marubatsu "７にちまえ　"
  ; .marubatsu "５まんえん　"
    .marubatsu "５まんえん　"
  ; .marubatsu "１０まんえん　"
    .marubatsu "１０まんえん　"
  ; .marubatsu "３０まんえん　"
    .marubatsu "３０まんえん　"
  ; .marubatsu "８０まんえん　"
    .marubatsu "８０まんえん　"

.loadtable "marubatsu_tbl\marubatsu_chs_30.tbl"
.orga (0x0D5194 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アジト１　"
    .marubatsu "アジト１　"
  ; .marubatsu "アジト２　"
    .marubatsu "アジト２　"
  ; .marubatsu "アジト３　"
    .marubatsu "アジト３　"
  ; .marubatsu "アジト４　"
    .marubatsu "アジト４　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１ちょうめ　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２ちょうめ　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３ちょうめ　"
  ; .marubatsu "となりまち　"
    .marubatsu "となりまち　"
.orga (0x0D5230 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かわい　"
    .marubatsu "かわい　"
  ; .marubatsu "おきた　"
    .marubatsu "おきた　"
  ; .marubatsu "とよだ　"
    .marubatsu "とよだ　"
  ; .marubatsu "かわぐち　"
    .marubatsu "かわぐち　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１ちょうめ　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２ちょうめ　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３ちょうめ　"
  ; .marubatsu "となりまち　"
    .marubatsu "となりまち　"

.loadtable "marubatsu_tbl\marubatsu_chs_31.tbl"
.orga (0x0D533E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ポーカー　"
    .marubatsu "ポーカー　"
  ; .marubatsu "ルーレット　"
    .marubatsu "ルーレット　"
  ; .marubatsu "スロット　"
    .marubatsu "スロット　"
  ; .marubatsu "バカラ　"
    .marubatsu "バカラ　"
  ; .marubatsu "１００チップ　"
    .marubatsu "１００チップ　"
  ; .marubatsu "２００チップ　"
    .marubatsu "２００チップ　"
  ; .marubatsu "３００チップ　"
    .marubatsu "３００チップ　"
  ; .marubatsu "４００チップ　"
    .marubatsu "４００チップ　"
.orga (0x0D53DA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あかい　"
    .marubatsu "あかい　"
  ; .marubatsu "あおの　"
    .marubatsu "あおの　"
  ; .marubatsu "きじま　"
    .marubatsu "きじま　"
  ; .marubatsu "くろさき　"
    .marubatsu "くろさき　"
  ; .marubatsu "１００チップ　"
    .marubatsu "１００チップ　"
  ; .marubatsu "２００チップ　"
    .marubatsu "２００チップ　"
  ; .marubatsu "３００チップ　"
    .marubatsu "３００チップ　"
  ; .marubatsu "４００チップ　"
    .marubatsu "４００チップ　"

.loadtable "marubatsu_tbl\marubatsu_chs_32.tbl"
.orga (0x0D54E8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ひでき　"
    .marubatsu "ひでき　"
  ; .marubatsu "さとる　"
    .marubatsu "さとる　"
  ; .marubatsu "よういち　"
    .marubatsu "よういち　"
  ; .marubatsu "てっぺい　"
    .marubatsu "てっぺい　"
  ; .marubatsu "げつようび　"
    .marubatsu "げつようび　"
  ; .marubatsu "かようび　"
    .marubatsu "かようび　"
  ; .marubatsu "すいようび　"
    .marubatsu "すいようび　"
  ; .marubatsu "もくようび　"
    .marubatsu "もくようび　"
.orga (0x0D5584 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "はるか　"
    .marubatsu "はるか　"
  ; .marubatsu "なつみ　"
    .marubatsu "なつみ　"
  ; .marubatsu "あきえ　"
    .marubatsu "あきえ　"
  ; .marubatsu "ふゆこ　"
    .marubatsu "ふゆこ　"
  ; .marubatsu "げつようび　"
    .marubatsu "げつようび　"
  ; .marubatsu "かようび　"
    .marubatsu "かようび　"
  ; .marubatsu "すいようび　"
    .marubatsu "すいようび　"
  ; .marubatsu "もくようび　"
    .marubatsu "もくようび　"

.loadtable "marubatsu_tbl\marubatsu_chs_33.tbl"
.orga (0x0D5692 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "マイコ　"
    .marubatsu "マイコ　"
  ; .marubatsu "ユウコ　"
    .marubatsu "ユウコ　"
  ; .marubatsu "アユミ　"
    .marubatsu "アユミ　"
  ; .marubatsu "ナツコ　"
    .marubatsu "ナツコ　"
  ; .marubatsu "おしゃれなうでどけい　"
    .marubatsu "おしゃれなうでどけい　"
  ; .marubatsu "かわいいシール　"
    .marubatsu "かわいいシール　"
  ; .marubatsu "ハートのピアス　"
    .marubatsu "ハートのピアス　"
  ; .marubatsu "バラのはなたば　"
    .marubatsu "バラのはなたば　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "さいご　"
    .marubatsu "さいご　"
.orga (0x0D572E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ぶしつのロッカー　"
    .marubatsu "ぶしつのロッカー　"
  ; .marubatsu "たいいくかんばき　"
    .marubatsu "たいいくかんばき　"
  ; .marubatsu "スポーツかばん　"
    .marubatsu "スポーツかばん　"
  ; .marubatsu "うんどうようジャージ　"
    .marubatsu "うんどうようジャージ　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "さいご　"
    .marubatsu "さいご　"
  ; .marubatsu "おしゃれなうでどけい　"
    .marubatsu "おしゃれなうでどけい　"
  ; .marubatsu "かわいいシール　"
    .marubatsu "かわいいシール　"
  ; .marubatsu "ハートのピアス　"
    .marubatsu "ハートのピアス　"
  ; .marubatsu "バラのはなたば　"
    .marubatsu "バラのはなたば　"

.loadtable "marubatsu_tbl\marubatsu_chs_34.tbl"
.orga (0x0D583C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "サッカーぶ　"
    .marubatsu "サッカーぶ　"
  ; .marubatsu "やきゅうぶ　"
    .marubatsu "やきゅうぶ　"
  ; .marubatsu "すいえいぶ　"
    .marubatsu "すいえいぶ　"
  ; .marubatsu "けんどうぶ　"
    .marubatsu "けんどうぶ　"
  ; .marubatsu "１ばんすき　"
    .marubatsu "１ばんすき　"
  ; .marubatsu "２ばんめにすき　"
    .marubatsu "２ばんめにすき　"
  ; .marubatsu "３ばんめにすき　"
    .marubatsu "３ばんめにすき　"
  ; .marubatsu "４ばんめにすき　"
    .marubatsu "４ばんめにすき　"
.orga (0x0D58D8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こまつ　"
    .marubatsu "こまつ　"
  ; .marubatsu "おおの　"
    .marubatsu "おおの　"
  ; .marubatsu "おおたき　"
    .marubatsu "おおたき　"
  ; .marubatsu "まつした　"
    .marubatsu "まつした　"
  ; .marubatsu "１ばんすき　"
    .marubatsu "１ばんすき　"
  ; .marubatsu "２ばんめにすき　"
    .marubatsu "２ばんめにすき　"
  ; .marubatsu "３ばんめにすき　"
    .marubatsu "３ばんめにすき　"
  ; .marubatsu "４ばんめにすき　"
    .marubatsu "４ばんめにすき　"

.loadtable "marubatsu_tbl\marubatsu_chs_35.tbl"
.orga (0x0D59E6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かがわ　"
    .marubatsu "かがわ　"
  ; .marubatsu "やまぐち　"
    .marubatsu "やまぐち　"
  ; .marubatsu "みやぎ　"
    .marubatsu "みやぎ　"
  ; .marubatsu "ふくおか　"
    .marubatsu "ふくおか　"
  ; .marubatsu "ばらばらじけん　"
    .marubatsu "ばらばらじけん　"
  ; .marubatsu "じゅうさつ　"
    .marubatsu "じゅうさつ　"
  ; .marubatsu "こうさつ　"
    .marubatsu "こうさつ　"
  ; .marubatsu "みすい　"
    .marubatsu "みすい　"
  ; .marubatsu "ことし　"
    .marubatsu "ことし　"
  ; .marubatsu "１ねんまえ　"
    .marubatsu "１ねんまえ　"
  ; .marubatsu "３ねんまえ　"
    .marubatsu "３ねんまえ　"
  ; .marubatsu "４ねんまえ　"
    .marubatsu "４ねんまえ　"
.orga (0x0D5A82 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ちば　　"
    .marubatsu "ちば　　"
  ; .marubatsu "ふくしま　"
    .marubatsu "ふくしま　"
  ; .marubatsu "やまがた　"
    .marubatsu "やまがた　"
  ; .marubatsu "ながの　"
    .marubatsu "ながの　"
  ; .marubatsu "ことし　"
    .marubatsu "ことし　"
  ; .marubatsu "１ねんまえ　"
    .marubatsu "１ねんまえ　"
  ; .marubatsu "３ねんまえ　"
    .marubatsu "３ねんまえ　"
  ; .marubatsu "４ねんまえ　"
    .marubatsu "４ねんまえ　"
  ; .marubatsu "ばらばらじけん　"
    .marubatsu "ばらばらじけん　"
  ; .marubatsu "じゅうさつ　"
    .marubatsu "じゅうさつ　"
  ; .marubatsu "こうさつ　"
    .marubatsu "こうさつ　"
  ; .marubatsu "みすい　"
    .marubatsu "みすい　"

.loadtable "marubatsu_tbl\marubatsu_chs_36.tbl"
.orga (0x0D5B90 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しごとのはなし　"
    .marubatsu "しごとのはなし　"
  ; .marubatsu "れんあいのそうだん　"
    .marubatsu "れんあいのそうだん　"
  ; .marubatsu "そうおんのくじょう　"
    .marubatsu "そうおんのくじょう　"
  ; .marubatsu "おかねのはなし　"
    .marubatsu "おかねのはなし　"
  ; .marubatsu "ともだち　"
    .marubatsu "ともだち　"
  ; .marubatsu "となり　"
    .marubatsu "となり　"
  ; .marubatsu "こいびと　"
    .marubatsu "こいびと　"
  ; .marubatsu "あに　　"
    .marubatsu "あに　　"
  ; .marubatsu "６じ　　"
    .marubatsu "６じ　　"
  ; .marubatsu "７じ　　"
    .marubatsu "７じ　　"
  ; .marubatsu "８じ　　"
    .marubatsu "８じ　　"
  ; .marubatsu "９じ　　"
    .marubatsu "９じ　　"
.orga (0x0D5C2C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "やまだ　"
    .marubatsu "やまだ　"
  ; .marubatsu "かわはら　"
    .marubatsu "かわはら　"
  ; .marubatsu "たにぐち　"
    .marubatsu "たにぐち　"
  ; .marubatsu "もり　　"
    .marubatsu "もり　　"
  ; .marubatsu "６じ　　"
    .marubatsu "６じ　　"
  ; .marubatsu "７じ　　"
    .marubatsu "７じ　　"
  ; .marubatsu "８じ　　"
    .marubatsu "８じ　　"
  ; .marubatsu "９じ　　"
    .marubatsu "９じ　　"
  ; .marubatsu "ともだち　"
    .marubatsu "ともだち　"
  ; .marubatsu "となり　"
    .marubatsu "となり　"
  ; .marubatsu "こいびと　"
    .marubatsu "こいびと　"
  ; .marubatsu "あに　　"
    .marubatsu "あに　　"

.loadtable "marubatsu_tbl\marubatsu_chs_37.tbl"
.orga (0x0D5D3A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "げつようび　"
    .marubatsu "げつようび　"
  ; .marubatsu "かようび　"
    .marubatsu "かようび　"
  ; .marubatsu "もくようび　"
    .marubatsu "もくようび　"
  ; .marubatsu "きんようび　"
    .marubatsu "きんようび　"
  ; .marubatsu "スター　"
    .marubatsu "スター　"
  ; .marubatsu "マフイア　"
    .marubatsu "マフイア　"
  ; .marubatsu "だいふごう　"
    .marubatsu "だいふごう　"
  ; .marubatsu "はかせ　"
    .marubatsu "はかせ　"
  ; .marubatsu "まずまずのけっか　"
    .marubatsu "まずまずのけっか　"
  ; .marubatsu "２はつでしとめた　"
    .marubatsu "２はつでしとめた　"
  ; .marubatsu "かんぺきなしごと　"
    .marubatsu "かんぺきなしごと　"
  ; .marubatsu "にげられた　"
    .marubatsu "にげられた　"
.orga (0x0D5DD6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アメリカ　"
    .marubatsu "アメリカ　"
  ; .marubatsu "ブラジル　"
    .marubatsu "ブラジル　"
  ; .marubatsu "フランス　"
    .marubatsu "フランス　"
  ; .marubatsu "イギリス　"
    .marubatsu "イギリス　"
  ; .marubatsu "まずまずのけっか　"
    .marubatsu "まずまずのけっか　"
  ; .marubatsu "２はつでしとめた　"
    .marubatsu "２はつでしとめた　"
  ; .marubatsu "かんぺきなしごと　"
    .marubatsu "かんぺきなしごと　"
  ; .marubatsu "にげられた　"
    .marubatsu "にげられた　"
  ; .marubatsu "スター　"
    .marubatsu "スター　"
  ; .marubatsu "マフイア　"
    .marubatsu "マフイア　"
  ; .marubatsu "だいふごう　"
    .marubatsu "だいふごう　"
  ; .marubatsu "はかせ　"
    .marubatsu "はかせ　"

.loadtable "marubatsu_tbl\marubatsu_chs_38.tbl"
.orga (0x0D5EE4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ウルウル　"
    .marubatsu "ウルウル　"
  ; .marubatsu "ワクワク　"
    .marubatsu "ワクワク　"
  ; .marubatsu "ビクビク　"
    .marubatsu "ビクビク　"
  ; .marubatsu "ドキドキ　"
    .marubatsu "ドキドキ　"
  ; .marubatsu "１５０ページ　"
    .marubatsu "１５０ページ　"
  ; .marubatsu "１６０ページ　"
    .marubatsu "１６０ページ　"
  ; .marubatsu "１７０ページ　"
    .marubatsu "１７０ページ　"
  ; .marubatsu "１８０ページ　"
    .marubatsu "１８０ページ　"
  ; .marubatsu "たびだち　"
    .marubatsu "たびだち　"
  ; .marubatsu "つりきち　"
    .marubatsu "つりきち　"
  ; .marubatsu "うんめい　"
    .marubatsu "うんめい　"
  ; .marubatsu "ときめき　"
    .marubatsu "ときめき　"
.orga (0x0D5F80 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シエーヌ　"
    .marubatsu "シエーヌ　"
  ; .marubatsu "マリリン　"
    .marubatsu "マリリン　"
  ; .marubatsu "ヨッシー　"
    .marubatsu "ヨッシー　"
  ; .marubatsu "ケイト　"
    .marubatsu "ケイト　"
  ; .marubatsu "たびだち　"
    .marubatsu "たびだち　"
  ; .marubatsu "つりきち　"
    .marubatsu "つりきち　"
  ; .marubatsu "うんめい　"
    .marubatsu "うんめい　"
  ; .marubatsu "ときめき　"
    .marubatsu "ときめき　"
  ; .marubatsu "１５０ページ　"
    .marubatsu "１５０ページ　"
  ; .marubatsu "１６０ページ　"
    .marubatsu "１６０ページ　"
  ; .marubatsu "１７０ページ　"
    .marubatsu "１７０ページ　"
  ; .marubatsu "１８０ページ　"
    .marubatsu "１８０ページ　"

.loadtable "marubatsu_tbl\marubatsu_chs_39.tbl"
.orga (0x0D608E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ナイフでころした　"
    .marubatsu "ナイフでころした　"
  ; .marubatsu "カビンでころした　"
    .marubatsu "カビンでころした　"
  ; .marubatsu "ジュウでころした　"
    .marubatsu "ジュウでころした　"
  ; .marubatsu "ドクヤクでころした　"
    .marubatsu "ドクヤクでころした　"
  ; .marubatsu "５じにおこなった　"
    .marubatsu "５じにおこなった　"
  ; .marubatsu "６じにおこなった　"
    .marubatsu "６じにおこなった　"
  ; .marubatsu "７じにおこなった　"
    .marubatsu "７じにおこなった　"
  ; .marubatsu "８じにおこなった　"
    .marubatsu "８じにおこなった　"
  ; .marubatsu "ケイコをころした　"
    .marubatsu "ケイコをころした　"
  ; .marubatsu "カズミをころした　"
    .marubatsu "カズミをころした　"
  ; .marubatsu "ヨーコをころした　"
    .marubatsu "ヨーコをころした　"
  ; .marubatsu "ヒロコをころした　"
    .marubatsu "ヒロコをころした　"
.orga (0x0D612A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ケイコがころした　"
    .marubatsu "ケイコがころした　"
  ; .marubatsu "カズミがころした　"
    .marubatsu "カズミがころした　"
  ; .marubatsu "ヨーコがころした　"
    .marubatsu "ヨーコがころした　"
  ; .marubatsu "ヒロコがころした　"
    .marubatsu "ヒロコがころした　"
  ; .marubatsu "ケイコをころした　"
    .marubatsu "ケイコをころした　"
  ; .marubatsu "カズミをころした　"
    .marubatsu "カズミをころした　"
  ; .marubatsu "ヨーコをころした　"
    .marubatsu "ヨーコをころした　"
  ; .marubatsu "ヒロコをころした　"
    .marubatsu "ヒロコをころした　"
  ; .marubatsu "５じにおこなった　"
    .marubatsu "５じにおこなった　"
  ; .marubatsu "６じにおこなった　"
    .marubatsu "６じにおこなった　"
  ; .marubatsu "７じにおこなった　"
    .marubatsu "７じにおこなった　"
  ; .marubatsu "８じにおこなった　"
    .marubatsu "８じにおこなった　"

