.macro .marubatsu,str
    .area 13,0xAF
        .strn str
    .endarea
.endmacro

/* 每条文本须遵守以下规则：
   1.必须以全角空格，即“　”结尾。
   2.文本长度不超过13（含“　”）。
   3.文本长度至少为4（含“　”），否则用“　”填充。
*/

.loadtable "marubatsu_tbl\marubatsu_chs_00.tbl"
.orga (0x0D01B4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "せいふく　"
    .marubatsu "せいふく　"
  ; .marubatsu "あかいふく　"
    .marubatsu "あかいふく　"
  ; .marubatsu "あおいふく　"
    .marubatsu "あおいふく　"
  ; .marubatsu "きいろいふく　"
    .marubatsu "きいろいふく　"
  ; .marubatsu "３かまえ　"
    .marubatsu "３かまえ　"
  ; .marubatsu "４かまえ　"
    .marubatsu "４かまえ　"
  ; .marubatsu "５かまえ　"
    .marubatsu "５かまえ　"
  ; .marubatsu "６かまえ　"
    .marubatsu "６かまえ　"
.orga (0x0D0250 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シネマ　"
    .marubatsu "シネマ　"
  ; .marubatsu "トロピカルランド　"
    .marubatsu "トロピカルランド　"
  ; .marubatsu "こうえん　"
    .marubatsu "こうえん　"
  ; .marubatsu "きょうかい　"
    .marubatsu "きょうかい　"
  ; .marubatsu "３かまえ　"
    .marubatsu "３かまえ　"
  ; .marubatsu "４かまえ　"
    .marubatsu "４かまえ　"
  ; .marubatsu "５かまえ　"
    .marubatsu "５かまえ　"
  ; .marubatsu "６かまえ　"
    .marubatsu "６かまえ　"

.loadtable "marubatsu_tbl\marubatsu_chs_01.tbl"
.orga (0x0D035E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "けいこ　"
    .marubatsu "けいこ　"
  ; .marubatsu "おくさん　"
    .marubatsu "おくさん　"
  ; .marubatsu "ヒゲありのだんせい　"
    .marubatsu "ヒゲありのだんせい　"
  ; .marubatsu "ヒゲなしのだんせい　"
    .marubatsu "ヒゲなしのだんせい　"
  ; .marubatsu "１ごうしつ　"
    .marubatsu "１ごうしつ　"
  ; .marubatsu "２ごうしつ　"
    .marubatsu "２ごうしつ　"
  ; .marubatsu "３ごうしつ　"
    .marubatsu "３ごうしつ　"
  ; .marubatsu "４ごうしつ　"
    .marubatsu "４ごうしつ　"
.orga (0x0D03FA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ピエトロしんぷ　"
    .marubatsu "ピエトロしんぷ　"
  ; .marubatsu "トマスしんぷ　"
    .marubatsu "トマスしんぷ　"
  ; .marubatsu "ポールしんぷ　"
    .marubatsu "ポールしんぷ　"
  ; .marubatsu "ジョンしんぷ　"
    .marubatsu "ジョンしんぷ　"
  ; .marubatsu "１ごうしつ　"
    .marubatsu "１ごうしつ　"
  ; .marubatsu "２ごうしつ　"
    .marubatsu "２ごうしつ　"
  ; .marubatsu "３ごうしつ　"
    .marubatsu "３ごうしつ　"
  ; .marubatsu "４ごうしつ　"
    .marubatsu "４ごうしつ　"

.loadtable "marubatsu_tbl\marubatsu_chs_02.tbl"
.orga (0x0D0508 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
  ; .marubatsu "でんごんをかく　"
    .marubatsu "でんごんをかく　"
  ; .marubatsu "ほんをかえす　"
    .marubatsu "ほんをかえす　"
  ; .marubatsu "チケットをかう　"
    .marubatsu "チケットをかう　"
  ; .marubatsu "ケーキをかう　"
    .marubatsu "ケーキをかう　"
.orga (0x0D05A4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "としょかん　"
    .marubatsu "としょかん　"
  ; .marubatsu "べいかえき　"
    .marubatsu "べいかえき　"
  ; .marubatsu "カフエ　ロイヤル　"
    .marubatsu "カフエ　ロイヤル　"
  ; .marubatsu "トロピカルランド　"
    .marubatsu "トロピカルランド　"
  ; .marubatsu "でんごんをかく　"
    .marubatsu "でんごんをかく　"
  ; .marubatsu "ほんをかえす　"
    .marubatsu "ほんをかえす　"
  ; .marubatsu "チケットをかう　"
    .marubatsu "チケットをかう　"
  ; .marubatsu "ケーキをかう　"
    .marubatsu "ケーキをかう　"

.loadtable "marubatsu_tbl\marubatsu_chs_03.tbl"
.orga (0x0D06B2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "２２ばん　"
    .marubatsu "２２ばん　"
  ; .marubatsu "２６ばん　"
    .marubatsu "２６ばん　"
  ; .marubatsu "４３ばん　"
    .marubatsu "４３ばん　"
  ; .marubatsu "４７ばん　"
    .marubatsu "４７ばん　"
  ; .marubatsu "スペード　"
    .marubatsu "スペード　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "ダイヤ　"
  ; .marubatsu "ハート　"
    .marubatsu "ハート　"
  ; .marubatsu "クラブ　"
    .marubatsu "クラブ　"
.orga (0x0D074E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "らん　　"
    .marubatsu "らん　　"
  ; .marubatsu "けいこ　"
    .marubatsu "けいこ　"
  ; .marubatsu "ポールしんぷ　"
    .marubatsu "ポールしんぷ　"
  ; .marubatsu "りょうこ　"
    .marubatsu "りょうこ　"
  ; .marubatsu "スペード　"
    .marubatsu "スペード　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "ダイヤ　"
  ; .marubatsu "ハート　"
    .marubatsu "ハート　"
  ; .marubatsu "クラブ　"
    .marubatsu "クラブ　"

.loadtable "marubatsu_tbl\marubatsu_chs_04.tbl"
.orga (0x0D085C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヒロイン　"
    .marubatsu "ヒロイン　"
  ; .marubatsu "ライバル　"
    .marubatsu "ライバル　"
  ; .marubatsu "かれし　"
    .marubatsu "かれし　"
  ; .marubatsu "ようぎしゃ　"
    .marubatsu "ようぎしゃ　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "ぜんぶ　"
    .marubatsu "ぜんぶ　"
.orga (0x0D08F8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "ヨーコ　"
  ; .marubatsu "きょうこ　"
    .marubatsu "きょうこ　"
  ; .marubatsu "ようじ　"
    .marubatsu "ようじ　"
  ; .marubatsu "としき　"
    .marubatsu "としき　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "ぜんぶ　"
    .marubatsu "ぜんぶ　"

.loadtable "marubatsu_tbl\marubatsu_chs_05.tbl"
.orga (0x0D0A06 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "４じ３０にでた　"
    .marubatsu "４じ３０にでた　"
  ; .marubatsu "５じにでた　"
    .marubatsu "５じにでた　"
  ; .marubatsu "５じ３０にでた　"
    .marubatsu "５じ３０にでた　"
  ; .marubatsu "６じにでた　"
    .marubatsu "６じにでた　"
  ; .marubatsu "２じ３０にでた　"
    .marubatsu "２じ３０にでた　"
  ; .marubatsu "３じにでた　"
    .marubatsu "３じにでた　"
  ; .marubatsu "３じ３０にでた　"
    .marubatsu "３じ３０にでた　"
  ; .marubatsu "４じにでた　"
    .marubatsu "４じにでた　"
.orga (0x0D0AA2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "ヨーコ　"
  ; .marubatsu "ようじ　"
    .marubatsu "ようじ　"
  ; .marubatsu "としき　"
    .marubatsu "としき　"
  ; .marubatsu "カントク　"
    .marubatsu "カントク　"
  ; .marubatsu "２じ３０にでた　"
    .marubatsu "２じ３０にでた　"
  ; .marubatsu "３じにでた　"
    .marubatsu "３じにでた　"
  ; .marubatsu "３じ３０にでた　"
    .marubatsu "３じ３０にでた　"
  ; .marubatsu "４じにでた　"
    .marubatsu "４じにでた　"

.loadtable "marubatsu_tbl\marubatsu_chs_06.tbl"
.orga (0x0D0BB0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シネマ　"
    .marubatsu "シネマ　"
  ; .marubatsu "タワー　"
    .marubatsu "タワー　"
  ; .marubatsu "デパート　"
    .marubatsu "デパート　"
  ; .marubatsu "がっこう　"
    .marubatsu "がっこう　"
  ; .marubatsu "こどもばんぐみ　"
    .marubatsu "こどもばんぐみ　"
  ; .marubatsu "グルメばんぐみ　"
    .marubatsu "グルメばんぐみ　"
  ; .marubatsu "しゅざい　"
    .marubatsu "しゅざい　"
  ; .marubatsu "あいさつ　"
    .marubatsu "あいさつ　"
.orga (0x0D0C4C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "ヨーコ　"
  ; .marubatsu "ようじ　"
    .marubatsu "ようじ　"
  ; .marubatsu "としき　"
    .marubatsu "としき　"
  ; .marubatsu "カントク　"
    .marubatsu "カントク　"
  ; .marubatsu "こどもばんぐみ　"
    .marubatsu "こどもばんぐみ　"
  ; .marubatsu "グルメばんぐみ　"
    .marubatsu "グルメばんぐみ　"
  ; .marubatsu "しゅざい　"
    .marubatsu "しゅざい　"
  ; .marubatsu "あいさつ　"
    .marubatsu "あいさつ　"

.loadtable "marubatsu_tbl\marubatsu_chs_07.tbl"
.orga (0x0D0D5A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ねんまえ　"
    .marubatsu "１ねんまえ　"
  ; .marubatsu "２ねんまえ　"
    .marubatsu "２ねんまえ　"
  ; .marubatsu "３ねんまえ　"
    .marubatsu "３ねんまえ　"
  ; .marubatsu "４ねんまえ　"
    .marubatsu "４ねんまえ　"
  ; .marubatsu "しごとをとられた　"
    .marubatsu "しごとをとられた　"
  ; .marubatsu "おかねをとられた　"
    .marubatsu "おかねをとられた　"
  ; .marubatsu "こいびとがじさつ　"
    .marubatsu "こいびとがじさつ　"
  ; .marubatsu "きょうこにふられた　"
    .marubatsu "きょうこにふられた　"
.orga (0x0D0DF6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "ヨーコ　"
  ; .marubatsu "ようじ　"
    .marubatsu "ようじ　"
  ; .marubatsu "としき　"
    .marubatsu "としき　"
  ; .marubatsu "カントク　"
    .marubatsu "カントク　"
  ; .marubatsu "しごとをとられた　"
    .marubatsu "しごとをとられた　"
  ; .marubatsu "おかねをとられた　"
    .marubatsu "おかねをとられた　"
  ; .marubatsu "こいびとがじさつ　"
    .marubatsu "こいびとがじさつ　"
  ; .marubatsu "きょうこにふられた　"
    .marubatsu "きょうこにふられた　"

.loadtable "marubatsu_tbl\marubatsu_chs_08.tbl"
.orga (0x0D0F04 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "むじのカサ　"
    .marubatsu "むじのカサ　"
  ; .marubatsu "みずたまのカサ　"
    .marubatsu "みずたまのカサ　"
  ; .marubatsu "チエックのカサ　"
    .marubatsu "チエックのカサ　"
  ; .marubatsu "たてじまのカサ　"
    .marubatsu "たてじまのカサ　"
  ; .marubatsu "ビニールぶくろ　"
    .marubatsu "ビニールぶくろ　"
  ; .marubatsu "カメラ　"
    .marubatsu "カメラ　"
  ; .marubatsu "アイスボックス　"
    .marubatsu "アイスボックス　"
  ; .marubatsu "リュック　"
    .marubatsu "リュック　"
.orga (0x0D0FA0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "ヨーコ　"
  ; .marubatsu "ようじ　"
    .marubatsu "ようじ　"
  ; .marubatsu "としき　"
    .marubatsu "としき　"
  ; .marubatsu "カントク　"
    .marubatsu "カントク　"
  ; .marubatsu "ビニールぶくろ　"
    .marubatsu "ビニールぶくろ　"
  ; .marubatsu "カメラ　"
    .marubatsu "カメラ　"
  ; .marubatsu "アイスボックス　"
    .marubatsu "アイスボックス　"
  ; .marubatsu "リュック　"
    .marubatsu "リュック　"

.loadtable "marubatsu_tbl\marubatsu_chs_09.tbl"
.orga (0x0D10AE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アメリカしゃ　"
    .marubatsu "アメリカしゃ　"
  ; .marubatsu "ニホンしゃ　"
    .marubatsu "ニホンしゃ　"
  ; .marubatsu "ドイツしゃ　"
    .marubatsu "ドイツしゃ　"
  ; .marubatsu "イギリスしゃ　"
    .marubatsu "イギリスしゃ　"
  ; .marubatsu "タワー　"
    .marubatsu "タワー　"
  ; .marubatsu "デパート　"
    .marubatsu "デパート　"
  ; .marubatsu "こうえん　"
    .marubatsu "こうえん　"
  ; .marubatsu "シネマ　"
    .marubatsu "シネマ　"
  ; .marubatsu "ナイフ　"
    .marubatsu "ナイフ　"
  ; .marubatsu "きり　　"
    .marubatsu "きり　　"
  ; .marubatsu "なぞ　　"
    .marubatsu "なぞ　　"
  ; .marubatsu "よる　　"
    .marubatsu "よる　　"
.orga (0x0D114A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しんいち　"
    .marubatsu "しんいち　"
  ; .marubatsu "へいじ　"
    .marubatsu "へいじ　"
  ; .marubatsu "こごろう　"
    .marubatsu "こごろう　"
  ; .marubatsu "ジャック　"
    .marubatsu "ジャック　"
  ; .marubatsu "ナイフ　"
    .marubatsu "ナイフ　"
  ; .marubatsu "きり　　"
    .marubatsu "きり　　"
  ; .marubatsu "なぞ　　"
    .marubatsu "なぞ　　"
  ; .marubatsu "よる　　"
    .marubatsu "よる　　"
  ; .marubatsu "タワー　"
    .marubatsu "タワー　"
  ; .marubatsu "デパート　"
    .marubatsu "デパート　"
  ; .marubatsu "こうえん　"
    .marubatsu "こうえん　"
  ; .marubatsu "シネマ　"
    .marubatsu "シネマ　"

.loadtable "marubatsu_tbl\marubatsu_chs_0A.tbl"
.orga (0x0D1258 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "せんさいのつれご　"
    .marubatsu "せんさいのつれご　"
  ; .marubatsu "ごさいのつれご　"
    .marubatsu "ごさいのつれご　"
  ; .marubatsu "せんさいのじっし　"
    .marubatsu "せんさいのじっし　"
  ; .marubatsu "ごさいのじっし　"
    .marubatsu "ごさいのじっし　"
  ; .marubatsu "いしゃ　"
    .marubatsu "いしゃ　"
  ; .marubatsu "じょせい　"
    .marubatsu "じょせい　"
  ; .marubatsu "きぞく　"
    .marubatsu "きぞく　"
  ; .marubatsu "けいかん　"
    .marubatsu "けいかん　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "すえっこ　"
    .marubatsu "すえっこ　"
.orga (0x0D12F4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しゃく　"
    .marubatsu "しゃく　"
  ; .marubatsu "りん　　"
    .marubatsu "りん　　"
  ; .marubatsu "とし　　"
    .marubatsu "とし　　"
  ; .marubatsu "あつし　"
    .marubatsu "あつし　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "すえっこ　"
    .marubatsu "すえっこ　"
  ; .marubatsu "いしゃ　"
    .marubatsu "いしゃ　"
  ; .marubatsu "じょせい　"
    .marubatsu "じょせい　"
  ; .marubatsu "きぞく　"
    .marubatsu "きぞく　"
  ; .marubatsu "けいかん　"
    .marubatsu "けいかん　"

.loadtable "marubatsu_tbl\marubatsu_chs_0B.tbl"
.orga (0x0D1402 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "やしき　"
    .marubatsu "やしき　"
  ; .marubatsu "べってい　"
    .marubatsu "べってい　"
  ; .marubatsu "かぶけん　"
    .marubatsu "かぶけん　"
  ; .marubatsu "コレクション　"
    .marubatsu "コレクション　"
  ; .marubatsu "２０おくえん　"
    .marubatsu "２０おくえん　"
  ; .marubatsu "１５おくえん　"
    .marubatsu "１５おくえん　"
  ; .marubatsu "１３おくえん　"
    .marubatsu "１３おくえん　"
  ; .marubatsu "１２おくえん　"
    .marubatsu "１２おくえん　"
.orga (0x0D149E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しゃく　"
    .marubatsu "しゃく　"
  ; .marubatsu "りん　　"
    .marubatsu "りん　　"
  ; .marubatsu "とし　　"
    .marubatsu "とし　　"
  ; .marubatsu "あつし　"
    .marubatsu "あつし　"
  ; .marubatsu "２０おくえん　"
    .marubatsu "２０おくえん　"
  ; .marubatsu "１５おくえん　"
    .marubatsu "１５おくえん　"
  ; .marubatsu "１３おくえん　"
    .marubatsu "１３おくえん　"
  ; .marubatsu "１２おくえん　"
    .marubatsu "１２おくえん　"

.loadtable "marubatsu_tbl\marubatsu_chs_0C.tbl"
.orga (0x0D15AC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アーミーナイフ　"
    .marubatsu "アーミーナイフ　"
  ; .marubatsu "くだものナイフ　"
    .marubatsu "くだものナイフ　"
  ; .marubatsu "ちょうこくとう　"
    .marubatsu "ちょうこくとう　"
  ; .marubatsu "もてない　"
    .marubatsu "もてない　"
  ; .marubatsu "あえない　"
    .marubatsu "あえない　"
  ; .marubatsu "どなられた　"
    .marubatsu "どなられた　"
  ; .marubatsu "わらった　"
    .marubatsu "わらった　"
  ; .marubatsu "コーヒーをとりに　"
    .marubatsu "コーヒーをとりに　"
  ; .marubatsu "１じ　　"
    .marubatsu "１じ　　"
  ; .marubatsu "２じ　　"
    .marubatsu "２じ　　"
  ; .marubatsu "３じ　　"
    .marubatsu "３じ　　"
  ; .marubatsu "４じ　　"
    .marubatsu "４じ　　"
.orga (0x0D1648 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しゃく　"
    .marubatsu "しゃく　"
  ; .marubatsu "りん　　"
    .marubatsu "りん　　"
  ; .marubatsu "とし　　"
    .marubatsu "とし　　"
  ; .marubatsu "あつし　"
    .marubatsu "あつし　"
  ; .marubatsu "１じ　　"
    .marubatsu "１じ　　"
  ; .marubatsu "２じ　　"
    .marubatsu "２じ　　"
  ; .marubatsu "３じ　　"
    .marubatsu "３じ　　"
  ; .marubatsu "４じ　　"
    .marubatsu "４じ　　"
  ; .marubatsu "あえない　"
    .marubatsu "あえない　"
  ; .marubatsu "どなられた　"
    .marubatsu "どなられた　"
  ; .marubatsu "わらった　"
    .marubatsu "わらった　"
  ; .marubatsu "コーヒーをとりに　"
    .marubatsu "コーヒーをとりに　"

.loadtable "marubatsu_tbl\marubatsu_chs_0D.tbl"
.orga (0x0D1756 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "３かまえ　"
    .marubatsu "３かまえ　"
  ; .marubatsu "おととい　"
    .marubatsu "おととい　"
  ; .marubatsu "ゆうべ　"
    .marubatsu "ゆうべ　"
  ; .marubatsu "こんや　"
    .marubatsu "こんや　"
  ; .marubatsu "はくぶつかん　"
    .marubatsu "はくぶつかん　"
  ; .marubatsu "びじゅつかん　"
    .marubatsu "びじゅつかん　"
  ; .marubatsu "タワー　"
    .marubatsu "タワー　"
  ; .marubatsu "きょうかい　"
    .marubatsu "きょうかい　"
.orga (0x0D17F2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "サフアイヤ　"
    .marubatsu "サフアイヤ　"
  ; .marubatsu "エメラルド　"
    .marubatsu "エメラルド　"
  ; .marubatsu "オパール　"
    .marubatsu "オパール　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "ダイヤ　"
  ; .marubatsu "はくぶつかん　"
    .marubatsu "はくぶつかん　"
  ; .marubatsu "びじゅつかん　"
    .marubatsu "びじゅつかん　"
  ; .marubatsu "タワー　"
    .marubatsu "タワー　"
  ; .marubatsu "きょうかい　"
    .marubatsu "きょうかい　"

.loadtable "marubatsu_tbl\marubatsu_chs_0E.tbl"
.orga (0x0D1900 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "だい１てんじしつ　"
    .marubatsu "だい１てんじしつ　"
  ; .marubatsu "だい２てんじしつ　"
    .marubatsu "だい２てんじしつ　"
  ; .marubatsu "だい３てんじしつ　"
    .marubatsu "だい３てんじしつ　"
  ; .marubatsu "だい４てんじしつ　"
    .marubatsu "だい４てんじしつ　"
  ; .marubatsu "かいが　"
    .marubatsu "かいが　"
  ; .marubatsu "ちょうこく　"
    .marubatsu "ちょうこく　"
  ; .marubatsu "げんだいアート　"
    .marubatsu "げんだいアート　"
  ; .marubatsu "ほうしょくひん　"
    .marubatsu "ほうしょくひん　"
  ; .marubatsu "いりぐちにちかい　"
    .marubatsu "いりぐちにちかい　"
  ; .marubatsu "でぐちひとつ　"
    .marubatsu "でぐちひとつ　"
  ; .marubatsu "とびら３つ　"
    .marubatsu "とびら３つ　"
  ; .marubatsu "ひじょうぐちあり　"
    .marubatsu "ひじょうぐちあり　"
.orga (0x0D199C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こごろう　"
    .marubatsu "こごろう　"
  ; .marubatsu "めぐれ　"
    .marubatsu "めぐれ　"
  ; .marubatsu "なかもり　"
    .marubatsu "なかもり　"
  ; .marubatsu "しらとり　"
    .marubatsu "しらとり　"
  ; .marubatsu "いりぐちにちかい　"
    .marubatsu "いりぐちにちかい　"
  ; .marubatsu "でぐちひとつ　"
    .marubatsu "でぐちひとつ　"
  ; .marubatsu "とびら３つ　"
    .marubatsu "とびら３つ　"
  ; .marubatsu "ひじょうぐちあり　"
    .marubatsu "ひじょうぐちあり　"
  ; .marubatsu "かいが　"
    .marubatsu "かいが　"
  ; .marubatsu "ちょうこく　"
    .marubatsu "ちょうこく　"
  ; .marubatsu "げんだいアート　"
    .marubatsu "げんだいアート　"
  ; .marubatsu "ほうしょくひん　"
    .marubatsu "ほうしょくひん　"

.loadtable "marubatsu_tbl\marubatsu_chs_0F.tbl"
.orga (0x0D1AAA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "６じ００にでた　"
    .marubatsu "６じ００にでた　"
  ; .marubatsu "６じ０５にでた　"
    .marubatsu "６じ０５にでた　"
  ; .marubatsu "６じ１０にでた　"
    .marubatsu "６じ１０にでた　"
  ; .marubatsu "６じ１５にでた　"
    .marubatsu "６じ１５にでた　"
  ; .marubatsu "５じ４５にはいった　"
    .marubatsu "５じ４５にはいった　"
  ; .marubatsu "５じ５５にはいった　"
    .marubatsu "５じ５５にはいった　"
  ; .marubatsu "６じ０５にはいった　"
    .marubatsu "６じ０５にはいった　"
  ; .marubatsu "６じ１０にはいった　"
    .marubatsu "６じ１０にはいった　"
.orga (0x0D1B46 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こごろう　"
    .marubatsu "こごろう　"
  ; .marubatsu "めぐれ　"
    .marubatsu "めぐれ　"
  ; .marubatsu "なかもり　"
    .marubatsu "なかもり　"
  ; .marubatsu "おおくぼ　"
    .marubatsu "おおくぼ　"
  ; .marubatsu "５じ４５にはいった　"
    .marubatsu "５じ４５にはいった　"
  ; .marubatsu "５じ５５にはいった　"
    .marubatsu "５じ５５にはいった　"
  ; .marubatsu "６じ０５にはいった　"
    .marubatsu "６じ０５にはいった　"
  ; .marubatsu "６じ１０にはいった　"
    .marubatsu "６じ１０にはいった　"

.loadtable "marubatsu_tbl\marubatsu_chs_10.tbl"
.orga (0x0D1C54 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あか　　"
    .marubatsu "あか　　"
  ; .marubatsu "あお　　"
    .marubatsu "あお　　"
  ; .marubatsu "きいろ　"
    .marubatsu "きいろ　"
  ; .marubatsu "むしょく　"
    .marubatsu "むしょく　"
  ; .marubatsu "みぎ　　"
    .marubatsu "みぎ　　"
  ; .marubatsu "ひだり　"
    .marubatsu "ひだり　"
  ; .marubatsu "おく　　"
    .marubatsu "おく　　"
  ; .marubatsu "ちゅうおう　"
    .marubatsu "ちゅうおう　"
.orga (0x0D1CF0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かわいいあおバラ　"
    .marubatsu "かわいいあおバラ　"
  ; .marubatsu "あくまのなみだ　"
    .marubatsu "あくまのなみだ　"
  ; .marubatsu "ソロモンのカギ　"
    .marubatsu "ソロモンのカギ　"
  ; .marubatsu "ヴイーナスのひとみ　"
    .marubatsu "ヴイーナスのひとみ　"
  ; .marubatsu "みぎ　　"
    .marubatsu "みぎ　　"
  ; .marubatsu "ひだり　"
    .marubatsu "ひだり　"
  ; .marubatsu "おく　　"
    .marubatsu "おく　　"
  ; .marubatsu "ちゅうおう　"
    .marubatsu "ちゅうおう　"

.loadtable "marubatsu_tbl\marubatsu_chs_11.tbl"
.orga (0x0D1DFE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１もじめ　"
    .marubatsu "１もじめ　"
  ; .marubatsu "２もじめ　"
    .marubatsu "２もじめ　"
  ; .marubatsu "３もじめ　"
    .marubatsu "３もじめ　"
  ; .marubatsu "４もじめ　"
    .marubatsu "４もじめ　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
.orga (0x0D1E9A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かわいいあおバラ　"
    .marubatsu "かわいいあおバラ　"
  ; .marubatsu "あくまのなみだ　"
    .marubatsu "あくまのなみだ　"
  ; .marubatsu "ソロモンのカギ　"
    .marubatsu "ソロモンのカギ　"
  ; .marubatsu "ヴイーナスのひとみ　"
    .marubatsu "ヴイーナスのひとみ　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_12.tbl"
.orga (0x0D1FA8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ベンチのした　"
    .marubatsu "ベンチのした　"
  ; .marubatsu "ごみばこのちかく　"
    .marubatsu "ごみばこのちかく　"
  ; .marubatsu "みずのみば　"
    .marubatsu "みずのみば　"
  ; .marubatsu "きのした　"
    .marubatsu "きのした　"
  ; .marubatsu "あか　　"
    .marubatsu "あか　　"
  ; .marubatsu "あお　　"
    .marubatsu "あお　　"
  ; .marubatsu "きいろ　"
    .marubatsu "きいろ　"
  ; .marubatsu "みどり　"
    .marubatsu "みどり　"
.orga (0x0D2044 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あゆみ　"
    .marubatsu "あゆみ　"
  ; .marubatsu "げんた　"
    .marubatsu "げんた　"
  ; .marubatsu "みつひこ　"
    .marubatsu "みつひこ　"
  ; .marubatsu "コナン　"
    .marubatsu "コナン　"
  ; .marubatsu "あか　　"
    .marubatsu "あか　　"
  ; .marubatsu "あお　　"
    .marubatsu "あお　　"
  ; .marubatsu "きいろ　"
    .marubatsu "きいろ　"
  ; .marubatsu "みどり　"
    .marubatsu "みどり　"

.loadtable "marubatsu_tbl\marubatsu_chs_13.tbl"
.orga (0x0D2152 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "マリブのかいぞく　"
    .marubatsu "マリブのかいぞく　"
  ; .marubatsu "カップ　"
    .marubatsu "カップ　"
  ; .marubatsu "コースター　"
    .marubatsu "コースター　"
  ; .marubatsu "かんらんしゃ　"
    .marubatsu "かんらんしゃ　"
  ; .marubatsu "くちのなか　"
    .marubatsu "くちのなか　"
  ; .marubatsu "さらのした　"
    .marubatsu "さらのした　"
  ; .marubatsu "ランタンのした　"
    .marubatsu "ランタンのした　"
  ; .marubatsu "けんばいきのよこ　"
    .marubatsu "けんばいきのよこ　"
.orga (0x0D21EE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルビー　"
    .marubatsu "ルビー　"
  ; .marubatsu "サフアイヤ　"
    .marubatsu "サフアイヤ　"
  ; .marubatsu "エメラルド　"
    .marubatsu "エメラルド　"
  ; .marubatsu "アメジスト　"
    .marubatsu "アメジスト　"
  ; .marubatsu "くちのなか　"
    .marubatsu "くちのなか　"
  ; .marubatsu "さらのした　"
    .marubatsu "さらのした　"
  ; .marubatsu "ランタンのした　"
    .marubatsu "ランタンのした　"
  ; .marubatsu "けんばいきのよこ　"
    .marubatsu "けんばいきのよこ　"

.loadtable "marubatsu_tbl\marubatsu_chs_14.tbl"
.orga (0x0D22FC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スペード　"
    .marubatsu "スペード　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "ダイヤ　"
  ; .marubatsu "ハート　"
    .marubatsu "ハート　"
  ; .marubatsu "クラブ　"
    .marubatsu "クラブ　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
  ; .marubatsu "みぎ　　"
    .marubatsu "みぎ　　"
  ; .marubatsu "ひだり　"
    .marubatsu "ひだり　"
  ; .marubatsu "うえ　　"
    .marubatsu "うえ　　"
  ; .marubatsu "した　　"
    .marubatsu "した　　"
.orga (0x0D2398 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルビー　"
    .marubatsu "ルビー　"
  ; .marubatsu "サフアイヤ　"
    .marubatsu "サフアイヤ　"
  ; .marubatsu "エメラルド　"
    .marubatsu "エメラルド　"
  ; .marubatsu "アメジスト　"
    .marubatsu "アメジスト　"
  ; .marubatsu "みぎ　　"
    .marubatsu "みぎ　　"
  ; .marubatsu "ひだり　"
    .marubatsu "ひだり　"
  ; .marubatsu "うえ　　"
    .marubatsu "うえ　　"
  ; .marubatsu "した　　"
    .marubatsu "した　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_15.tbl"
.orga (0x0D24A6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "おす　　"
    .marubatsu "おす　　"
  ; .marubatsu "ひく　　"
    .marubatsu "ひく　　"
  ; .marubatsu "はずす　"
    .marubatsu "はずす　"
  ; .marubatsu "さかさま　"
    .marubatsu "さかさま　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
.orga (0x0D2542 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ジイ　　"
    .marubatsu "ジイ　　"
  ; .marubatsu "アイ　　"
    .marubatsu "アイ　　"
  ; .marubatsu "エムエー　"
    .marubatsu "エムエー　"
  ; .marubatsu "シー　　"
    .marubatsu "シー　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_16.tbl"
.orga (0x0D2650 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルビー　"
    .marubatsu "ルビー　"
  ; .marubatsu "サフアイヤ　"
    .marubatsu "サフアイヤ　"
  ; .marubatsu "エメラルド　"
    .marubatsu "エメラルド　"
  ; .marubatsu "アメジスト　"
    .marubatsu "アメジスト　"
  ; .marubatsu "よこ１　"
    .marubatsu "よこ１　"
  ; .marubatsu "よこ２　"
    .marubatsu "よこ２　"
  ; .marubatsu "よこ３　"
    .marubatsu "よこ３　"
  ; .marubatsu "よこ４　"
    .marubatsu "よこ４　"
  ; .marubatsu "たに１　"
    .marubatsu "たに１　"
  ; .marubatsu "たに２　"
    .marubatsu "たに２　"
  ; .marubatsu "たに３　"
    .marubatsu "たに３　"
  ; .marubatsu "たに４　"
    .marubatsu "たに４　"
.orga (0x0D26EC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スペード　"
    .marubatsu "スペード　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "ダイヤ　"
  ; .marubatsu "ハート　"
    .marubatsu "ハート　"
  ; .marubatsu "クラブ　"
    .marubatsu "クラブ　"
  ; .marubatsu "たに１　"
    .marubatsu "たに１　"
  ; .marubatsu "たに２　"
    .marubatsu "たに２　"
  ; .marubatsu "たに３　"
    .marubatsu "たに３　"
  ; .marubatsu "たに４　"
    .marubatsu "たに４　"
  ; .marubatsu "よこ１　"
    .marubatsu "よこ１　"
  ; .marubatsu "よこ２　"
    .marubatsu "よこ２　"
  ; .marubatsu "よこ３　"
    .marubatsu "よこ３　"
  ; .marubatsu "よこ４　"
    .marubatsu "よこ４　"

.loadtable "marubatsu_tbl\marubatsu_chs_17.tbl"
.orga (0x0D27FA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スペード　"
    .marubatsu "スペード　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "ダイヤ　"
  ; .marubatsu "ハート　"
    .marubatsu "ハート　"
  ; .marubatsu "クラブ　"
    .marubatsu "クラブ　"
  ; .marubatsu "１かいめ　"
    .marubatsu "１かいめ　"
  ; .marubatsu "２かいめ　"
    .marubatsu "２かいめ　"
  ; .marubatsu "３かいめ　"
    .marubatsu "３かいめ　"
  ; .marubatsu "４かいめ　"
    .marubatsu "４かいめ　"
  ; .marubatsu "あとシー　"
    .marubatsu "あとシー　"
  ; .marubatsu "あとアイ　"
    .marubatsu "あとアイ　"
  ; .marubatsu "あとエイ　"
    .marubatsu "あとエイ　"
  ; .marubatsu "あとエヌ　"
    .marubatsu "あとエヌ　"
.orga (0x0D2896 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "まえエム　"
    .marubatsu "まえエム　"
  ; .marubatsu "まえエイ　"
    .marubatsu "まえエイ　"
  ; .marubatsu "まえジー　"
    .marubatsu "まえジー　"
  ; .marubatsu "まえアイ　"
    .marubatsu "まえアイ　"
  ; .marubatsu "あとシー　"
    .marubatsu "あとシー　"
  ; .marubatsu "あとアイ　"
    .marubatsu "あとアイ　"
  ; .marubatsu "あとエイ　"
    .marubatsu "あとエイ　"
  ; .marubatsu "あとエヌ　"
    .marubatsu "あとエヌ　"
  ; .marubatsu "１かいめ　"
    .marubatsu "１かいめ　"
  ; .marubatsu "２かいめ　"
    .marubatsu "２かいめ　"
  ; .marubatsu "３かいめ　"
    .marubatsu "３かいめ　"
  ; .marubatsu "４かいめ　"
    .marubatsu "４かいめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_18.tbl"
.orga (0x0D29A4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "みぎ　　"
    .marubatsu "みぎ　　"
  ; .marubatsu "ひだり　"
    .marubatsu "ひだり　"
  ; .marubatsu "うえ　　"
    .marubatsu "うえ　　"
  ; .marubatsu "した　　"
    .marubatsu "した　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
.orga (0x0D2A40 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "２　　　"
    .marubatsu "２　　　"
  ; .marubatsu "０　　　"
    .marubatsu "０　　　"
  ; .marubatsu "せい　　"
    .marubatsu "せい　　"
  ; .marubatsu "き　　　"
    .marubatsu "き　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_19.tbl"
.orga (0x0D2B4E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "みどり　"
    .marubatsu "みどり　"
  ; .marubatsu "ウラシマ　"
    .marubatsu "ウラシマ　"
  ; .marubatsu "ウサギ　"
    .marubatsu "ウサギ　"
  ; .marubatsu "ロケット　"
    .marubatsu "ロケット　"
  ; .marubatsu "げんた　"
    .marubatsu "げんた　"
  ; .marubatsu "あゆみ　"
    .marubatsu "あゆみ　"
  ; .marubatsu "コナン　"
    .marubatsu "コナン　"
  ; .marubatsu "みつひこ　"
    .marubatsu "みつひこ　"
.orga (0x0D2BEA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "コイ　　"
    .marubatsu "コイ　　"
  ; .marubatsu "カメ　　"
    .marubatsu "カメ　　"
  ; .marubatsu "うさぎ　"
    .marubatsu "うさぎ　"
  ; .marubatsu "ハト　　"
    .marubatsu "ハト　　"
  ; .marubatsu "げんた　"
    .marubatsu "げんた　"
  ; .marubatsu "あゆみ　"
    .marubatsu "あゆみ　"
  ; .marubatsu "コナン　"
    .marubatsu "コナン　"
  ; .marubatsu "みつひこ　"
    .marubatsu "みつひこ　"

.loadtable "marubatsu_tbl\marubatsu_chs_1A.tbl"
.orga (0x0D2CF8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
  ; .marubatsu "じむしょ　"
    .marubatsu "じむしょ　"
  ; .marubatsu "デパート　"
    .marubatsu "デパート　"
  ; .marubatsu "けいさつ　"
    .marubatsu "けいさつ　"
  ; .marubatsu "タワー　"
    .marubatsu "タワー　"
.orga (0x0D2D94 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シロ　　"
    .marubatsu "シロ　　"
  ; .marubatsu "クロ　　"
    .marubatsu "クロ　　"
  ; .marubatsu "トラ　　"
    .marubatsu "トラ　　"
  ; .marubatsu "ミケ　　"
    .marubatsu "ミケ　　"
  ; .marubatsu "じむしょ　"
    .marubatsu "じむしょ　"
  ; .marubatsu "デパート　"
    .marubatsu "デパート　"
  ; .marubatsu "けいさつ　"
    .marubatsu "けいさつ　"
  ; .marubatsu "タワー　"
    .marubatsu "タワー　"

.loadtable "marubatsu_tbl\marubatsu_chs_1B.tbl"
.orga (0x0D2EA2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "がくしゃ　"
    .marubatsu "がくしゃ　"
  ; .marubatsu "しょき　"
    .marubatsu "しょき　"
  ; .marubatsu "バイヤー　"
    .marubatsu "バイヤー　"
  ; .marubatsu "えいぞう　"
    .marubatsu "えいぞう　"
  ; .marubatsu "シングル　"
    .marubatsu "シングル　"
  ; .marubatsu "ダブル　"
    .marubatsu "ダブル　"
  ; .marubatsu "タイなし　"
    .marubatsu "タイなし　"
  ; .marubatsu "チャイナ　"
    .marubatsu "チャイナ　"
  ; .marubatsu "かいつけ　"
    .marubatsu "かいつけ　"
  ; .marubatsu "さつえい　"
    .marubatsu "さつえい　"
  ; .marubatsu "きぞう　"
    .marubatsu "きぞう　"
  ; .marubatsu "きょうみ　"
    .marubatsu "きょうみ　"
.orga (0x0D2F3E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "いぬい　"
    .marubatsu "いぬい　"
  ; .marubatsu "セルゲイ　"
    .marubatsu "セルゲイ　"
  ; .marubatsu "さがわ　"
    .marubatsu "さがわ　"
  ; .marubatsu "せいらん　"
    .marubatsu "せいらん　"
  ; .marubatsu "かいつけ　"
    .marubatsu "かいつけ　"
  ; .marubatsu "さつえい　"
    .marubatsu "さつえい　"
  ; .marubatsu "きぞう　"
    .marubatsu "きぞう　"
  ; .marubatsu "きょうみ　"
    .marubatsu "きょうみ　"
  ; .marubatsu "シングル　"
    .marubatsu "シングル　"
  ; .marubatsu "ダブル　"
    .marubatsu "ダブル　"
  ; .marubatsu "タイなし　"
    .marubatsu "タイなし　"
  ; .marubatsu "チャイナ　"
    .marubatsu "チャイナ　"

.loadtable "marubatsu_tbl\marubatsu_chs_1C.tbl"
.orga (0x0D304C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スミスアンドウエッソン　"
    .marubatsu "スミスアンドウエッソン　"
  ; .marubatsu "エム８９ビー　"
    .marubatsu "エム８９ビー　"
  ; .marubatsu "ワルサーピー３８　"
    .marubatsu "ワルサーピー３８　"
  ; .marubatsu "アダムス　"
    .marubatsu "アダムス　"
  ; .marubatsu "イギリスせい　"
    .marubatsu "イギリスせい　"
  ; .marubatsu "イタリアせい　"
    .marubatsu "イタリアせい　"
  ; .marubatsu "ドイツせい　"
    .marubatsu "ドイツせい　"
  ; .marubatsu "アメリカせい　"
    .marubatsu "アメリカせい　"
.orga (0x0D30E8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "もちづき　"
    .marubatsu "もちづき　"
  ; .marubatsu "こうの　"
    .marubatsu "こうの　"
  ; .marubatsu "はぎわら　"
    .marubatsu "はぎわら　"
  ; .marubatsu "いしざき　"
    .marubatsu "いしざき　"
  ; .marubatsu "イギリスせい　"
    .marubatsu "イギリスせい　"
  ; .marubatsu "イタリアせい　"
    .marubatsu "イタリアせい　"
  ; .marubatsu "ドイツせい　"
    .marubatsu "ドイツせい　"
  ; .marubatsu "アメリカせい　"
    .marubatsu "アメリカせい　"

.loadtable "marubatsu_tbl\marubatsu_chs_1D.tbl"
.orga (0x0D31F6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "コインロッカー　"
    .marubatsu "コインロッカー　"
  ; .marubatsu "かしきんこ　"
    .marubatsu "かしきんこ　"
  ; .marubatsu "そうこ　"
    .marubatsu "そうこ　"
  ; .marubatsu "じたく　"
    .marubatsu "じたく　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
.orga (0x0D3292 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ダイヤモンド　"
    .marubatsu "ダイヤモンド　"
  ; .marubatsu "サフアイア　"
    .marubatsu "サフアイア　"
  ; .marubatsu "エメラルド　"
    .marubatsu "エメラルド　"
  ; .marubatsu "ルビー　"
    .marubatsu "ルビー　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_1E.tbl"
.orga (0x0D33A0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ようじんあんさつ　"
    .marubatsu "ようじんあんさつ　"
  ; .marubatsu "じょせいさつがい　"
    .marubatsu "じょせいさつがい　"
  ; .marubatsu "けいさつかんさつがい　"
    .marubatsu "けいさつかんさつがい　"
  ; .marubatsu "みすい　ふうふさつがい　"
    .marubatsu "みすい　ふうふさつがい　"
  ; .marubatsu "１かげつまえ　"
    .marubatsu "１かげつまえ　"
  ; .marubatsu "はんとしまえ　"
    .marubatsu "はんとしまえ　"
  ; .marubatsu "いちねんまえ　"
    .marubatsu "いちねんまえ　"
  ; .marubatsu "にねんまえ　"
    .marubatsu "にねんまえ　"
.orga (0x0D343C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ベアー　"
    .marubatsu "ベアー　"
  ; .marubatsu "ウルフ　"
    .marubatsu "ウルフ　"
  ; .marubatsu "イーグル　"
    .marubatsu "イーグル　"
  ; .marubatsu "タイガー　"
    .marubatsu "タイガー　"
  ; .marubatsu "１かげつまえ　"
    .marubatsu "１かげつまえ　"
  ; .marubatsu "はんとしまえ　"
    .marubatsu "はんとしまえ　"
  ; .marubatsu "いちねんまえ　"
    .marubatsu "いちねんまえ　"
  ; .marubatsu "にねんまえ　"
    .marubatsu "にねんまえ　"

.loadtable "marubatsu_tbl\marubatsu_chs_1F.tbl"
.orga (0x0D354A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "はは　　"
    .marubatsu "はは　　"
  ; .marubatsu "あね　　"
    .marubatsu "あね　　"
  ; .marubatsu "あに　　"
    .marubatsu "あに　　"
  ; .marubatsu "おとうと　"
    .marubatsu "おとうと　"
  ; .marubatsu "２まんえん　"
    .marubatsu "２まんえん　"
  ; .marubatsu "１まんえん　"
    .marubatsu "１まんえん　"
  ; .marubatsu "６せんえん　"
    .marubatsu "６せんえん　"
  ; .marubatsu "３ぜんえん　"
    .marubatsu "３ぜんえん　"
  ; .marubatsu "きのう　"
    .marubatsu "きのう　"
  ; .marubatsu "けさ　　"
    .marubatsu "けさ　　"
  ; .marubatsu "ひる　　"
    .marubatsu "ひる　　"
  ; .marubatsu "よる　　"
    .marubatsu "よる　　"
.orga (0x0D35E6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１かん　"
    .marubatsu "１かん　"
  ; .marubatsu "２かん　"
    .marubatsu "２かん　"
  ; .marubatsu "３かん　"
    .marubatsu "３かん　"
  ; .marubatsu "４かん　"
    .marubatsu "４かん　"
  ; .marubatsu "きのう　"
    .marubatsu "きのう　"
  ; .marubatsu "けさ　　"
    .marubatsu "けさ　　"
  ; .marubatsu "ひる　　"
    .marubatsu "ひる　　"
  ; .marubatsu "よる　　"
    .marubatsu "よる　　"
  ; .marubatsu "２まんえん　"
    .marubatsu "２まんえん　"
  ; .marubatsu "１まんえん　"
    .marubatsu "１まんえん　"
  ; .marubatsu "６せんえん　"
    .marubatsu "６せんえん　"
  ; .marubatsu "３ぜんえん　"
    .marubatsu "３ぜんえん　"

.loadtable "marubatsu_tbl\marubatsu_chs_20.tbl"
.orga (0x0D36F4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こむぎこ　"
    .marubatsu "こむぎこ　"
  ; .marubatsu "ベーキングパウダー　"
    .marubatsu "ベーキングパウダー　"
  ; .marubatsu "たまご　"
    .marubatsu "たまご　"
  ; .marubatsu "さとう　"
    .marubatsu "さとう　"
  ; .marubatsu "１ばんめに　"
    .marubatsu "１ばんめに　"
  ; .marubatsu "２ばんめに　"
    .marubatsu "２ばんめに　"
  ; .marubatsu "３ばんめに　"
    .marubatsu "３ばんめに　"
  ; .marubatsu "４ばんめに　"
    .marubatsu "４ばんめに　"
  ; .marubatsu "５グラム　"
    .marubatsu "５グラム　"
  ; .marubatsu "５０グラム　"
    .marubatsu "５０グラム　"
  ; .marubatsu "５５グラム　"
    .marubatsu "５５グラム　"
  ; .marubatsu "１００グラム　"
    .marubatsu "１００グラム　"
.orga (0x0D3790 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あかいけ　"
    .marubatsu "あかいけ　"
  ; .marubatsu "ささもと　"
    .marubatsu "ささもと　"
  ; .marubatsu "なかざわ　"
    .marubatsu "なかざわ　"
  ; .marubatsu "たけむら　"
    .marubatsu "たけむら　"
  ; .marubatsu "５グラム　"
    .marubatsu "５グラム　"
  ; .marubatsu "５０グラム　"
    .marubatsu "５０グラム　"
  ; .marubatsu "５５グラム　"
    .marubatsu "５５グラム　"
  ; .marubatsu "１００グラム　"
    .marubatsu "１００グラム　"
  ; .marubatsu "１ばんめに　"
    .marubatsu "１ばんめに　"
  ; .marubatsu "２ばんめに　"
    .marubatsu "２ばんめに　"
  ; .marubatsu "３ばんめに　"
    .marubatsu "３ばんめに　"
  ; .marubatsu "４ばんめに　"
    .marubatsu "４ばんめに　"

.loadtable "marubatsu_tbl\marubatsu_chs_21.tbl"
.orga (0x0D389E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "まやく　"
    .marubatsu "まやく　"
  ; .marubatsu "ピストル　"
    .marubatsu "ピストル　"
  ; .marubatsu "ブラジャー　"
    .marubatsu "ブラジャー　"
  ; .marubatsu "ナイフ　"
    .marubatsu "ナイフ　"
  ; .marubatsu "デイパック　"
    .marubatsu "デイパック　"
  ; .marubatsu "ボストンバッグ　"
    .marubatsu "ボストンバッグ　"
  ; .marubatsu "セカンドバッグ　"
    .marubatsu "セカンドバッグ　"
  ; .marubatsu "スーツケース　"
    .marubatsu "スーツケース　"
.orga (0x0D393A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "おかだ　"
    .marubatsu "おかだ　"
  ; .marubatsu "もり　　"
    .marubatsu "もり　　"
  ; .marubatsu "やぎ　　"
    .marubatsu "やぎ　　"
  ; .marubatsu "まるやま　"
    .marubatsu "まるやま　"
  ; .marubatsu "デイパック　"
    .marubatsu "デイパック　"
  ; .marubatsu "ボストンバッグ　"
    .marubatsu "ボストンバッグ　"
  ; .marubatsu "セカンドバッグ　"
    .marubatsu "セカンドバッグ　"
  ; .marubatsu "スーツケース　"
    .marubatsu "スーツケース　"

.loadtable "marubatsu_tbl\marubatsu_chs_22.tbl"
.orga (0x0D3A48 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ロビーで　"
    .marubatsu "ロビーで　"
  ; .marubatsu "なかにわで　"
    .marubatsu "なかにわで　"
  ; .marubatsu "へやで　"
    .marubatsu "へやで　"
  ; .marubatsu "バーで　"
    .marubatsu "バーで　"
  ; .marubatsu "０９５０に　"
    .marubatsu "０９５０に　"
  ; .marubatsu "１０１０に　"
    .marubatsu "１０１０に　"
  ; .marubatsu "１０２０に　"
    .marubatsu "１０２０に　"
  ; .marubatsu "１０３０に　"
    .marubatsu "１０３０に　"
.orga (0x0D3AE4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "いけま　"
    .marubatsu "いけま　"
  ; .marubatsu "とくなが　"
    .marubatsu "とくなが　"
  ; .marubatsu "しまや　"
    .marubatsu "しまや　"
  ; .marubatsu "すながわ　"
    .marubatsu "すながわ　"
  ; .marubatsu "０９５０に　"
    .marubatsu "０９５０に　"
  ; .marubatsu "１０１０に　"
    .marubatsu "１０１０に　"
  ; .marubatsu "１０２０に　"
    .marubatsu "１０２０に　"
  ; .marubatsu "１０３０に　"
    .marubatsu "１０３０に　"

.loadtable "marubatsu_tbl\marubatsu_chs_23.tbl"
.orga (0x0D3BF2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シュークリーム　"
    .marubatsu "シュークリーム　"
  ; .marubatsu "チョコケーキ　"
    .marubatsu "チョコケーキ　"
  ; .marubatsu "イチゴショート　"
    .marubatsu "イチゴショート　"
  ; .marubatsu "チーズケーキ　"
    .marubatsu "チーズケーキ　"
  ; .marubatsu "３００えん　"
    .marubatsu "３００えん　"
  ; .marubatsu "４００えん　"
    .marubatsu "４００えん　"
  ; .marubatsu "５００えん　"
    .marubatsu "５００えん　"
  ; .marubatsu "６００えん　"
    .marubatsu "６００えん　"
.orga (0x0D3C8E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "うさぎや　"
    .marubatsu "うさぎや　"
  ; .marubatsu "フランセ　"
    .marubatsu "フランセ　"
  ; .marubatsu "ビーグル　"
    .marubatsu "ビーグル　"
  ; .marubatsu "パンダや　"
    .marubatsu "パンダや　"
  ; .marubatsu "３００えん　"
    .marubatsu "３００えん　"
  ; .marubatsu "４００えん　"
    .marubatsu "４００えん　"
  ; .marubatsu "５００えん　"
    .marubatsu "５００えん　"
  ; .marubatsu "６００えん　"
    .marubatsu "６００えん　"

.loadtable "marubatsu_tbl\marubatsu_chs_24.tbl"
.orga (0x0D3D9C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "そばや　"
    .marubatsu "そばや　"
  ; .marubatsu "きっさてん　"
    .marubatsu "きっさてん　"
  ; .marubatsu "ラーメンや　"
    .marubatsu "ラーメンや　"
  ; .marubatsu "カレーせんもんてん　"
    .marubatsu "カレーせんもんてん　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１ちょうめ　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２ちょうめ　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３ちょうめ　"
  ; .marubatsu "４ちょうめ　"
    .marubatsu "４ちょうめ　"
  ; .marubatsu "げつようび　"
    .marubatsu "げつようび　"
  ; .marubatsu "すいようび　"
    .marubatsu "すいようび　"
  ; .marubatsu "きんようび　"
    .marubatsu "きんようび　"
  ; .marubatsu "にちようび　"
    .marubatsu "にちようび　"
.orga (0x0D3E38 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "さくら　"
    .marubatsu "さくら　"
  ; .marubatsu "パンジー　"
    .marubatsu "パンジー　"
  ; .marubatsu "アイリス　"
    .marubatsu "アイリス　"
  ; .marubatsu "うめ　　"
    .marubatsu "うめ　　"
  ; .marubatsu "げつようび　"
    .marubatsu "げつようび　"
  ; .marubatsu "すいようび　"
    .marubatsu "すいようび　"
  ; .marubatsu "きんようび　"
    .marubatsu "きんようび　"
  ; .marubatsu "にちようび　"
    .marubatsu "にちようび　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１ちょうめ　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２ちょうめ　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３ちょうめ　"
  ; .marubatsu "４ちょうめ　"
    .marubatsu "４ちょうめ　"

.loadtable "marubatsu_tbl\marubatsu_chs_25.tbl"
.orga (0x0D3F46 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "まさと　"
    .marubatsu "まさと　"
  ; .marubatsu "ゆか　　"
    .marubatsu "ゆか　　"
  ; .marubatsu "たかのり　"
    .marubatsu "たかのり　"
  ; .marubatsu "きょうこ　"
    .marubatsu "きょうこ　"
  ; .marubatsu "しょくひんうりば　"
    .marubatsu "しょくひんうりば　"
  ; .marubatsu "しんしふくうりば　"
    .marubatsu "しんしふくうりば　"
  ; .marubatsu "ふじんふくうりば　"
    .marubatsu "ふじんふくうりば　"
  ; .marubatsu "おもちゃうりば　"
    .marubatsu "おもちゃうりば　"
  ; .marubatsu "２さい　"
    .marubatsu "２さい　"
  ; .marubatsu "３さい　"
    .marubatsu "３さい　"
  ; .marubatsu "４さい　"
    .marubatsu "４さい　"
  ; .marubatsu "５さい　"
    .marubatsu "５さい　"
.orga (0x0D3FE2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "なかむら　"
    .marubatsu "なかむら　"
  ; .marubatsu "こうの　"
    .marubatsu "こうの　"
  ; .marubatsu "たけはら　"
    .marubatsu "たけはら　"
  ; .marubatsu "さいとう　"
    .marubatsu "さいとう　"
  ; .marubatsu "２さい　"
    .marubatsu "２さい　"
  ; .marubatsu "３さい　"
    .marubatsu "３さい　"
  ; .marubatsu "４さい　"
    .marubatsu "４さい　"
  ; .marubatsu "５さい　"
    .marubatsu "５さい　"
  ; .marubatsu "しょくひんうりば　"
    .marubatsu "しょくひんうりば　"
  ; .marubatsu "しんしふくうりば　"
    .marubatsu "しんしふくうりば　"
  ; .marubatsu "ふじんふくうりば　"
    .marubatsu "ふじんふくうりば　"
  ; .marubatsu "おもちゃうりば　"
    .marubatsu "おもちゃうりば　"

.loadtable "marubatsu_tbl\marubatsu_chs_26.tbl"
.orga (0x0D40F0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ロープ　"
    .marubatsu "ロープ　"
  ; .marubatsu "ジーパン　"
    .marubatsu "ジーパン　"
  ; .marubatsu "ナイフ　"
    .marubatsu "ナイフ　"
  ; .marubatsu "シャツ　"
    .marubatsu "シャツ　"
  ; .marubatsu "かわにすてた　"
    .marubatsu "かわにすてた　"
  ; .marubatsu "こうえんでもやした　"
    .marubatsu "こうえんでもやした　"
  ; .marubatsu "ごみすてばにすてた　"
    .marubatsu "ごみすてばにすてた　"
  ; .marubatsu "やまにうめた　"
    .marubatsu "やまにうめた　"
.orga (0x0D418C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめにすてた　"
    .marubatsu "１ばんめにすてた　"
  ; .marubatsu "２ばんめにすてた　"
    .marubatsu "２ばんめにすてた　"
  ; .marubatsu "３ばんめにすてた　"
    .marubatsu "３ばんめにすてた　"
  ; .marubatsu "４ばんめにすてた　"
    .marubatsu "４ばんめにすてた　"
  ; .marubatsu "かわにすてた　"
    .marubatsu "かわにすてた　"
  ; .marubatsu "こうえんでもやした　"
    .marubatsu "こうえんでもやした　"
  ; .marubatsu "ごみすてばにすてた　"
    .marubatsu "ごみすてばにすてた　"
  ; .marubatsu "やまにうめた　"
    .marubatsu "やまにうめた　"

.loadtable "marubatsu_tbl\marubatsu_chs_27.tbl"
.orga (0x0D429A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "４ばんめ　"
  ; .marubatsu "やきもの　"
    .marubatsu "やきもの　"
  ; .marubatsu "ゴルフクラブ　"
    .marubatsu "ゴルフクラブ　"
  ; .marubatsu "にほんとう　"
    .marubatsu "にほんとう　"
  ; .marubatsu "ネクタイ　"
    .marubatsu "ネクタイ　"
.orga (0x0D4336 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "なかがわ　"
    .marubatsu "なかがわ　"
  ; .marubatsu "まき　　"
    .marubatsu "まき　　"
  ; .marubatsu "たむら　"
    .marubatsu "たむら　"
  ; .marubatsu "おおはし　"
    .marubatsu "おおはし　"
  ; .marubatsu "やきもの　"
    .marubatsu "やきもの　"
  ; .marubatsu "ゴルフクラブ　"
    .marubatsu "ゴルフクラブ　"
  ; .marubatsu "にほんとう　"
    .marubatsu "にほんとう　"
  ; .marubatsu "ネクタイ　"
    .marubatsu "ネクタイ　"

.loadtable "marubatsu_tbl\marubatsu_chs_28.tbl"
.orga (0x0D4444 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "トロのにぎり　"
    .marubatsu "トロのにぎり　"
  ; .marubatsu "アジのにぎり　"
    .marubatsu "アジのにぎり　"
  ; .marubatsu "タコのにぎり　"
    .marubatsu "タコのにぎり　"
  ; .marubatsu "サバのにぎり　"
    .marubatsu "サバのにぎり　"
  ; .marubatsu "きよし　"
    .marubatsu "きよし　"
  ; .marubatsu "あおい　"
    .marubatsu "あおい　"
  ; .marubatsu "のぶみち　"
    .marubatsu "のぶみち　"
  ; .marubatsu "たかひろ　"
    .marubatsu "たかひろ　"
.orga (0x0D44E0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "サヤカ　"
    .marubatsu "サヤカ　"
  ; .marubatsu "ノリコ　"
    .marubatsu "ノリコ　"
  ; .marubatsu "エリカ　"
    .marubatsu "エリカ　"
  ; .marubatsu "マキ　　"
    .marubatsu "マキ　　"
  ; .marubatsu "きよし　"
    .marubatsu "きよし　"
  ; .marubatsu "あおい　"
    .marubatsu "あおい　"
  ; .marubatsu "のぶみち　"
    .marubatsu "のぶみち　"
  ; .marubatsu "たかひろ　"
    .marubatsu "たかひろ　"

.loadtable "marubatsu_tbl\marubatsu_chs_29.tbl"
.orga (0x0D45EE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "たいようがもえもえ　"
    .marubatsu "たいようがもえもえ　"
  ; .marubatsu "かがやくきせつ　"
    .marubatsu "かがやくきせつ　"
  ; .marubatsu "かもね　"
    .marubatsu "かもね　"
  ; .marubatsu "だんごのおやこ　"
    .marubatsu "だんごのおやこ　"
  ; .marubatsu "ザ　モンキー　"
    .marubatsu "ザ　モンキー　"
  ; .marubatsu "かねこまみ　"
    .marubatsu "かねこまみ　"
  ; .marubatsu "ジョージながおか　"
    .marubatsu "ジョージながおか　"
  ; .marubatsu "ようこ　"
    .marubatsu "ようこ　"
  ; .marubatsu "ロック　"
    .marubatsu "ロック　"
  ; .marubatsu "えんか　"
    .marubatsu "えんか　"
  ; .marubatsu "ラップ　"
    .marubatsu "ラップ　"
  ; .marubatsu "アニメソング　"
    .marubatsu "アニメソング　"
.orga (0x0D468A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめのうた　"
    .marubatsu "１ばんめのうた　"
  ; .marubatsu "２ばんめのうた　"
    .marubatsu "２ばんめのうた　"
  ; .marubatsu "３ばんめのうた　"
    .marubatsu "３ばんめのうた　"
  ; .marubatsu "４ばんめのうた　"
    .marubatsu "４ばんめのうた　"
  ; .marubatsu "ロック　"
    .marubatsu "ロック　"
  ; .marubatsu "えんか　"
    .marubatsu "えんか　"
  ; .marubatsu "ラップ　"
    .marubatsu "ラップ　"
  ; .marubatsu "アニメソング　"
    .marubatsu "アニメソング　"
  ; .marubatsu "ザ　モンキー　"
    .marubatsu "ザ　モンキー　"
  ; .marubatsu "かねこまみ　"
    .marubatsu "かねこまみ　"
  ; .marubatsu "ジョージながおか　"
    .marubatsu "ジョージながおか　"
  ; .marubatsu "ようこ　"
    .marubatsu "ようこ　"

.loadtable "marubatsu_tbl\marubatsu_chs_2A.tbl"
.orga (0x0D4798 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１０００まんえん　"
    .marubatsu "１０００まんえん　"
  ; .marubatsu "２０００まんえん　"
    .marubatsu "２０００まんえん　"
  ; .marubatsu "３０００まんえん　"
    .marubatsu "３０００まんえん　"
  ; .marubatsu "４０００まんえん　"
    .marubatsu "４０００まんえん　"
  ; .marubatsu "くろいカバン　"
    .marubatsu "くろいカバン　"
  ; .marubatsu "あおいカバン　"
    .marubatsu "あおいカバン　"
  ; .marubatsu "しろいカバン　"
    .marubatsu "しろいカバン　"
  ; .marubatsu "あかいカバン　"
    .marubatsu "あかいカバン　"
  ; .marubatsu "でんわボックス　"
    .marubatsu "でんわボックス　"
  ; .marubatsu "コインロッカー　"
    .marubatsu "コインロッカー　"
  ; .marubatsu "こうしゅうトイレ　"
    .marubatsu "こうしゅうトイレ　"
  ; .marubatsu "こうえんのベンチ　"
    .marubatsu "こうえんのベンチ　"
.orga (0x0D4834 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ちちおや　"
    .marubatsu "ちちおや　"
  ; .marubatsu "ははおや　"
    .marubatsu "ははおや　"
  ; .marubatsu "あね　　"
    .marubatsu "あね　　"
  ; .marubatsu "あに　　"
    .marubatsu "あに　　"
  ; .marubatsu "でんわボックス　"
    .marubatsu "でんわボックス　"
  ; .marubatsu "コインロッカー　"
    .marubatsu "コインロッカー　"
  ; .marubatsu "こうしゅうトイレ　"
    .marubatsu "こうしゅうトイレ　"
  ; .marubatsu "こうえんのベンチ　"
    .marubatsu "こうえんのベンチ　"
  ; .marubatsu "くろいカバン　"
    .marubatsu "くろいカバン　"
  ; .marubatsu "あおいカバン　"
    .marubatsu "あおいカバン　"
  ; .marubatsu "しろいカバン　"
    .marubatsu "しろいカバン　"
  ; .marubatsu "あかいカバン　"
    .marubatsu "あかいカバン　"

.loadtable "marubatsu_tbl\marubatsu_chs_2B.tbl"
.orga (0x0D4942 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルパン　"
    .marubatsu "ルパン　"
  ; .marubatsu "ホームズ　"
    .marubatsu "ホームズ　"
  ; .marubatsu "ポアロ　"
    .marubatsu "ポアロ　"
  ; .marubatsu "マーブル　"
    .marubatsu "マーブル　"
  ; .marubatsu "１じに　"
    .marubatsu "１じに　"
  ; .marubatsu "２じに　"
    .marubatsu "２じに　"
  ; .marubatsu "３じに　"
    .marubatsu "３じに　"
  ; .marubatsu "４じに　"
    .marubatsu "４じに　"
.orga (0x0D49DE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こうえん　"
    .marubatsu "こうえん　"
  ; .marubatsu "デパート　"
    .marubatsu "デパート　"
  ; .marubatsu "ホテル　"
    .marubatsu "ホテル　"
  ; .marubatsu "こうこう　"
    .marubatsu "こうこう　"
  ; .marubatsu "１じに　"
    .marubatsu "１じに　"
  ; .marubatsu "２じに　"
    .marubatsu "２じに　"
  ; .marubatsu "３じに　"
    .marubatsu "３じに　"
  ; .marubatsu "４じに　"
    .marubatsu "４じに　"

.loadtable "marubatsu_tbl\marubatsu_chs_2C.tbl"
.orga (0x0D4AEC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ほし　　"
    .marubatsu "ほし　　"
  ; .marubatsu "タロット　"
    .marubatsu "タロット　"
  ; .marubatsu "てそう　"
    .marubatsu "てそう　"
  ; .marubatsu "にんそう　"
    .marubatsu "にんそう　"
  ; .marubatsu "１ばんにんき　"
    .marubatsu "１ばんにんき　"
  ; .marubatsu "２ばんにんき　"
    .marubatsu "２ばんにんき　"
  ; .marubatsu "３ばんにんき　"
    .marubatsu "３ばんにんき　"
  ; .marubatsu "４ばんにんき　"
    .marubatsu "４ばんにんき　"
.orga (0x0D4B88 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ひがしのへや　"
    .marubatsu "ひがしのへや　"
  ; .marubatsu "にしのへや　"
    .marubatsu "にしのへや　"
  ; .marubatsu "みなみのへや　"
    .marubatsu "みなみのへや　"
  ; .marubatsu "きたのへや　"
    .marubatsu "きたのへや　"
  ; .marubatsu "１ばんにんき　"
    .marubatsu "１ばんにんき　"
  ; .marubatsu "２ばんにんき　"
    .marubatsu "２ばんにんき　"
  ; .marubatsu "３ばんにんき　"
    .marubatsu "３ばんにんき　"
  ; .marubatsu "４ばんにんき　"
    .marubatsu "４ばんにんき　"

.loadtable "marubatsu_tbl\marubatsu_chs_2D.tbl"
.orga (0x0D4C96 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しょくどう　"
    .marubatsu "しょくどう　"
  ; .marubatsu "リビングルーム　"
    .marubatsu "リビングルーム　"
  ; .marubatsu "ベランダ　"
    .marubatsu "ベランダ　"
  ; .marubatsu "ベッドルーム　"
    .marubatsu "ベッドルーム　"
  ; .marubatsu "コーヒー　"
    .marubatsu "コーヒー　"
  ; .marubatsu "こうちゃ　"
    .marubatsu "こうちゃ　"
  ; .marubatsu "ばんちゃ　"
    .marubatsu "ばんちゃ　"
  ; .marubatsu "ホットミルク　"
    .marubatsu "ホットミルク　"
  ; .marubatsu "あさ　　"
    .marubatsu "あさ　　"
  ; .marubatsu "ひる　　"
    .marubatsu "ひる　　"
  ; .marubatsu "ゆうがた　"
    .marubatsu "ゆうがた　"
  ; .marubatsu "よる　　"
    .marubatsu "よる　　"
.orga (0x0D4D32 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あかいカップ　"
    .marubatsu "あかいカップ　"
  ; .marubatsu "しろいカップ　"
    .marubatsu "しろいカップ　"
  ; .marubatsu "くろいカップ　"
    .marubatsu "くろいカップ　"
  ; .marubatsu "みどりのカップ　"
    .marubatsu "みどりのカップ　"
  ; .marubatsu "あさ　　"
    .marubatsu "あさ　　"
  ; .marubatsu "ひる　　"
    .marubatsu "ひる　　"
  ; .marubatsu "ゆうがた　"
    .marubatsu "ゆうがた　"
  ; .marubatsu "よる　　"
    .marubatsu "よる　　"
  ; .marubatsu "コーヒー　"
    .marubatsu "コーヒー　"
  ; .marubatsu "こうちゃ　"
    .marubatsu "こうちゃ　"
  ; .marubatsu "ばんちゃ　"
    .marubatsu "ばんちゃ　"
  ; .marubatsu "ホットミルク　"
    .marubatsu "ホットミルク　"

.loadtable "marubatsu_tbl\marubatsu_chs_2E.tbl"
.orga (0x0D4E40 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１２じに　"
    .marubatsu "１２じに　"
  ; .marubatsu "１じに　"
    .marubatsu "１じに　"
  ; .marubatsu "２じに　"
    .marubatsu "２じに　"
  ; .marubatsu "３じに　"
    .marubatsu "３じに　"
  ; .marubatsu "ぎんこう　"
    .marubatsu "ぎんこう　"
  ; .marubatsu "スーパー　"
    .marubatsu "スーパー　"
  ; .marubatsu "がっこう　"
    .marubatsu "がっこう　"
  ; .marubatsu "アパート　"
    .marubatsu "アパート　"
  ; .marubatsu "ごみばこがもえた　"
    .marubatsu "ごみばこがもえた　"
  ; .marubatsu "くるまがもえた　"
    .marubatsu "くるまがもえた　"
  ; .marubatsu "ビニールがもえた　"
    .marubatsu "ビニールがもえた　"
  ; .marubatsu "ポスターがもえた　"
    .marubatsu "ポスターがもえた　"
.orga (0x0D4EDC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "くわはら　"
    .marubatsu "くわはら　"
  ; .marubatsu "のぐち　"
    .marubatsu "のぐち　"
  ; .marubatsu "えばた　"
    .marubatsu "えばた　"
  ; .marubatsu "なかはら　"
    .marubatsu "なかはら　"
  ; .marubatsu "ごみばこがもえた　"
    .marubatsu "ごみばこがもえた　"
  ; .marubatsu "くるまがもえた　"
    .marubatsu "くるまがもえた　"
  ; .marubatsu "ビニールがもえた　"
    .marubatsu "ビニールがもえた　"
  ; .marubatsu "ポスターがもえた　"
    .marubatsu "ポスターがもえた　"
  ; .marubatsu "ぎんこう　"
    .marubatsu "ぎんこう　"
  ; .marubatsu "スーパー　"
    .marubatsu "スーパー　"
  ; .marubatsu "がっこう　"
    .marubatsu "がっこう　"
  ; .marubatsu "アパート　"
    .marubatsu "アパート　"

.loadtable "marubatsu_tbl\marubatsu_chs_2F.tbl"
.orga (0x0D4FEA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "きんけん　"
    .marubatsu "きんけん　"
  ; .marubatsu "つぼ　　"
    .marubatsu "つぼ　　"
  ; .marubatsu "げんきん　"
    .marubatsu "げんきん　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "ダイヤ　"
  ; .marubatsu "５まんえん　"
    .marubatsu "５まんえん　"
  ; .marubatsu "１０まんえん　"
    .marubatsu "１０まんえん　"
  ; .marubatsu "３０まんえん　"
    .marubatsu "３０まんえん　"
  ; .marubatsu "８０まんえん　"
    .marubatsu "８０まんえん　"
  ; .marubatsu "きょう　"
    .marubatsu "きょう　"
  ; .marubatsu "きのう　"
    .marubatsu "きのう　"
  ; .marubatsu "５にちまえ　"
    .marubatsu "５にちまえ　"
  ; .marubatsu "７にちまえ　"
    .marubatsu "７にちまえ　"
.orga (0x0D5086 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "いしゃのいえ　"
    .marubatsu "いしゃのいえ　"
  ; .marubatsu "はいゆうのいえ　"
    .marubatsu "はいゆうのいえ　"
  ; .marubatsu "べんごしのいえ　"
    .marubatsu "べんごしのいえ　"
  ; .marubatsu "きょうしのいえ　"
    .marubatsu "きょうしのいえ　"
  ; .marubatsu "きょう　"
    .marubatsu "きょう　"
  ; .marubatsu "きのう　"
    .marubatsu "きのう　"
  ; .marubatsu "５にちまえ　"
    .marubatsu "５にちまえ　"
  ; .marubatsu "７にちまえ　"
    .marubatsu "７にちまえ　"
  ; .marubatsu "５まんえん　"
    .marubatsu "５まんえん　"
  ; .marubatsu "１０まんえん　"
    .marubatsu "１０まんえん　"
  ; .marubatsu "３０まんえん　"
    .marubatsu "３０まんえん　"
  ; .marubatsu "８０まんえん　"
    .marubatsu "８０まんえん　"

.loadtable "marubatsu_tbl\marubatsu_chs_30.tbl"
.orga (0x0D5194 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アジト１　"
    .marubatsu "アジト１　"
  ; .marubatsu "アジト２　"
    .marubatsu "アジト２　"
  ; .marubatsu "アジト３　"
    .marubatsu "アジト３　"
  ; .marubatsu "アジト４　"
    .marubatsu "アジト４　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１ちょうめ　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２ちょうめ　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３ちょうめ　"
  ; .marubatsu "となりまち　"
    .marubatsu "となりまち　"
.orga (0x0D5230 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かわい　"
    .marubatsu "かわい　"
  ; .marubatsu "おきた　"
    .marubatsu "おきた　"
  ; .marubatsu "とよだ　"
    .marubatsu "とよだ　"
  ; .marubatsu "かわぐち　"
    .marubatsu "かわぐち　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１ちょうめ　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２ちょうめ　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３ちょうめ　"
  ; .marubatsu "となりまち　"
    .marubatsu "となりまち　"

.loadtable "marubatsu_tbl\marubatsu_chs_31.tbl"
.orga (0x0D533E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ポーカー　"
    .marubatsu "ポーカー　"
  ; .marubatsu "ルーレット　"
    .marubatsu "ルーレット　"
  ; .marubatsu "スロット　"
    .marubatsu "スロット　"
  ; .marubatsu "バカラ　"
    .marubatsu "バカラ　"
  ; .marubatsu "１００チップ　"
    .marubatsu "１００チップ　"
  ; .marubatsu "２００チップ　"
    .marubatsu "２００チップ　"
  ; .marubatsu "３００チップ　"
    .marubatsu "３００チップ　"
  ; .marubatsu "４００チップ　"
    .marubatsu "４００チップ　"
.orga (0x0D53DA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あかい　"
    .marubatsu "あかい　"
  ; .marubatsu "あおの　"
    .marubatsu "あおの　"
  ; .marubatsu "きじま　"
    .marubatsu "きじま　"
  ; .marubatsu "くろさき　"
    .marubatsu "くろさき　"
  ; .marubatsu "１００チップ　"
    .marubatsu "１００チップ　"
  ; .marubatsu "２００チップ　"
    .marubatsu "２００チップ　"
  ; .marubatsu "３００チップ　"
    .marubatsu "３００チップ　"
  ; .marubatsu "４００チップ　"
    .marubatsu "４００チップ　"

.loadtable "marubatsu_tbl\marubatsu_chs_32.tbl"
.orga (0x0D54E8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ひでき　"
    .marubatsu "ひでき　"
  ; .marubatsu "さとる　"
    .marubatsu "さとる　"
  ; .marubatsu "よういち　"
    .marubatsu "よういち　"
  ; .marubatsu "てっぺい　"
    .marubatsu "てっぺい　"
  ; .marubatsu "げつようび　"
    .marubatsu "げつようび　"
  ; .marubatsu "かようび　"
    .marubatsu "かようび　"
  ; .marubatsu "すいようび　"
    .marubatsu "すいようび　"
  ; .marubatsu "もくようび　"
    .marubatsu "もくようび　"
.orga (0x0D5584 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "はるか　"
    .marubatsu "はるか　"
  ; .marubatsu "なつみ　"
    .marubatsu "なつみ　"
  ; .marubatsu "あきえ　"
    .marubatsu "あきえ　"
  ; .marubatsu "ふゆこ　"
    .marubatsu "ふゆこ　"
  ; .marubatsu "げつようび　"
    .marubatsu "げつようび　"
  ; .marubatsu "かようび　"
    .marubatsu "かようび　"
  ; .marubatsu "すいようび　"
    .marubatsu "すいようび　"
  ; .marubatsu "もくようび　"
    .marubatsu "もくようび　"

.loadtable "marubatsu_tbl\marubatsu_chs_33.tbl"
.orga (0x0D5692 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "マイコ　"
    .marubatsu "マイコ　"
  ; .marubatsu "ユウコ　"
    .marubatsu "ユウコ　"
  ; .marubatsu "アユミ　"
    .marubatsu "アユミ　"
  ; .marubatsu "ナツコ　"
    .marubatsu "ナツコ　"
  ; .marubatsu "おしゃれなうでどけい　"
    .marubatsu "おしゃれなうでどけい　"
  ; .marubatsu "かわいいシール　"
    .marubatsu "かわいいシール　"
  ; .marubatsu "ハートのピアス　"
    .marubatsu "ハートのピアス　"
  ; .marubatsu "バラのはなたば　"
    .marubatsu "バラのはなたば　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "さいご　"
    .marubatsu "さいご　"
.orga (0x0D572E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ぶしつのロッカー　"
    .marubatsu "ぶしつのロッカー　"
  ; .marubatsu "たいいくかんばき　"
    .marubatsu "たいいくかんばき　"
  ; .marubatsu "スポーツかばん　"
    .marubatsu "スポーツかばん　"
  ; .marubatsu "うんどうようジャージ　"
    .marubatsu "うんどうようジャージ　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "１ばんめ　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "２ばんめ　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "３ばんめ　"
  ; .marubatsu "さいご　"
    .marubatsu "さいご　"
  ; .marubatsu "おしゃれなうでどけい　"
    .marubatsu "おしゃれなうでどけい　"
  ; .marubatsu "かわいいシール　"
    .marubatsu "かわいいシール　"
  ; .marubatsu "ハートのピアス　"
    .marubatsu "ハートのピアス　"
  ; .marubatsu "バラのはなたば　"
    .marubatsu "バラのはなたば　"

.loadtable "marubatsu_tbl\marubatsu_chs_34.tbl"
.orga (0x0D583C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "サッカーぶ　"
    .marubatsu "サッカーぶ　"
  ; .marubatsu "やきゅうぶ　"
    .marubatsu "やきゅうぶ　"
  ; .marubatsu "すいえいぶ　"
    .marubatsu "すいえいぶ　"
  ; .marubatsu "けんどうぶ　"
    .marubatsu "けんどうぶ　"
  ; .marubatsu "１ばんすき　"
    .marubatsu "１ばんすき　"
  ; .marubatsu "２ばんめにすき　"
    .marubatsu "２ばんめにすき　"
  ; .marubatsu "３ばんめにすき　"
    .marubatsu "３ばんめにすき　"
  ; .marubatsu "４ばんめにすき　"
    .marubatsu "４ばんめにすき　"
.orga (0x0D58D8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こまつ　"
    .marubatsu "こまつ　"
  ; .marubatsu "おおの　"
    .marubatsu "おおの　"
  ; .marubatsu "おおたき　"
    .marubatsu "おおたき　"
  ; .marubatsu "まつした　"
    .marubatsu "まつした　"
  ; .marubatsu "１ばんすき　"
    .marubatsu "１ばんすき　"
  ; .marubatsu "２ばんめにすき　"
    .marubatsu "２ばんめにすき　"
  ; .marubatsu "３ばんめにすき　"
    .marubatsu "３ばんめにすき　"
  ; .marubatsu "４ばんめにすき　"
    .marubatsu "４ばんめにすき　"

.loadtable "marubatsu_tbl\marubatsu_chs_35.tbl"
.orga (0x0D59E6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かがわ　"
    .marubatsu "かがわ　"
  ; .marubatsu "やまぐち　"
    .marubatsu "やまぐち　"
  ; .marubatsu "みやぎ　"
    .marubatsu "みやぎ　"
  ; .marubatsu "ふくおか　"
    .marubatsu "ふくおか　"
  ; .marubatsu "ばらばらじけん　"
    .marubatsu "ばらばらじけん　"
  ; .marubatsu "じゅうさつ　"
    .marubatsu "じゅうさつ　"
  ; .marubatsu "こうさつ　"
    .marubatsu "こうさつ　"
  ; .marubatsu "みすい　"
    .marubatsu "みすい　"
  ; .marubatsu "ことし　"
    .marubatsu "ことし　"
  ; .marubatsu "１ねんまえ　"
    .marubatsu "１ねんまえ　"
  ; .marubatsu "３ねんまえ　"
    .marubatsu "３ねんまえ　"
  ; .marubatsu "４ねんまえ　"
    .marubatsu "４ねんまえ　"
.orga (0x0D5A82 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ちば　　"
    .marubatsu "ちば　　"
  ; .marubatsu "ふくしま　"
    .marubatsu "ふくしま　"
  ; .marubatsu "やまがた　"
    .marubatsu "やまがた　"
  ; .marubatsu "ながの　"
    .marubatsu "ながの　"
  ; .marubatsu "ことし　"
    .marubatsu "ことし　"
  ; .marubatsu "１ねんまえ　"
    .marubatsu "１ねんまえ　"
  ; .marubatsu "３ねんまえ　"
    .marubatsu "３ねんまえ　"
  ; .marubatsu "４ねんまえ　"
    .marubatsu "４ねんまえ　"
  ; .marubatsu "ばらばらじけん　"
    .marubatsu "ばらばらじけん　"
  ; .marubatsu "じゅうさつ　"
    .marubatsu "じゅうさつ　"
  ; .marubatsu "こうさつ　"
    .marubatsu "こうさつ　"
  ; .marubatsu "みすい　"
    .marubatsu "みすい　"

.loadtable "marubatsu_tbl\marubatsu_chs_36.tbl"
.orga (0x0D5B90 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しごとのはなし　"
    .marubatsu "しごとのはなし　"
  ; .marubatsu "れんあいのそうだん　"
    .marubatsu "れんあいのそうだん　"
  ; .marubatsu "そうおんのくじょう　"
    .marubatsu "そうおんのくじょう　"
  ; .marubatsu "おかねのはなし　"
    .marubatsu "おかねのはなし　"
  ; .marubatsu "ともだち　"
    .marubatsu "ともだち　"
  ; .marubatsu "となり　"
    .marubatsu "となり　"
  ; .marubatsu "こいびと　"
    .marubatsu "こいびと　"
  ; .marubatsu "あに　　"
    .marubatsu "あに　　"
  ; .marubatsu "６じ　　"
    .marubatsu "６じ　　"
  ; .marubatsu "７じ　　"
    .marubatsu "７じ　　"
  ; .marubatsu "８じ　　"
    .marubatsu "８じ　　"
  ; .marubatsu "９じ　　"
    .marubatsu "９じ　　"
.orga (0x0D5C2C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "やまだ　"
    .marubatsu "やまだ　"
  ; .marubatsu "かわはら　"
    .marubatsu "かわはら　"
  ; .marubatsu "たにぐち　"
    .marubatsu "たにぐち　"
  ; .marubatsu "もり　　"
    .marubatsu "もり　　"
  ; .marubatsu "６じ　　"
    .marubatsu "６じ　　"
  ; .marubatsu "７じ　　"
    .marubatsu "７じ　　"
  ; .marubatsu "８じ　　"
    .marubatsu "８じ　　"
  ; .marubatsu "９じ　　"
    .marubatsu "９じ　　"
  ; .marubatsu "ともだち　"
    .marubatsu "ともだち　"
  ; .marubatsu "となり　"
    .marubatsu "となり　"
  ; .marubatsu "こいびと　"
    .marubatsu "こいびと　"
  ; .marubatsu "あに　　"
    .marubatsu "あに　　"

.loadtable "marubatsu_tbl\marubatsu_chs_37.tbl"
.orga (0x0D5D3A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "げつようび　"
    .marubatsu "げつようび　"
  ; .marubatsu "かようび　"
    .marubatsu "かようび　"
  ; .marubatsu "もくようび　"
    .marubatsu "もくようび　"
  ; .marubatsu "きんようび　"
    .marubatsu "きんようび　"
  ; .marubatsu "スター　"
    .marubatsu "スター　"
  ; .marubatsu "マフイア　"
    .marubatsu "マフイア　"
  ; .marubatsu "だいふごう　"
    .marubatsu "だいふごう　"
  ; .marubatsu "はかせ　"
    .marubatsu "はかせ　"
  ; .marubatsu "まずまずのけっか　"
    .marubatsu "まずまずのけっか　"
  ; .marubatsu "２はつでしとめた　"
    .marubatsu "２はつでしとめた　"
  ; .marubatsu "かんぺきなしごと　"
    .marubatsu "かんぺきなしごと　"
  ; .marubatsu "にげられた　"
    .marubatsu "にげられた　"
.orga (0x0D5DD6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アメリカ　"
    .marubatsu "アメリカ　"
  ; .marubatsu "ブラジル　"
    .marubatsu "ブラジル　"
  ; .marubatsu "フランス　"
    .marubatsu "フランス　"
  ; .marubatsu "イギリス　"
    .marubatsu "イギリス　"
  ; .marubatsu "まずまずのけっか　"
    .marubatsu "まずまずのけっか　"
  ; .marubatsu "２はつでしとめた　"
    .marubatsu "２はつでしとめた　"
  ; .marubatsu "かんぺきなしごと　"
    .marubatsu "かんぺきなしごと　"
  ; .marubatsu "にげられた　"
    .marubatsu "にげられた　"
  ; .marubatsu "スター　"
    .marubatsu "スター　"
  ; .marubatsu "マフイア　"
    .marubatsu "マフイア　"
  ; .marubatsu "だいふごう　"
    .marubatsu "だいふごう　"
  ; .marubatsu "はかせ　"
    .marubatsu "はかせ　"

.loadtable "marubatsu_tbl\marubatsu_chs_38.tbl"
.orga (0x0D5EE4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ウルウル　"
    .marubatsu "ウルウル　"
  ; .marubatsu "ワクワク　"
    .marubatsu "ワクワク　"
  ; .marubatsu "ビクビク　"
    .marubatsu "ビクビク　"
  ; .marubatsu "ドキドキ　"
    .marubatsu "ドキドキ　"
  ; .marubatsu "１５０ページ　"
    .marubatsu "１５０ページ　"
  ; .marubatsu "１６０ページ　"
    .marubatsu "１６０ページ　"
  ; .marubatsu "１７０ページ　"
    .marubatsu "１７０ページ　"
  ; .marubatsu "１８０ページ　"
    .marubatsu "１８０ページ　"
  ; .marubatsu "たびだち　"
    .marubatsu "たびだち　"
  ; .marubatsu "つりきち　"
    .marubatsu "つりきち　"
  ; .marubatsu "うんめい　"
    .marubatsu "うんめい　"
  ; .marubatsu "ときめき　"
    .marubatsu "ときめき　"
.orga (0x0D5F80 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シエーヌ　"
    .marubatsu "シエーヌ　"
  ; .marubatsu "マリリン　"
    .marubatsu "マリリン　"
  ; .marubatsu "ヨッシー　"
    .marubatsu "ヨッシー　"
  ; .marubatsu "ケイト　"
    .marubatsu "ケイト　"
  ; .marubatsu "たびだち　"
    .marubatsu "たびだち　"
  ; .marubatsu "つりきち　"
    .marubatsu "つりきち　"
  ; .marubatsu "うんめい　"
    .marubatsu "うんめい　"
  ; .marubatsu "ときめき　"
    .marubatsu "ときめき　"
  ; .marubatsu "１５０ページ　"
    .marubatsu "１５０ページ　"
  ; .marubatsu "１６０ページ　"
    .marubatsu "１６０ページ　"
  ; .marubatsu "１７０ページ　"
    .marubatsu "１７０ページ　"
  ; .marubatsu "１８０ページ　"
    .marubatsu "１８０ページ　"

.loadtable "marubatsu_tbl\marubatsu_chs_39.tbl"
.orga (0x0D608E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ナイフでころした　"
    .marubatsu "ナイフでころした　"
  ; .marubatsu "カビンでころした　"
    .marubatsu "カビンでころした　"
  ; .marubatsu "ジュウでころした　"
    .marubatsu "ジュウでころした　"
  ; .marubatsu "ドクヤクでころした　"
    .marubatsu "ドクヤクでころした　"
  ; .marubatsu "５じにおこなった　"
    .marubatsu "５じにおこなった　"
  ; .marubatsu "６じにおこなった　"
    .marubatsu "６じにおこなった　"
  ; .marubatsu "７じにおこなった　"
    .marubatsu "７じにおこなった　"
  ; .marubatsu "８じにおこなった　"
    .marubatsu "８じにおこなった　"
  ; .marubatsu "ケイコをころした　"
    .marubatsu "ケイコをころした　"
  ; .marubatsu "カズミをころした　"
    .marubatsu "カズミをころした　"
  ; .marubatsu "ヨーコをころした　"
    .marubatsu "ヨーコをころした　"
  ; .marubatsu "ヒロコをころした　"
    .marubatsu "ヒロコをころした　"
.orga (0x0D612A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ケイコがころした　"
    .marubatsu "ケイコがころした　"
  ; .marubatsu "カズミがころした　"
    .marubatsu "カズミがころした　"
  ; .marubatsu "ヨーコがころした　"
    .marubatsu "ヨーコがころした　"
  ; .marubatsu "ヒロコがころした　"
    .marubatsu "ヒロコがころした　"
  ; .marubatsu "ケイコをころした　"
    .marubatsu "ケイコをころした　"
  ; .marubatsu "カズミをころした　"
    .marubatsu "カズミをころした　"
  ; .marubatsu "ヨーコをころした　"
    .marubatsu "ヨーコをころした　"
  ; .marubatsu "ヒロコをころした　"
    .marubatsu "ヒロコをころした　"
  ; .marubatsu "５じにおこなった　"
    .marubatsu "５じにおこなった　"
  ; .marubatsu "６じにおこなった　"
    .marubatsu "６じにおこなった　"
  ; .marubatsu "７じにおこなった　"
    .marubatsu "７じにおこなった　"
  ; .marubatsu "８じにおこなった　"
    .marubatsu "８じにおこなった　"

