.macro .marubatsu,str
    .area 13,0xAF
        .strn str
    .endarea
.endmacro

/* 每条文本须遵守以下规则：
   1.必须以全角空格，即“　”结尾。
   2.文本长度不超过13（含“　”）。
   3.文本长度至少为4（含“　”），否则用“　”填充。
*/

.loadtable "marubatsu_tbl\marubatsu_chs_00.tbl"
.orga (0x0D01B4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "せいふく　"
    .marubatsu "制服　　"
  ; .marubatsu "あかいふく　"
    .marubatsu "红衣服　"
  ; .marubatsu "あおいふく　"
    .marubatsu "蓝衣服　"
  ; .marubatsu "きいろいふく　"
    .marubatsu "黄衣服　"
  ; .marubatsu "３かまえ　"
    .marubatsu "３天前　"
  ; .marubatsu "４かまえ　"
    .marubatsu "４天前　"
  ; .marubatsu "５かまえ　"
    .marubatsu "５天前　"
  ; .marubatsu "６かまえ　"
    .marubatsu "６天前　"
.orga (0x0D0250 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シネマ　"
    .marubatsu "电影院　"
  ; .marubatsu "トロピカルランド　"
    .marubatsu "多罗碧加　"
  ; .marubatsu "こうえん　"
    .marubatsu "公园　　"
  ; .marubatsu "きょうかい　"
    .marubatsu "教会　　"
  ; .marubatsu "３かまえ　"
    .marubatsu "３天前　"
  ; .marubatsu "４かまえ　"
    .marubatsu "４天前　"
  ; .marubatsu "５かまえ　"
    .marubatsu "５天前　"
  ; .marubatsu "６かまえ　"
    .marubatsu "６天前　"

.loadtable "marubatsu_tbl\marubatsu_chs_01.tbl"
.orga (0x0D035E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "けいこ　"
    .marubatsu "惠子　　"
  ; .marubatsu "おくさん　"
    .marubatsu "夫人　　"
  ; .marubatsu "ヒゲありのだんせい　"
    .marubatsu "胡子男　"
  ; .marubatsu "ヒゲなしのだんせい　"
    .marubatsu "没胡子男　"
  ; .marubatsu "１ごうしつ　"
    .marubatsu "１号室　"
  ; .marubatsu "２ごうしつ　"
    .marubatsu "２号室　"
  ; .marubatsu "３ごうしつ　"
    .marubatsu "３号室　"
  ; .marubatsu "４ごうしつ　"
    .marubatsu "４号室　"
.orga (0x0D03FA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ピエトロしんぷ　"
    .marubatsu "彼得罗神父　"
  ; .marubatsu "トマスしんぷ　"
    .marubatsu "托马斯神父　"
  ; .marubatsu "ポールしんぷ　"
    .marubatsu "保罗神父　"
  ; .marubatsu "ジョンしんぷ　"
    .marubatsu "约翰神父　"
  ; .marubatsu "１ごうしつ　"
    .marubatsu "１号室　"
  ; .marubatsu "２ごうしつ　"
    .marubatsu "２号室　"
  ; .marubatsu "３ごうしつ　"
    .marubatsu "３号室　"
  ; .marubatsu "４ごうしつ　"
    .marubatsu "４号室　"

.loadtable "marubatsu_tbl\marubatsu_chs_02.tbl"
.orga (0x0D0508 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１项　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２项　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３项　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４项　"
  ; .marubatsu "でんごんをかく　"
    .marubatsu "写留言　"
  ; .marubatsu "ほんをかえす　"
    .marubatsu "还书　　"
  ; .marubatsu "チケットをかう　"
    .marubatsu "买票　　"
  ; .marubatsu "ケーキをかう　"
    .marubatsu "买蛋糕　"
.orga (0x0D05A4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "としょかん　"
    .marubatsu "图书馆　"
  ; .marubatsu "べいかえき　"
    .marubatsu "米花站　"
  ; .marubatsu "カフエ　ロイヤル　"
    .marubatsu "罗伊尔　"
  ; .marubatsu "トロピカルランド　"
    .marubatsu "多罗碧加　"
  ; .marubatsu "でんごんをかく　"
    .marubatsu "写留言　"
  ; .marubatsu "ほんをかえす　"
    .marubatsu "还书　　"
  ; .marubatsu "チケットをかう　"
    .marubatsu "买票　　"
  ; .marubatsu "ケーキをかう　"
    .marubatsu "买蛋糕　"

.loadtable "marubatsu_tbl\marubatsu_chs_03.tbl"
.orga (0x0D06B2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "２２ばん　"
    .marubatsu "２２号　"
  ; .marubatsu "２６ばん　"
    .marubatsu "２６号　"
  ; .marubatsu "４３ばん　"
    .marubatsu "４３号　"
  ; .marubatsu "４７ばん　"
    .marubatsu "４７号　"
  ; .marubatsu "スペード　"
    .marubatsu "黑桃　　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "方片　　"
  ; .marubatsu "ハート　"
    .marubatsu "红桃　　"
  ; .marubatsu "クラブ　"
    .marubatsu "梅花　　"
.orga (0x0D074E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "らん　　"
    .marubatsu "兰　　　"
  ; .marubatsu "けいこ　"
    .marubatsu "惠子　　"
  ; .marubatsu "ポールしんぷ　"
    .marubatsu "保罗神父　"
  ; .marubatsu "りょうこ　"
    .marubatsu "良子　　"
  ; .marubatsu "スペード　"
    .marubatsu "黑桃　　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "方片　　"
  ; .marubatsu "ハート　"
    .marubatsu "红桃　　"
  ; .marubatsu "クラブ　"
    .marubatsu "梅花　　"

.loadtable "marubatsu_tbl\marubatsu_chs_04.tbl"
.orga (0x0D085C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヒロイン　"
    .marubatsu "女主角　"
  ; .marubatsu "ライバル　"
    .marubatsu "情敌　　"
  ; .marubatsu "かれし　"
    .marubatsu "男友　　"
  ; .marubatsu "ようぎしゃ　"
    .marubatsu "嫌疑人　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１出场　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２出场　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３出场　"
  ; .marubatsu "ぜんぶ　"
    .marubatsu "全部出场　"
.orga (0x0D08F8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "洋子　　"
  ; .marubatsu "きょうこ　"
    .marubatsu "京子　　"
  ; .marubatsu "ようじ　"
    .marubatsu "洋二　　"
  ; .marubatsu "としき　"
    .marubatsu "俊树　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１出场　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２出场　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３出场　"
  ; .marubatsu "ぜんぶ　"
    .marubatsu "全部出场　"

.loadtable "marubatsu_tbl\marubatsu_chs_05.tbl"
.orga (0x0D0A06 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "４じ３０にでた　"
    .marubatsu "４点３０　"
  ; .marubatsu "５じにでた　"
    .marubatsu "５点　　"
  ; .marubatsu "５じ３０にでた　"
    .marubatsu "５点３０　"
  ; .marubatsu "６じにでた　"
    .marubatsu "６点　　"
  ; .marubatsu "２じ３０にでた　"
    .marubatsu "２点３０　"
  ; .marubatsu "３じにでた　"
    .marubatsu "３点　　"
  ; .marubatsu "３じ３０にでた　"
    .marubatsu "３点３０　"
  ; .marubatsu "４じにでた　"
    .marubatsu "４点　　"
.orga (0x0D0AA2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "洋子　　"
  ; .marubatsu "ようじ　"
    .marubatsu "洋二　　"
  ; .marubatsu "としき　"
    .marubatsu "俊树　　"
  ; .marubatsu "カントク　"
    .marubatsu "导演　　"
  ; .marubatsu "２じ３０にでた　"
    .marubatsu "２点３０　"
  ; .marubatsu "３じにでた　"
    .marubatsu "３点　　"
  ; .marubatsu "３じ３０にでた　"
    .marubatsu "３点３０　"
  ; .marubatsu "４じにでた　"
    .marubatsu "４点　　"

.loadtable "marubatsu_tbl\marubatsu_chs_06.tbl"
.orga (0x0D0BB0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シネマ　"
    .marubatsu "电影院　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
  ; .marubatsu "デパート　"
    .marubatsu "百货大楼　"
  ; .marubatsu "がっこう　"
    .marubatsu "学校　　"
  ; .marubatsu "こどもばんぐみ　"
    .marubatsu "儿童节目　"
  ; .marubatsu "グルメばんぐみ　"
    .marubatsu "美食节目　"
  ; .marubatsu "しゅざい　"
    .marubatsu "采访　　"
  ; .marubatsu "あいさつ　"
    .marubatsu "见面会　"
.orga (0x0D0C4C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "洋子　　"
  ; .marubatsu "ようじ　"
    .marubatsu "洋二　　"
  ; .marubatsu "としき　"
    .marubatsu "俊树　　"
  ; .marubatsu "カントク　"
    .marubatsu "导演　　"
  ; .marubatsu "こどもばんぐみ　"
    .marubatsu "儿童节目　"
  ; .marubatsu "グルメばんぐみ　"
    .marubatsu "美食节目　"
  ; .marubatsu "しゅざい　"
    .marubatsu "采访　　"
  ; .marubatsu "あいさつ　"
    .marubatsu "见面会　"

.loadtable "marubatsu_tbl\marubatsu_chs_07.tbl"
.orga (0x0D0D5A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ねんまえ　"
    .marubatsu "１年前　"
  ; .marubatsu "２ねんまえ　"
    .marubatsu "２年前　"
  ; .marubatsu "３ねんまえ　"
    .marubatsu "３年前　"
  ; .marubatsu "４ねんまえ　"
    .marubatsu "４年前　"
  ; .marubatsu "しごとをとられた　"
    .marubatsu "工作被抢　"
  ; .marubatsu "おかねをとられた　"
    .marubatsu "钱被骗　"
  ; .marubatsu "こいびとがじさつ　"
    .marubatsu "恋人自杀　"
  ; .marubatsu "きょうこにふられた　"
    .marubatsu "被甩了　"
.orga (0x0D0DF6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "洋子　　"
  ; .marubatsu "ようじ　"
    .marubatsu "洋二　　"
  ; .marubatsu "としき　"
    .marubatsu "俊树　　"
  ; .marubatsu "カントク　"
    .marubatsu "导演　　"
  ; .marubatsu "しごとをとられた　"
    .marubatsu "工作被抢　"
  ; .marubatsu "おかねをとられた　"
    .marubatsu "钱被骗　"
  ; .marubatsu "こいびとがじさつ　"
    .marubatsu "恋人自杀　"
  ; .marubatsu "きょうこにふられた　"
    .marubatsu "被甩了　"

.loadtable "marubatsu_tbl\marubatsu_chs_08.tbl"
.orga (0x0D0F04 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "むじのカサ　"
    .marubatsu "单色伞　"
  ; .marubatsu "みずたまのカサ　"
    .marubatsu "雨点伞　"
  ; .marubatsu "チエックのカサ　"
    .marubatsu "格子伞　"
  ; .marubatsu "たてじまのカサ　"
    .marubatsu "条纹伞　"
  ; .marubatsu "ビニールぶくろ　"
    .marubatsu "塑料袋　"
  ; .marubatsu "カメラ　"
    .marubatsu "相机　　"
  ; .marubatsu "アイスボックス　"
    .marubatsu "冰块盒　"
  ; .marubatsu "リュック　"
    .marubatsu "帆布背包　"
.orga (0x0D0FA0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ヨーコ　"
    .marubatsu "洋子　　"
  ; .marubatsu "ようじ　"
    .marubatsu "洋二　　"
  ; .marubatsu "としき　"
    .marubatsu "俊树　　"
  ; .marubatsu "カントク　"
    .marubatsu "导演　　"
  ; .marubatsu "ビニールぶくろ　"
    .marubatsu "塑料袋　"
  ; .marubatsu "カメラ　"
    .marubatsu "相机　　"
  ; .marubatsu "アイスボックス　"
    .marubatsu "冰块盒　"
  ; .marubatsu "リュック　"
    .marubatsu "帆布背包　"

.loadtable "marubatsu_tbl\marubatsu_chs_09.tbl"
.orga (0x0D10AE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アメリカしゃ　"
    .marubatsu "美国车　"
  ; .marubatsu "ニホンしゃ　"
    .marubatsu "日本车　"
  ; .marubatsu "ドイツしゃ　"
    .marubatsu "德国车　"
  ; .marubatsu "イギリスしゃ　"
    .marubatsu "英国车　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
  ; .marubatsu "デパート　"
    .marubatsu "百货大楼　"
  ; .marubatsu "こうえん　"
    .marubatsu "公园　　"
  ; .marubatsu "シネマ　"
    .marubatsu "电影院　"
  ; .marubatsu "ナイフ　"
    .marubatsu "小刀　　"
  ; .marubatsu "きり　　"
    .marubatsu "雾　　　"
  ; .marubatsu "なぞ　　"
    .marubatsu "谜　　　"
  ; .marubatsu "よる　　"
    .marubatsu "夜　　　"
.orga (0x0D114A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しんいち　"
    .marubatsu "新一　　"
  ; .marubatsu "へいじ　"
    .marubatsu "平次　　"
  ; .marubatsu "こごろう　"
    .marubatsu "小五郎　"
  ; .marubatsu "ジャック　"
    .marubatsu "杰克　　"
  ; .marubatsu "ナイフ　"
    .marubatsu "小刀　　"
  ; .marubatsu "きり　　"
    .marubatsu "雾　　　"
  ; .marubatsu "なぞ　　"
    .marubatsu "谜　　　"
  ; .marubatsu "よる　　"
    .marubatsu "夜　　　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
  ; .marubatsu "デパート　"
    .marubatsu "百货大楼　"
  ; .marubatsu "こうえん　"
    .marubatsu "公园　　"
  ; .marubatsu "シネマ　"
    .marubatsu "电影院　"

.loadtable "marubatsu_tbl\marubatsu_chs_0A.tbl"
.orga (0x0D1258 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "せんさいのつれご　"
    .marubatsu "前妻带的　"
  ; .marubatsu "ごさいのつれご　"
    .marubatsu "后妻带的　"
  ; .marubatsu "せんさいのじっし　"
    .marubatsu "前妻生的　"
  ; .marubatsu "ごさいのじっし　"
    .marubatsu "后妻生的　"
  ; .marubatsu "いしゃ　"
    .marubatsu "医生　　"
  ; .marubatsu "じょせい　"
    .marubatsu "女性　　"
  ; .marubatsu "きぞく　"
    .marubatsu "贵族　　"
  ; .marubatsu "けいかん　"
    .marubatsu "警官　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "老大　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "老二　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "老三　　"
  ; .marubatsu "すえっこ　"
    .marubatsu "老四　　"
.orga (0x0D12F4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しゃく　"
    .marubatsu "爵　　　"
  ; .marubatsu "りん　　"
    .marubatsu "伦　　　"
  ; .marubatsu "とし　　"
    .marubatsu "利　　　"
  ; .marubatsu "あつし　"
    .marubatsu "敦　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "老大　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "老二　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "老三　　"
  ; .marubatsu "すえっこ　"
    .marubatsu "老四　　"
  ; .marubatsu "いしゃ　"
    .marubatsu "医生　　"
  ; .marubatsu "じょせい　"
    .marubatsu "女性　　"
  ; .marubatsu "きぞく　"
    .marubatsu "贵族　　"
  ; .marubatsu "けいかん　"
    .marubatsu "警官　　"

.loadtable "marubatsu_tbl\marubatsu_chs_0B.tbl"
.orga (0x0D1402 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "やしき　"
    .marubatsu "宅邸　　"
  ; .marubatsu "べってい　"
    .marubatsu "别墅　　"
  ; .marubatsu "かぶけん　"
    .marubatsu "股票　　"
  ; .marubatsu "コレクション　"
    .marubatsu "收藏　　"
  ; .marubatsu "２０おくえん　"
    .marubatsu "２０亿　"
  ; .marubatsu "１５おくえん　"
    .marubatsu "１５亿　"
  ; .marubatsu "１３おくえん　"
    .marubatsu "１３亿　"
  ; .marubatsu "１２おくえん　"
    .marubatsu "１２亿　"
.orga (0x0D149E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しゃく　"
    .marubatsu "爵　　　"
  ; .marubatsu "りん　　"
    .marubatsu "伦　　　"
  ; .marubatsu "とし　　"
    .marubatsu "利　　　"
  ; .marubatsu "あつし　"
    .marubatsu "敦　　　"
  ; .marubatsu "２０おくえん　"
    .marubatsu "２０亿　"
  ; .marubatsu "１５おくえん　"
    .marubatsu "１５亿　"
  ; .marubatsu "１３おくえん　"
    .marubatsu "１３亿　"
  ; .marubatsu "１２おくえん　"
    .marubatsu "１２亿　"

.loadtable "marubatsu_tbl\marubatsu_chs_0C.tbl"
.orga (0x0D15AC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アーミーナイフ　"
    .marubatsu "军刀　　"
  ; .marubatsu "くだものナイフ　"
    .marubatsu "水果刀　"
  ; .marubatsu "ちょうこくとう　"
    .marubatsu "雕刻刀　"
  ; .marubatsu "もてない　"
    .marubatsu "没拿东西　"
  ; .marubatsu "あえない　"
    .marubatsu "没见到　"
  ; .marubatsu "どなられた　"
    .marubatsu "大叫　　"
  ; .marubatsu "わらった　"
    .marubatsu "笑了　　"
  ; .marubatsu "コーヒーをとりに　"
    .marubatsu "去拿咖啡　"
  ; .marubatsu "１じ　　"
    .marubatsu "１点　　"
  ; .marubatsu "２じ　　"
    .marubatsu "２点　　"
  ; .marubatsu "３じ　　"
    .marubatsu "３点　　"
  ; .marubatsu "４じ　　"
    .marubatsu "４点　　"
.orga (0x0D1648 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しゃく　"
    .marubatsu "爵　　　"
  ; .marubatsu "りん　　"
    .marubatsu "伦　　　"
  ; .marubatsu "とし　　"
    .marubatsu "利　　　"
  ; .marubatsu "あつし　"
    .marubatsu "敦　　　"
  ; .marubatsu "１じ　　"
    .marubatsu "１点　　"
  ; .marubatsu "２じ　　"
    .marubatsu "２点　　"
  ; .marubatsu "３じ　　"
    .marubatsu "３点　　"
  ; .marubatsu "４じ　　"
    .marubatsu "４点　　"
  ; .marubatsu "あえない　"
    .marubatsu "没见到　"
  ; .marubatsu "どなられた　"
    .marubatsu "大叫　　"
  ; .marubatsu "わらった　"
    .marubatsu "笑了　　"
  ; .marubatsu "コーヒーをとりに　"
    .marubatsu "去拿咖啡　"

.loadtable "marubatsu_tbl\marubatsu_chs_0D.tbl"
.orga (0x0D1756 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "３かまえ　"
    .marubatsu "３天前　"
  ; .marubatsu "おととい　"
    .marubatsu "前天　　"
  ; .marubatsu "ゆうべ　"
    .marubatsu "昨晚　　"
  ; .marubatsu "こんや　"
    .marubatsu "今晚　　"
  ; .marubatsu "はくぶつかん　"
    .marubatsu "博物馆　"
  ; .marubatsu "びじゅつかん　"
    .marubatsu "美术馆　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
  ; .marubatsu "きょうかい　"
    .marubatsu "教会　　"
.orga (0x0D17F2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "サフアイヤ　"
    .marubatsu "蓝宝石　"
  ; .marubatsu "エメラルド　"
    .marubatsu "绿宝石　"
  ; .marubatsu "オパール　"
    .marubatsu "蛋白石　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "钻石　　"
  ; .marubatsu "はくぶつかん　"
    .marubatsu "博物馆　"
  ; .marubatsu "びじゅつかん　"
    .marubatsu "美术馆　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
  ; .marubatsu "きょうかい　"
    .marubatsu "教会　　"

.loadtable "marubatsu_tbl\marubatsu_chs_0E.tbl"
.orga (0x0D1900 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "だい１てんじしつ　"
    .marubatsu "第１展厅　"
  ; .marubatsu "だい２てんじしつ　"
    .marubatsu "第２展厅　"
  ; .marubatsu "だい３てんじしつ　"
    .marubatsu "第３展厅　"
  ; .marubatsu "だい４てんじしつ　"
    .marubatsu "第４展厅　"
  ; .marubatsu "かいが　"
    .marubatsu "绘画　　"
  ; .marubatsu "ちょうこく　"
    .marubatsu "雕刻　　"
  ; .marubatsu "げんだいアート　"
    .marubatsu "现代艺术　"
  ; .marubatsu "ほうしょくひん　"
    .marubatsu "珠宝首饰　"
  ; .marubatsu "いりぐちにちかい　"
    .marubatsu "离入口近　"
  ; .marubatsu "でぐちひとつ　"
    .marubatsu "一个出口　"
  ; .marubatsu "とびら３つ　"
    .marubatsu "３扇门　"
  ; .marubatsu "ひじょうぐちあり　"
    .marubatsu "紧急出口　"
.orga (0x0D199C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こごろう　"
    .marubatsu "小五郎　"
  ; .marubatsu "めぐれ　"
    .marubatsu "目暮　　"
  ; .marubatsu "なかもり　"
    .marubatsu "中森　　"
  ; .marubatsu "しらとり　"
    .marubatsu "白鸟　　"
  ; .marubatsu "いりぐちにちかい　"
    .marubatsu "离入口近　"
  ; .marubatsu "でぐちひとつ　"
    .marubatsu "一个入口　"
  ; .marubatsu "とびら３つ　"
    .marubatsu "３个入口　"
  ; .marubatsu "ひじょうぐちあり　"
    .marubatsu "紧急出口　"
  ; .marubatsu "かいが　"
    .marubatsu "绘画　　"
  ; .marubatsu "ちょうこく　"
    .marubatsu "雕刻　　"
  ; .marubatsu "げんだいアート　"
    .marubatsu "现代艺术　"
  ; .marubatsu "ほうしょくひん　"
    .marubatsu "珠宝首饰　"

.loadtable "marubatsu_tbl\marubatsu_chs_0F.tbl"
.orga (0x0D1AAA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "６じ００にでた　"
    .marubatsu "出６点００　"
  ; .marubatsu "６じ０５にでた　"
    .marubatsu "出６点０５　"
  ; .marubatsu "６じ１０にでた　"
    .marubatsu "出６点１０　"
  ; .marubatsu "６じ１５にでた　"
    .marubatsu "出６点１５　"
  ; .marubatsu "５じ４５にはいった　"
    .marubatsu "进５点４５　"
  ; .marubatsu "５じ５５にはいった　"
    .marubatsu "进５点５５　"
  ; .marubatsu "６じ０５にはいった　"
    .marubatsu "进６点０５　"
  ; .marubatsu "６じ１０にはいった　"
    .marubatsu "进６点１０　"
.orga (0x0D1B46 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こごろう　"
    .marubatsu "小五郎　"
  ; .marubatsu "めぐれ　"
    .marubatsu "目暮　　"
  ; .marubatsu "なかもり　"
    .marubatsu "中森　　"
  ; .marubatsu "おおくぼ　"
    .marubatsu "大久保　"
  ; .marubatsu "５じ４５にはいった　"
    .marubatsu "进５点４５　"
  ; .marubatsu "５じ５５にはいった　"
    .marubatsu "进５点５５　"
  ; .marubatsu "６じ０５にはいった　"
    .marubatsu "进６点０５　"
  ; .marubatsu "６じ１０にはいった　"
    .marubatsu "进６点１０　"

.loadtable "marubatsu_tbl\marubatsu_chs_10.tbl"
.orga (0x0D1C54 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あか　　"
    .marubatsu "红　　　"
  ; .marubatsu "あお　　"
    .marubatsu "蓝　　　"
  ; .marubatsu "きいろ　"
    .marubatsu "黄　　　"
  ; .marubatsu "むしょく　"
    .marubatsu "透明　　"
  ; .marubatsu "みぎ　　"
    .marubatsu "右　　　"
  ; .marubatsu "ひだり　"
    .marubatsu "左　　　"
  ; .marubatsu "おく　　"
    .marubatsu "深处　　"
  ; .marubatsu "ちゅうおう　"
    .marubatsu "中央　　"
.orga (0x0D1CF0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かわいいあおバラ　"
    .marubatsu "萌蓝玫瑰　"
  ; .marubatsu "あくまのなみだ　"
    .marubatsu "泪眼恶魔　"
  ; .marubatsu "ソロモンのカギ　"
    .marubatsu "所罗门钥匙　"
  ; .marubatsu "ヴイーナスのひとみ　"
    .marubatsu "维纳斯之眼　"
  ; .marubatsu "みぎ　　"
    .marubatsu "右　　　"
  ; .marubatsu "ひだり　"
    .marubatsu "左　　　"
  ; .marubatsu "おく　　"
    .marubatsu "深处　　"
  ; .marubatsu "ちゅうおう　"
    .marubatsu "中央　　"

.loadtable "marubatsu_tbl\marubatsu_chs_11.tbl"
.orga (0x0D1DFE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１もじめ　"
    .marubatsu "第１个字　"
  ; .marubatsu "２もじめ　"
    .marubatsu "第２个字　"
  ; .marubatsu "３もじめ　"
    .marubatsu "第３个字　"
  ; .marubatsu "４もじめ　"
    .marubatsu "第４个字　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１个读　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２个读　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３个读　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４个读　"
.orga (0x0D1E9A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かわいいあおバラ　"
    .marubatsu "萌蓝玫瑰　"
  ; .marubatsu "あくまのなみだ　"
    .marubatsu "泪眼恶魔　"
  ; .marubatsu "ソロモンのカギ　"
    .marubatsu "所罗门钥匙　"
  ; .marubatsu "ヴイーナスのひとみ　"
    .marubatsu "维纳斯之眼　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１个读　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２个读　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３个读　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４个读　"

.loadtable "marubatsu_tbl\marubatsu_chs_12.tbl"
.orga (0x0D1FA8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ベンチのした　"
    .marubatsu "长椅下面　"
  ; .marubatsu "ごみばこのちかく　"
    .marubatsu "垃圾桶旁　"
  ; .marubatsu "みずのみば　"
    .marubatsu "饮水处　"
  ; .marubatsu "きのした　"
    .marubatsu "树下　　"
  ; .marubatsu "あか　　"
    .marubatsu "红　　　"
  ; .marubatsu "あお　　"
    .marubatsu "蓝　　　"
  ; .marubatsu "きいろ　"
    .marubatsu "黄　　　"
  ; .marubatsu "みどり　"
    .marubatsu "绿　　　"
.orga (0x0D2044 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あゆみ　"
    .marubatsu "步美　　"
  ; .marubatsu "げんた　"
    .marubatsu "元太　　"
  ; .marubatsu "みつひこ　"
    .marubatsu "光彦　　"
  ; .marubatsu "コナン　"
    .marubatsu "柯南　　"
  ; .marubatsu "あか　　"
    .marubatsu "红　　　"
  ; .marubatsu "あお　　"
    .marubatsu "蓝　　　"
  ; .marubatsu "きいろ　"
    .marubatsu "黄　　　"
  ; .marubatsu "みどり　"
    .marubatsu "绿　　　"

.loadtable "marubatsu_tbl\marubatsu_chs_13.tbl"
.orga (0x0D2152 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "マリブのかいぞく　"
    .marubatsu "海盗船　"
  ; .marubatsu "カップ　"
    .marubatsu "旋转茶杯　"
  ; .marubatsu "コースター　"
    .marubatsu "云霄飞车　"
  ; .marubatsu "かんらんしゃ　"
    .marubatsu "摩天轮　"
  ; .marubatsu "くちのなか　"
    .marubatsu "口中　　"
  ; .marubatsu "さらのした　"
    .marubatsu "盘子下面　"
  ; .marubatsu "ランタンのした　"
    .marubatsu "壁灯下面　"
  ; .marubatsu "けんばいきのよこ　"
    .marubatsu "售票机旁　"
.orga (0x0D21EE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルビー　"
    .marubatsu "红宝石　"
  ; .marubatsu "サフアイヤ　"
    .marubatsu "蓝宝石　"
  ; .marubatsu "エメラルド　"
    .marubatsu "绿宝石　"
  ; .marubatsu "アメジスト　"
    .marubatsu "紫水晶　"
  ; .marubatsu "くちのなか　"
    .marubatsu "口中　　"
  ; .marubatsu "さらのした　"
    .marubatsu "盘子下面　"
  ; .marubatsu "ランタンのした　"
    .marubatsu "壁灯下面　"
  ; .marubatsu "けんばいきのよこ　"
    .marubatsu "售票机旁　"

.loadtable "marubatsu_tbl\marubatsu_chs_14.tbl"
.orga (0x0D22FC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スペード　"
    .marubatsu "黑桃　　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "方片　　"
  ; .marubatsu "ハート　"
    .marubatsu "红桃　　"
  ; .marubatsu "クラブ　"
    .marubatsu "梅花　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　"
  ; .marubatsu "みぎ　　"
    .marubatsu "右　　　"
  ; .marubatsu "ひだり　"
    .marubatsu "左　　　"
  ; .marubatsu "うえ　　"
    .marubatsu "上　　　"
  ; .marubatsu "した　　"
    .marubatsu "下　　　"
.orga (0x0D2398 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルビー　"
    .marubatsu "红宝石　"
  ; .marubatsu "サフアイヤ　"
    .marubatsu "蓝宝石　"
  ; .marubatsu "エメラルド　"
    .marubatsu "绿宝石　"
  ; .marubatsu "アメジスト　"
    .marubatsu "紫水晶　"
  ; .marubatsu "みぎ　　"
    .marubatsu "右　　　"
  ; .marubatsu "ひだり　"
    .marubatsu "左　　　"
  ; .marubatsu "うえ　　"
    .marubatsu "上　　　"
  ; .marubatsu "した　　"
    .marubatsu "下　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　"

.loadtable "marubatsu_tbl\marubatsu_chs_15.tbl"
.orga (0x0D24A6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "おす　　"
    .marubatsu "推　　　"
  ; .marubatsu "ひく　　"
    .marubatsu "拉　　　"
  ; .marubatsu "はずす　"
    .marubatsu "取下　　"
  ; .marubatsu "さかさま　"
    .marubatsu "颠倒　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　"
.orga (0x0D2542 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ジイ　　"
    .marubatsu "g　　　"
  ; .marubatsu "アイ　　"
    .marubatsu "i　　　"
  ; .marubatsu "エムエー　"
    .marubatsu "Ma　　"
  ; .marubatsu "シー　　"
    .marubatsu "c　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　"

.loadtable "marubatsu_tbl\marubatsu_chs_16.tbl"
.orga (0x0D2650 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルビー　"
    .marubatsu "红宝石　"
  ; .marubatsu "サフアイヤ　"
    .marubatsu "蓝宝石　"
  ; .marubatsu "エメラルド　"
    .marubatsu "绿宝石　"
  ; .marubatsu "アメジスト　"
    .marubatsu "紫水晶　"
  ; .marubatsu "よこ１　"
    .marubatsu "横向１　"
  ; .marubatsu "よこ２　"
    .marubatsu "横向２　"
  ; .marubatsu "よこ３　"
    .marubatsu "横向３　"
  ; .marubatsu "よこ４　"
    .marubatsu "横向４　"
  ; .marubatsu "たに１　"
    .marubatsu "纵向１　"
  ; .marubatsu "たに２　"
    .marubatsu "纵向２　"
  ; .marubatsu "たに３　"
    .marubatsu "纵向３　"
  ; .marubatsu "たに４　"
    .marubatsu "纵向４　"
.orga (0x0D26EC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スペード　"
    .marubatsu "黑桃　　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "方片　　"
  ; .marubatsu "ハート　"
    .marubatsu "红桃　　"
  ; .marubatsu "クラブ　"
    .marubatsu "梅花　　"
  ; .marubatsu "たに１　"
    .marubatsu "纵向１　"
  ; .marubatsu "たに２　"
    .marubatsu "纵向２　"
  ; .marubatsu "たに３　"
    .marubatsu "纵向３　"
  ; .marubatsu "たに４　"
    .marubatsu "纵向４　"
  ; .marubatsu "よこ１　"
    .marubatsu "横向１　"
  ; .marubatsu "よこ２　"
    .marubatsu "横向２　"
  ; .marubatsu "よこ３　"
    .marubatsu "横向３　"
  ; .marubatsu "よこ４　"
    .marubatsu "横向４　"

.loadtable "marubatsu_tbl\marubatsu_chs_17.tbl"
.orga (0x0D27FA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スペード　"
    .marubatsu "黑桃　　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "方片　　"
  ; .marubatsu "ハート　"
    .marubatsu "红桃　　"
  ; .marubatsu "クラブ　"
    .marubatsu "梅花　　"
  ; .marubatsu "１かいめ　"
    .marubatsu "第１轮　"
  ; .marubatsu "２かいめ　"
    .marubatsu "第２轮　"
  ; .marubatsu "３かいめ　"
    .marubatsu "第３轮　"
  ; .marubatsu "４かいめ　"
    .marubatsu "第４轮　"
  ; .marubatsu "あとシー　"
    .marubatsu "后C　　"
  ; .marubatsu "あとアイ　"
    .marubatsu "后I　　"
  ; .marubatsu "あとエイ　"
    .marubatsu "后A　　"
  ; .marubatsu "あとエヌ　"
    .marubatsu "后N　　"
.orga (0x0D2896 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "まえエム　"
    .marubatsu "先M　　"
  ; .marubatsu "まえエイ　"
    .marubatsu "先A　　"
  ; .marubatsu "まえジー　"
    .marubatsu "先G　　"
  ; .marubatsu "まえアイ　"
    .marubatsu "先I　　"
  ; .marubatsu "あとシー　"
    .marubatsu "后C　　"
  ; .marubatsu "あとアイ　"
    .marubatsu "后I　　"
  ; .marubatsu "あとエイ　"
    .marubatsu "后A　　"
  ; .marubatsu "あとエヌ　"
    .marubatsu "后N　　"
  ; .marubatsu "１かいめ　"
    .marubatsu "第１轮　"
  ; .marubatsu "２かいめ　"
    .marubatsu "第２轮　"
  ; .marubatsu "３かいめ　"
    .marubatsu "第３轮　"
  ; .marubatsu "４かいめ　"
    .marubatsu "第４轮　"

.loadtable "marubatsu_tbl\marubatsu_chs_18.tbl"
.orga (0x0D29A4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "みぎ　　"
    .marubatsu "右　　　"
  ; .marubatsu "ひだり　"
    .marubatsu "左　　　"
  ; .marubatsu "うえ　　"
    .marubatsu "上　　　"
  ; .marubatsu "した　　"
    .marubatsu "下　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　"
.orga (0x0D2A40 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "２　　　"
    .marubatsu "２　　　"
  ; .marubatsu "０　　　"
    .marubatsu "０　　　"
  ; .marubatsu "せい　　"
    .marubatsu "世　　　"
  ; .marubatsu "き　　　"
    .marubatsu "纪　　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　"

.loadtable "marubatsu_tbl\marubatsu_chs_19.tbl"
.orga (0x0D2B4E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "みどり　"
    .marubatsu "绿色　　"
  ; .marubatsu "ウラシマ　"
    .marubatsu "浦岛　　"
  ; .marubatsu "ウサギ　"
    .marubatsu "兔子　　"
  ; .marubatsu "ロケット　"
    .marubatsu "火箭　　"
  ; .marubatsu "げんた　"
    .marubatsu "元太　　"
  ; .marubatsu "あゆみ　"
    .marubatsu "步美　　"
  ; .marubatsu "コナン　"
    .marubatsu "柯南　　"
  ; .marubatsu "みつひこ　"
    .marubatsu "光彦　　"
.orga (0x0D2BEA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "コイ　　"
    .marubatsu "鲤鱼　　"
  ; .marubatsu "カメ　　"
    .marubatsu "乌龟　　"
  ; .marubatsu "うさぎ　"
    .marubatsu "兔子　　"
  ; .marubatsu "ハト　　"
    .marubatsu "鸽子　　"
  ; .marubatsu "げんた　"
    .marubatsu "元太　　"
  ; .marubatsu "あゆみ　"
    .marubatsu "步美　　"
  ; .marubatsu "コナン　"
    .marubatsu "柯南　　"
  ; .marubatsu "みつひこ　"
    .marubatsu "光彦　　"

.loadtable "marubatsu_tbl\marubatsu_chs_1A.tbl"
.orga (0x0D2CF8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１只　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２只　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３只　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４只　"
  ; .marubatsu "じむしょ　"
    .marubatsu "事务所　"
  ; .marubatsu "デパート　"
    .marubatsu "百货大楼　"
  ; .marubatsu "けいさつ　"
    .marubatsu "警察局　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"
.orga (0x0D2D94 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シロ　　"
    .marubatsu "白色　　"
  ; .marubatsu "クロ　　"
    .marubatsu "黑色　　"
  ; .marubatsu "トラ　　"
    .marubatsu "虎斑　　"
  ; .marubatsu "ミケ　　"
    .marubatsu "三色　　"
  ; .marubatsu "じむしょ　"
    .marubatsu "事务所　"
  ; .marubatsu "デパート　"
    .marubatsu "百货大楼　"
  ; .marubatsu "けいさつ　"
    .marubatsu "警察局　"
  ; .marubatsu "タワー　"
    .marubatsu "东都塔　"

.loadtable "marubatsu_tbl\marubatsu_chs_1B.tbl"
.orga (0x0D2EA2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "がくしゃ　"
    .marubatsu "学者　　"
  ; .marubatsu "しょき　"
    .marubatsu "书记　　"
  ; .marubatsu "バイヤー　"
    .marubatsu "买家　　"
  ; .marubatsu "えいぞう　"
    .marubatsu "摄影师　"
  ; .marubatsu "シングル　"
    .marubatsu "干练西服　"
  ; .marubatsu "ダブル　　"
    .marubatsu "华丽西服　"
  ; .marubatsu "タイなし　"
    .marubatsu "休闲服　"
  ; .marubatsu "チャイナ　"
    .marubatsu "旗袍　　"
  ; .marubatsu "かいつけ　"
    .marubatsu "购买　　"
  ; .marubatsu "さつえい　"
    .marubatsu "拍照　　"
  ; .marubatsu "きぞう　"
    .marubatsu "赠送　　"
  ; .marubatsu "きょうみ　"
    .marubatsu "兴趣　　"
.orga (0x0D2F3E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "いぬい　"
    .marubatsu "乾　　　"
  ; .marubatsu "セルゲイ　"
    .marubatsu "谢尔盖　"
  ; .marubatsu "さがわ　"
    .marubatsu "寒川　　"
  ; .marubatsu "せいらん　"
    .marubatsu "青兰　　"
  ; .marubatsu "かいつけ　"
    .marubatsu "购买　　"
  ; .marubatsu "さつえい　"
    .marubatsu "拍照　　"
  ; .marubatsu "きぞう　"
    .marubatsu "赠送　　"
  ; .marubatsu "きょうみ　"
    .marubatsu "兴趣　　"
  ; .marubatsu "シングル　"
    .marubatsu "干练西服　"
  ; .marubatsu "ダブル　　"
    .marubatsu "华丽西服　"
  ; .marubatsu "タイなし　"
    .marubatsu "休闲服　"
  ; .marubatsu "チャイナ　"
    .marubatsu "旗袍　　"

.loadtable "marubatsu_tbl\marubatsu_chs_1C.tbl"
.orga (0x0D304C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "スミスアンドウエッソン　"
    .marubatsu "史密斯＆威森　"
  ; .marubatsu "エム８９ビー　"
    .marubatsu "Ｍ８９Ｂ　"
  ; .marubatsu "ワルサーピー３８　"
    .marubatsu "瓦尔特３８　"
  ; .marubatsu "アダムス　"
    .marubatsu "亚当斯　"
  ; .marubatsu "イギリスせい　"
    .marubatsu "英国制　"
  ; .marubatsu "イタリアせい　"
    .marubatsu "意大利制　"
  ; .marubatsu "ドイツせい　"
    .marubatsu "德国制　"
  ; .marubatsu "アメリカせい　"
    .marubatsu "美国制　"
.orga (0x0D30E8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "もちづき　"
    .marubatsu "望月　　"
  ; .marubatsu "こうの　"
    .marubatsu "河野　　"
  ; .marubatsu "はぎわら　"
    .marubatsu "萩原　　"
  ; .marubatsu "いしざき　"
    .marubatsu "石琦　　"
  ; .marubatsu "イギリスせい　"
    .marubatsu "英国制　"
  ; .marubatsu "イタリアせい　"
    .marubatsu "意大利制　"
  ; .marubatsu "ドイツせい　"
    .marubatsu "德国制　"
  ; .marubatsu "アメリカせい　"
    .marubatsu "美国制　"

.loadtable "marubatsu_tbl\marubatsu_chs_1D.tbl"
.orga (0x0D31F6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "コインロッカー　"
    .marubatsu "出租柜　"
  ; .marubatsu "かしきんこ　"
    .marubatsu "保险库　"
  ; .marubatsu "そうこ　"
    .marubatsu "仓库　　"
  ; .marubatsu "じたく　"
    .marubatsu "自家　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　"
.orga (0x0D3292 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ダイヤモンド　"
    .marubatsu "钻石　　"
  ; .marubatsu "サフアイア　"
    .marubatsu "蓝宝石　"
  ; .marubatsu "エメラルド　"
    .marubatsu "绿宝石　"
  ; .marubatsu "ルビー　"
    .marubatsu "红宝石　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　"

.loadtable "marubatsu_tbl\marubatsu_chs_1E.tbl"
.orga (0x0D33A0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ようじんあんさつ　"
    .marubatsu "暗杀要人　"
  ; .marubatsu "じょせいさつがい　"
    .marubatsu "杀害女性　"
  ; .marubatsu "けいさつかんさつがい　"
    .marubatsu "杀害警察　"
  ; .marubatsu "みすい　ふうふさつがい　"
    .marubatsu "未遂　　"
  ; .marubatsu "１かげつまえ　"
    .marubatsu "１个月前　"
  ; .marubatsu "はんとしまえ　"
    .marubatsu "半年前　"
  ; .marubatsu "いちねんまえ　"
    .marubatsu "一年前　"
  ; .marubatsu "にねんまえ　"
    .marubatsu "两年前　"
.orga (0x0D343C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ベアー　"
    .marubatsu "大熊　　"
  ; .marubatsu "ウルフ　"
    .marubatsu "老狼　　"
  ; .marubatsu "イーグル　"
    .marubatsu "老鹰　　"
  ; .marubatsu "タイガー　"
    .marubatsu "老虎　　"
  ; .marubatsu "１かげつまえ　"
    .marubatsu "１个月前　"
  ; .marubatsu "はんとしまえ　"
    .marubatsu "半年前　"
  ; .marubatsu "いちねんまえ　"
    .marubatsu "一年前　"
  ; .marubatsu "にねんまえ　"
    .marubatsu "两年前　"

.loadtable "marubatsu_tbl\marubatsu_chs_1F.tbl"
.orga (0x0D354A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "はは　　"
    .marubatsu "妈妈　　"
  ; .marubatsu "あね　　"
    .marubatsu "姐姐　　"
  ; .marubatsu "あに　　"
    .marubatsu "哥哥　　"
  ; .marubatsu "おとうと　"
    .marubatsu "弟弟　　"
  ; .marubatsu "２まんえん　"
    .marubatsu "２万元　"
  ; .marubatsu "１まんえん　"
    .marubatsu "１万元　"
  ; .marubatsu "６せんえん　"
    .marubatsu "６千元　"
  ; .marubatsu "３ぜんえん　"
    .marubatsu "３千元　"
  ; .marubatsu "きのう　"
    .marubatsu "昨天　　"
  ; .marubatsu "けさ　　"
    .marubatsu "早上　　"
  ; .marubatsu "ひる　　"
    .marubatsu "中午　　"
  ; .marubatsu "よる　　"
    .marubatsu "晚上　　"
.orga (0x0D35E6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１かん　"
    .marubatsu "１卷　　"
  ; .marubatsu "２かん　"
    .marubatsu "２卷　　"
  ; .marubatsu "３かん　"
    .marubatsu "３卷　　"
  ; .marubatsu "４かん　"
    .marubatsu "４卷　　"
  ; .marubatsu "きのう　"
    .marubatsu "昨天　　"
  ; .marubatsu "けさ　　"
    .marubatsu "早上　　"
  ; .marubatsu "ひる　　"
    .marubatsu "中午　　"
  ; .marubatsu "よる　　"
    .marubatsu "晚上　　"
  ; .marubatsu "２まんえん　"
    .marubatsu "２万元　"
  ; .marubatsu "１まんえん　"
    .marubatsu "１万元　"
  ; .marubatsu "６せんえん　"
    .marubatsu "６千元　"
  ; .marubatsu "３ぜんえん　"
    .marubatsu "３千元　"

.loadtable "marubatsu_tbl\marubatsu_chs_20.tbl"
.orga (0x0D36F4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こむぎこ　"
    .marubatsu "小麦粉　"
  ; .marubatsu "ベーキングパウダー　"
    .marubatsu "发面粉　"
  ; .marubatsu "たまご　"
    .marubatsu "蛋　　　"
  ; .marubatsu "さとう　"
    .marubatsu "砂糖　　"
  ; .marubatsu "１ばんめに　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめに　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめに　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめに　"
    .marubatsu "第４　　"
  ; .marubatsu "５グラム　"
    .marubatsu "５克　　"
  ; .marubatsu "５０グラム　"
    .marubatsu "５０克　"
  ; .marubatsu "５５グラム　"
    .marubatsu "５５克　"
  ; .marubatsu "１００グラム　"
    .marubatsu "１００克　"
.orga (0x0D3790 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あかいけ　"
    .marubatsu "赤池　　"
  ; .marubatsu "ささもと　"
    .marubatsu "笹本　　"
  ; .marubatsu "なかざわ　"
    .marubatsu "中泽　　"
  ; .marubatsu "たけむら　"
    .marubatsu "竹村　　"
  ; .marubatsu "５グラム　"
    .marubatsu "５克　　"
  ; .marubatsu "５０グラム　"
    .marubatsu "５０克　"
  ; .marubatsu "５５グラム　"
    .marubatsu "５５克　"
  ; .marubatsu "１００グラム　"
    .marubatsu "１００克　"
  ; .marubatsu "１ばんめに　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめに　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめに　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめに　"
    .marubatsu "第４　　"

.loadtable "marubatsu_tbl\marubatsu_chs_21.tbl"
.orga (0x0D389E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "まやく　"
    .marubatsu "毒品　　"
  ; .marubatsu "ピストル　"
    .marubatsu "手枪　　"
  ; .marubatsu "ブラジャー　"
    .marubatsu "胸罩　　"
  ; .marubatsu "ナイフ　"
    .marubatsu "小刀　　"
  ; .marubatsu "デイパック　"
    .marubatsu "小背包　"
  ; .marubatsu "ボストンバッグ　"
    .marubatsu "旅行挎包　"
  ; .marubatsu "セカンドバッグ　"
    .marubatsu "手提包　　"
  ; .marubatsu "スーツケース　"
    .marubatsu "旅行箱　"
.orga (0x0D393A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "おかだ　"
    .marubatsu "冈田　　"
  ; .marubatsu "もり　　"
    .marubatsu "森　　　"
  ; .marubatsu "やぎ　　"
    .marubatsu "八木　　"
  ; .marubatsu "まるやま　"
    .marubatsu "丸山　　"
  ; .marubatsu "デイパック　"
    .marubatsu "小背包　"
  ; .marubatsu "ボストンバッグ　"
    .marubatsu "旅行挎包　"
  ; .marubatsu "セカンドバッグ　"
    .marubatsu "手提包　　"
  ; .marubatsu "スーツケース　"
    .marubatsu "旅行箱　"

.loadtable "marubatsu_tbl\marubatsu_chs_22.tbl"
.orga (0x0D3A48 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ロビーで　"
    .marubatsu "大厅　　"
  ; .marubatsu "なかにわで　"
    .marubatsu "庭院　　"
  ; .marubatsu "へやで　"
    .marubatsu "房间　　"
  ; .marubatsu "バーで　"
    .marubatsu "酒吧　　"
  ; .marubatsu "０９５０に　"
    .marubatsu "０９５０　"
  ; .marubatsu "１０１０に　"
    .marubatsu "１０１０　"
  ; .marubatsu "１０２０に　"
    .marubatsu "１０２０　"
  ; .marubatsu "１０３０に　"
    .marubatsu "１０３０　"
.orga (0x0D3AE4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "いけま　"
    .marubatsu "池间　　"
  ; .marubatsu "とくなが　"
    .marubatsu "德永　　"
  ; .marubatsu "しまや　"
    .marubatsu "岛屋　　"
  ; .marubatsu "すながわ　"
    .marubatsu "砂川　　"
  ; .marubatsu "０９５０に　"
    .marubatsu "０９５０　"
  ; .marubatsu "１０１０に　"
    .marubatsu "１０１０　"
  ; .marubatsu "１０２０に　"
    .marubatsu "１０２０　"
  ; .marubatsu "１０３０に　"
    .marubatsu "１０３０　"

.loadtable "marubatsu_tbl\marubatsu_chs_23.tbl"
.orga (0x0D3BF2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シュークリーム　"
    .marubatsu "奶油点心　"
  ; .marubatsu "チョコケーキ　"
    .marubatsu "巧克力蛋糕　"
  ; .marubatsu "イチゴショート　"
    .marubatsu "草莓蛋糕　"
  ; .marubatsu "チーズケーキ　"
    .marubatsu "起司蛋糕　"
  ; .marubatsu "３００えん　"
    .marubatsu "３００元　"
  ; .marubatsu "４００えん　"
    .marubatsu "４００元　"
  ; .marubatsu "５００えん　"
    .marubatsu "５００元　"
  ; .marubatsu "６００えん　"
    .marubatsu "６００元　"
.orga (0x0D3C8E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "うさぎや　"
    .marubatsu "兔子坊　"
  ; .marubatsu "フランセ　"
    .marubatsu "佛朗森　"
  ; .marubatsu "ビーグル　"
    .marubatsu "皮克尔　"
  ; .marubatsu "パンダや　"
    .marubatsu "熊猫坊　"
  ; .marubatsu "３００えん　"
    .marubatsu "３００元　"
  ; .marubatsu "４００えん　"
    .marubatsu "４００元　"
  ; .marubatsu "５００えん　"
    .marubatsu "５００元　"
  ; .marubatsu "６００えん　"
    .marubatsu "６００元　"

.loadtable "marubatsu_tbl\marubatsu_chs_24.tbl"
.orga (0x0D3D9C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "そばや　"
    .marubatsu "荞麦面店　"
  ; .marubatsu "きっさてん　"
    .marubatsu "咖啡厅　"
  ; .marubatsu "ラーメンや　"
    .marubatsu "拉面店　"
  ; .marubatsu "カレーせんもんてん　"
    .marubatsu "咖喱店　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１丁目　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２丁目　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３丁目　"
  ; .marubatsu "４ちょうめ　"
    .marubatsu "４丁目　"
  ; .marubatsu "げつようび　"
    .marubatsu "星期一　"
  ; .marubatsu "すいようび　"
    .marubatsu "星期三　"
  ; .marubatsu "きんようび　"
    .marubatsu "星期五　"
  ; .marubatsu "にちようび　"
    .marubatsu "星期日　"
.orga (0x0D3E38 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "さくら　"
    .marubatsu "樱花　　"
  ; .marubatsu "パンジー　"
    .marubatsu "三色堇　"
  ; .marubatsu "アイリス　"
    .marubatsu "爱丽丝　"
  ; .marubatsu "うめ　　"
    .marubatsu "梅花　　"
  ; .marubatsu "げつようび　"
    .marubatsu "星期一　"
  ; .marubatsu "すいようび　"
    .marubatsu "星期三　"
  ; .marubatsu "きんようび　"
    .marubatsu "星期五　"
  ; .marubatsu "にちようび　"
    .marubatsu "星期日　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１丁目　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２丁目　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３丁目　"
  ; .marubatsu "４ちょうめ　"
    .marubatsu "４丁目　"

.loadtable "marubatsu_tbl\marubatsu_chs_25.tbl"
.orga (0x0D3F46 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "まさと　"
    .marubatsu "正人　　"
  ; .marubatsu "ゆか　　"
    .marubatsu "由香　　"
  ; .marubatsu "たかのり　"
    .marubatsu "贵教　　"
  ; .marubatsu "きょうこ　"
    .marubatsu "杏子　　"
  ; .marubatsu "しょくひんうりば　"
    .marubatsu "食品卖场　"
  ; .marubatsu "しんしふくうりば　"
    .marubatsu "男服卖场　"
  ; .marubatsu "ふじんふくうりば　"
    .marubatsu "女服卖场　"
  ; .marubatsu "おもちゃうりば　"
    .marubatsu "玩具卖场　"
  ; .marubatsu "２さい　"
    .marubatsu "２岁　　"
  ; .marubatsu "３さい　"
    .marubatsu "３岁　　"
  ; .marubatsu "４さい　"
    .marubatsu "４岁　　"
  ; .marubatsu "５さい　"
    .marubatsu "５岁　　"
.orga (0x0D3FE2 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "なかむら　"
    .marubatsu "中村　　"
  ; .marubatsu "こうの　"
    .marubatsu "河野　　"
  ; .marubatsu "たけはら　"
    .marubatsu "竹原　　"
  ; .marubatsu "さいとう　"
    .marubatsu "齐藤　　"
  ; .marubatsu "２さい　"
    .marubatsu "２岁　　"
  ; .marubatsu "３さい　"
    .marubatsu "３岁　　"
  ; .marubatsu "４さい　"
    .marubatsu "４岁　　"
  ; .marubatsu "５さい　"
    .marubatsu "５岁　　"
  ; .marubatsu "しょくひんうりば　"
    .marubatsu "食品卖场　"
  ; .marubatsu "しんしふくうりば　"
    .marubatsu "男服卖场　"
  ; .marubatsu "ふじんふくうりば　"
    .marubatsu "女服卖场　"
  ; .marubatsu "おもちゃうりば　"
    .marubatsu "玩具卖场　"

.loadtable "marubatsu_tbl\marubatsu_chs_26.tbl"
.orga (0x0D40F0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ロープ　"
    .marubatsu "绳子　　"
  ; .marubatsu "ジーパン　"
    .marubatsu "牛仔裤　"
  ; .marubatsu "ナイフ　"
    .marubatsu "小刀　　"
  ; .marubatsu "シャツ　"
    .marubatsu "衬衫　　"
  ; .marubatsu "かわにすてた　"
    .marubatsu "河边扔掉　"
  ; .marubatsu "こうえんでもやした　"
    .marubatsu "公园烧掉　"
  ; .marubatsu "ごみすてばにすてた　"
    .marubatsu "丢垃圾场　"
  ; .marubatsu "やまにうめた　"
    .marubatsu "埋到山里　"
.orga (0x0D418C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめにすてた　"
    .marubatsu "第１个丢　"
  ; .marubatsu "２ばんめにすてた　"
    .marubatsu "第２个丢　"
  ; .marubatsu "３ばんめにすてた　"
    .marubatsu "第３个丢　"
  ; .marubatsu "４ばんめにすてた　"
    .marubatsu "第４个丢　"
  ; .marubatsu "かわにすてた　"
    .marubatsu "河边扔掉　"
  ; .marubatsu "こうえんでもやした　"
    .marubatsu "公园烧掉　"
  ; .marubatsu "ごみすてばにすてた　"
    .marubatsu "丢垃圾场　"
  ; .marubatsu "やまにうめた　"
    .marubatsu "埋到山里　"

.loadtable "marubatsu_tbl\marubatsu_chs_27.tbl"
.orga (0x0D429A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "４ばんめ　"
    .marubatsu "第４　　"
  ; .marubatsu "やきもの　"
    .marubatsu "陶器　　"
  ; .marubatsu "ゴルフクラブ　"
    .marubatsu "高尔夫球杆　"
  ; .marubatsu "にほんとう　"
    .marubatsu "日本刀　"
  ; .marubatsu "ネクタイ　"
    .marubatsu "领带　　"
.orga (0x0D4336 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "なかがわ　"
    .marubatsu "中川　　"
  ; .marubatsu "まき　　"
    .marubatsu "牧　　　"
  ; .marubatsu "たむら　"
    .marubatsu "田村　　"
  ; .marubatsu "おおはし　"
    .marubatsu "大桥　　"
  ; .marubatsu "やきもの　"
    .marubatsu "陶器　　"
  ; .marubatsu "ゴルフクラブ　"
    .marubatsu "高尔夫球杆　"
  ; .marubatsu "にほんとう　"
    .marubatsu "日本刀　"
  ; .marubatsu "ネクタイ　"
    .marubatsu "领带　　"

.loadtable "marubatsu_tbl\marubatsu_chs_28.tbl"
.orga (0x0D4444 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "トロのにぎり　"
    .marubatsu "金枪鱼寿司　"
  ; .marubatsu "アジのにぎり　"
    .marubatsu "竹夹鱼寿司　"
  ; .marubatsu "タコのにぎり　"
    .marubatsu "章鱼寿司　"
  ; .marubatsu "サバのにぎり　"
    .marubatsu "青花鱼寿司　"
  ; .marubatsu "きよし　"
    .marubatsu "清志　　"
  ; .marubatsu "あおい　"
    .marubatsu "苍井　　"
  ; .marubatsu "のぶみち　"
    .marubatsu "信道　　"
  ; .marubatsu "たかひろ　"
    .marubatsu "贵广　　"
.orga (0x0D44E0 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "サヤカ　"
    .marubatsu "沙耶香　"
  ; .marubatsu "ノリコ　"
    .marubatsu "典子　　"
  ; .marubatsu "エリカ　"
    .marubatsu "绘里香　"
  ; .marubatsu "マキ　　"
    .marubatsu "真木　　"
  ; .marubatsu "きよし　"
    .marubatsu "清志　　"
  ; .marubatsu "あおい　"
    .marubatsu "苍井　　"
  ; .marubatsu "のぶみち　"
    .marubatsu "信道　　"
  ; .marubatsu "たかひろ　"
    .marubatsu "贵广　　"

.loadtable "marubatsu_tbl\marubatsu_chs_29.tbl"
.orga (0x0D45EE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "たいようがもえもえ　"
    .marubatsu "太阳在燃烧　"
  ; .marubatsu "かがやくきせつ　"
    .marubatsu "光辉的季节　"
  ; .marubatsu "かもね　"
    .marubatsu "也许吧　"
  ; .marubatsu "だんごのおやこ　"
    .marubatsu "团子家族　"
  ; .marubatsu "ザ　モンキー　"
    .marubatsu "查蒙奇　"
  ; .marubatsu "かねこまみ　"
    .marubatsu "金子麻美　"
  ; .marubatsu "ジョージながおか　"
    .marubatsu "乔治长冈　"
  ; .marubatsu "ようこ　"
    .marubatsu "洋子　　"
  ; .marubatsu "ロック　"
    .marubatsu "摇滚　　"
  ; .marubatsu "えんか　"
    .marubatsu "演歌　　"
  ; .marubatsu "ラップ　"
    .marubatsu "说唱　　"
  ; .marubatsu "アニメソング　"
    .marubatsu "动漫歌曲　"
.orga (0x0D468A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１ばんめのうた　"
    .marubatsu "第１首歌　"
  ; .marubatsu "２ばんめのうた　"
    .marubatsu "第２首歌　"
  ; .marubatsu "３ばんめのうた　"
    .marubatsu "第３首歌　"
  ; .marubatsu "４ばんめのうた　"
    .marubatsu "第４首歌　"
  ; .marubatsu "ロック　"
    .marubatsu "摇滚　　"
  ; .marubatsu "えんか　"
    .marubatsu "演歌　　"
  ; .marubatsu "ラップ　"
    .marubatsu "说唱　　"
  ; .marubatsu "アニメソング　"
    .marubatsu "动漫歌曲　"
  ; .marubatsu "ザ　モンキー　"
    .marubatsu "查蒙奇　"
  ; .marubatsu "かねこまみ　"
    .marubatsu "金子麻美　"
  ; .marubatsu "ジョージながおか　"
    .marubatsu "乔治长冈　"
  ; .marubatsu "ようこ　"
    .marubatsu "洋子　　"

.loadtable "marubatsu_tbl\marubatsu_chs_2A.tbl"
.orga (0x0D4798 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１０００まんえん　"
    .marubatsu "１０００万　"
  ; .marubatsu "２０００まんえん　"
    .marubatsu "２０００万　"
  ; .marubatsu "３０００まんえん　"
    .marubatsu "３０００万　"
  ; .marubatsu "４０００まんえん　"
    .marubatsu "４０００万　"
  ; .marubatsu "くろいカバン　"
    .marubatsu "黑包　　"
  ; .marubatsu "あおいカバン　"
    .marubatsu "蓝包　　"
  ; .marubatsu "しろいカバン　"
    .marubatsu "白包　　"
  ; .marubatsu "あかいカバン　"
    .marubatsu "红包　　"
  ; .marubatsu "でんわボックス　"
    .marubatsu "电话亭　"
  ; .marubatsu "コインロッカー　"
    .marubatsu "储存柜　"
  ; .marubatsu "こうしゅうトイレ　"
    .marubatsu "公共厕所　"
  ; .marubatsu "こうえんのベンチ　"
    .marubatsu "公园长椅　"
.orga (0x0D4834 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ちちおや　"
    .marubatsu "父亲　　"
  ; .marubatsu "ははおや　"
    .marubatsu "母亲　　"
  ; .marubatsu "あね　　"
    .marubatsu "姐姐　　"
  ; .marubatsu "あに　　"
    .marubatsu "哥哥　　"
  ; .marubatsu "でんわボックス　"
    .marubatsu "电话亭　"
  ; .marubatsu "コインロッカー　"
    .marubatsu "储存柜　"
  ; .marubatsu "こうしゅうトイレ　"
    .marubatsu "公共厕所　"
  ; .marubatsu "こうえんのベンチ　"
    .marubatsu "公园长椅　"
  ; .marubatsu "くろいカバン　"
    .marubatsu "黑包　　"
  ; .marubatsu "あおいカバン　"
    .marubatsu "蓝包　　"
  ; .marubatsu "しろいカバン　"
    .marubatsu "白包　　"
  ; .marubatsu "あかいカバン　"
    .marubatsu "红包　　"

.loadtable "marubatsu_tbl\marubatsu_chs_2B.tbl"
.orga (0x0D4942 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ルパン　"
    .marubatsu "鲁邦　　"
  ; .marubatsu "ホームズ　"
    .marubatsu "福尔摩斯　"
  ; .marubatsu "ポアロ　"
    .marubatsu "波洛　　"
  ; .marubatsu "マーブル　"
    .marubatsu "马布尔　"
  ; .marubatsu "１じに　"
    .marubatsu "１点　　"
  ; .marubatsu "２じに　"
    .marubatsu "２点　　"
  ; .marubatsu "３じに　"
    .marubatsu "３点　　"
  ; .marubatsu "４じに　"
    .marubatsu "４点　　"
.orga (0x0D49DE + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こうえん　"
    .marubatsu "公园　　"
  ; .marubatsu "デパート　"
    .marubatsu "商场　　"
  ; .marubatsu "ホテル　"
    .marubatsu "酒店　　"
  ; .marubatsu "こうこう　"
    .marubatsu "高中　　"
  ; .marubatsu "１じに　"
    .marubatsu "１点　　"
  ; .marubatsu "２じに　"
    .marubatsu "２点　　"
  ; .marubatsu "３じに　"
    .marubatsu "３点　　"
  ; .marubatsu "４じに　"
    .marubatsu "４点　　"

.loadtable "marubatsu_tbl\marubatsu_chs_2C.tbl"
.orga (0x0D4AEC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ほし　　"
    .marubatsu "占星术　"
  ; .marubatsu "タロット　"
    .marubatsu "塔罗牌　"
  ; .marubatsu "てそう　"
    .marubatsu "看手相　"
  ; .marubatsu "にんそう　"
    .marubatsu "看面相　"
  ; .marubatsu "１ばんにんき　"
    .marubatsu "第１人气　"
  ; .marubatsu "２ばんにんき　"
    .marubatsu "第２人气　"
  ; .marubatsu "３ばんにんき　"
    .marubatsu "第３人气　"
  ; .marubatsu "４ばんにんき　"
    .marubatsu "第４人气　"
.orga (0x0D4B88 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ひがしのへや　"
    .marubatsu "东房间　"
  ; .marubatsu "にしのへや　"
    .marubatsu "西房间　"
  ; .marubatsu "みなみのへや　"
    .marubatsu "南房间　"
  ; .marubatsu "きたのへや　"
    .marubatsu "北房间　"
  ; .marubatsu "１ばんにんき　"
    .marubatsu "第１人气　"
  ; .marubatsu "２ばんにんき　"
    .marubatsu "第２人气　"
  ; .marubatsu "３ばんにんき　"
    .marubatsu "第３人气　"
  ; .marubatsu "４ばんにんき　"
    .marubatsu "第４人气　"

.loadtable "marubatsu_tbl\marubatsu_chs_2D.tbl"
.orga (0x0D4C96 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しょくどう　"
    .marubatsu "餐厅　　"
  ; .marubatsu "リビングルーム　"
    .marubatsu "客厅　　"
  ; .marubatsu "ベランダ　"
    .marubatsu "阳台　　"
  ; .marubatsu "ベッドルーム　"
    .marubatsu "卧室　　"
  ; .marubatsu "コーヒー　"
    .marubatsu "咖啡　　"
  ; .marubatsu "こうちゃ　"
    .marubatsu "红茶　　"
  ; .marubatsu "ばんちゃ　"
    .marubatsu "绿茶　　"
  ; .marubatsu "ホットミルク　"
    .marubatsu "热牛奶　"
  ; .marubatsu "あさ　　"
    .marubatsu "早上　　"
  ; .marubatsu "ひる　　"
    .marubatsu "上午　　"
  ; .marubatsu "ゆうがた　"
    .marubatsu "傍晚　　"
  ; .marubatsu "よる　　"
    .marubatsu "晚上　　"
.orga (0x0D4D32 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あかいカップ　"
    .marubatsu "红色茶杯　"
  ; .marubatsu "しろいカップ　"
    .marubatsu "白色茶杯　"
  ; .marubatsu "くろいカップ　"
    .marubatsu "黑色茶杯　"
  ; .marubatsu "みどりのカップ　"
    .marubatsu "绿色茶杯　"
  ; .marubatsu "あさ　　"
    .marubatsu "早上　　"
  ; .marubatsu "ひる　　"
    .marubatsu "上午　　"
  ; .marubatsu "ゆうがた　"
    .marubatsu "傍晚　　"
  ; .marubatsu "よる　　"
    .marubatsu "晚上　　"
  ; .marubatsu "コーヒー　"
    .marubatsu "咖啡　　"
  ; .marubatsu "こうちゃ　"
    .marubatsu "红茶　　"
  ; .marubatsu "ばんちゃ　"
    .marubatsu "绿茶　　"
  ; .marubatsu "ホットミルク　"
    .marubatsu "热牛奶　"

.loadtable "marubatsu_tbl\marubatsu_chs_2E.tbl"
.orga (0x0D4E40 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "１２じに　"
    .marubatsu "１２点　"
  ; .marubatsu "１じに　"
    .marubatsu "１点　　"
  ; .marubatsu "２じに　"
    .marubatsu "２点　　"
  ; .marubatsu "３じに　"
    .marubatsu "３点　　"
  ; .marubatsu "ぎんこう　"
    .marubatsu "银行　　"
  ; .marubatsu "スーパー　"
    .marubatsu "超市　　"
  ; .marubatsu "がっこう　"
    .marubatsu "学校　　"
  ; .marubatsu "アパート　"
    .marubatsu "公寓　　"
  ; .marubatsu "ごみばこがもえた　"
    .marubatsu "垃圾桶着火　"
  ; .marubatsu "くるまがもえた　"
    .marubatsu "汽车着火　"
  ; .marubatsu "ビニールがもえた　"
    .marubatsu "塑料袋着火　"
  ; .marubatsu "ポスターがもえた　"
    .marubatsu "海报着火　"
.orga (0x0D4EDC + ROM_EXPANSION_OFFSET)
  ; .marubatsu "くわはら　"
    .marubatsu "桑原　　"
  ; .marubatsu "のぐち　"
    .marubatsu "野口　　"
  ; .marubatsu "えばた　"
    .marubatsu "江畑　　"
  ; .marubatsu "なかはら　"
    .marubatsu "中原　　"
  ; .marubatsu "ごみばこがもえた　"
    .marubatsu "垃圾桶着火　"
  ; .marubatsu "くるまがもえた　"
    .marubatsu "汽车着火　"
  ; .marubatsu "ビニールがもえた　"
    .marubatsu "塑料袋着火　"
  ; .marubatsu "ポスターがもえた　"
    .marubatsu "海报着火　"
  ; .marubatsu "ぎんこう　"
    .marubatsu "银行　　"
  ; .marubatsu "スーパー　"
    .marubatsu "超市　　"
  ; .marubatsu "がっこう　"
    .marubatsu "学校　　"
  ; .marubatsu "アパート　"
    .marubatsu "公寓　　"

.loadtable "marubatsu_tbl\marubatsu_chs_2F.tbl"
.orga (0x0D4FEA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "きんけん　"
    .marubatsu "证券　　"
  ; .marubatsu "つぼ　　"
    .marubatsu "壶　　　"
  ; .marubatsu "げんきん　"
    .marubatsu "现金　　"
  ; .marubatsu "ダイヤ　"
    .marubatsu "钻石　　"
  ; .marubatsu "５まんえん　"
    .marubatsu "５万元　"
  ; .marubatsu "１０まんえん　"
    .marubatsu "１０万元　"
  ; .marubatsu "３０まんえん　"
    .marubatsu "３０万元　"
  ; .marubatsu "８０まんえん　"
    .marubatsu "８０万元　"
  ; .marubatsu "きょう　"
    .marubatsu "今天　　"
  ; .marubatsu "きのう　"
    .marubatsu "昨天　　"
  ; .marubatsu "５にちまえ　"
    .marubatsu "５天前　"
  ; .marubatsu "７にちまえ　"
    .marubatsu "７天前　"
.orga (0x0D5086 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "いしゃのいえ　"
    .marubatsu "医生的家　"
  ; .marubatsu "はいゆうのいえ　"
    .marubatsu "演员的家　"
  ; .marubatsu "べんごしのいえ　"
    .marubatsu "律师的家　"
  ; .marubatsu "きょうしのいえ　"
    .marubatsu "老师的家　"
  ; .marubatsu "きょう　"
    .marubatsu "今天　　"
  ; .marubatsu "きのう　"
    .marubatsu "昨天　　"
  ; .marubatsu "５にちまえ　"
    .marubatsu "５天前　"
  ; .marubatsu "７にちまえ　"
    .marubatsu "７天前　"
  ; .marubatsu "５まんえん　"
    .marubatsu "５万元　"
  ; .marubatsu "１０まんえん　"
    .marubatsu "１０万元　"
  ; .marubatsu "３０まんえん　"
    .marubatsu "３０万元　"
  ; .marubatsu "８０まんえん　"
    .marubatsu "８０万元　"

.loadtable "marubatsu_tbl\marubatsu_chs_30.tbl"
.orga (0x0D5194 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アジト１　"
    .marubatsu "安全屋１　"
  ; .marubatsu "アジト２　"
    .marubatsu "安全屋２　"
  ; .marubatsu "アジト３　"
    .marubatsu "安全屋３　"
  ; .marubatsu "アジト４　"
    .marubatsu "安全屋４　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１丁目　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２丁目　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３丁目　"
  ; .marubatsu "となりまち　"
    .marubatsu "隔壁街区　"
.orga (0x0D5230 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かわい　"
    .marubatsu "河合　　"
  ; .marubatsu "おきた　"
    .marubatsu "冲田　　"
  ; .marubatsu "とよだ　"
    .marubatsu "丰田　　"
  ; .marubatsu "かわぐち　"
    .marubatsu "河口　　"
  ; .marubatsu "１ちょうめ　"
    .marubatsu "１丁目　"
  ; .marubatsu "２ちょうめ　"
    .marubatsu "２丁目　"
  ; .marubatsu "３ちょうめ　"
    .marubatsu "３丁目　"
  ; .marubatsu "となりまち　"
    .marubatsu "隔壁街区　"

.loadtable "marubatsu_tbl\marubatsu_chs_31.tbl"
.orga (0x0D533E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ポーカー　"
    .marubatsu "扑克　　"
  ; .marubatsu "ルーレット　"
    .marubatsu "轮盘　　"
  ; .marubatsu "スロット　"
    .marubatsu "老虎机　"
  ; .marubatsu "バカラ　"
    .marubatsu "百家乐　"
  ; .marubatsu "１００チップ　"
    .marubatsu "１００筹码　"
  ; .marubatsu "２００チップ　"
    .marubatsu "２００筹码　"
  ; .marubatsu "３００チップ　"
    .marubatsu "３００筹码　"
  ; .marubatsu "４００チップ　"
    .marubatsu "４００筹码　"
.orga (0x0D53DA + ROM_EXPANSION_OFFSET)
  ; .marubatsu "あかい　"
    .marubatsu "赤井　　"
  ; .marubatsu "あおの　"
    .marubatsu "青野　　"
  ; .marubatsu "きじま　"
    .marubatsu "黄岛　　"
  ; .marubatsu "くろさき　"
    .marubatsu "黑崎　　"
  ; .marubatsu "１００チップ　"
    .marubatsu "１００筹码　"
  ; .marubatsu "２００チップ　"
    .marubatsu "２００筹码　"
  ; .marubatsu "３００チップ　"
    .marubatsu "３００筹码　"
  ; .marubatsu "４００チップ　"
    .marubatsu "４００筹码　"

.loadtable "marubatsu_tbl\marubatsu_chs_32.tbl"
.orga (0x0D54E8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ひでき　"
    .marubatsu "秀树　　"
  ; .marubatsu "さとる　"
    .marubatsu "聪　　　"
  ; .marubatsu "よういち　"
    .marubatsu "洋一　　"
  ; .marubatsu "てっぺい　"
    .marubatsu "折平　　"
  ; .marubatsu "げつようび　"
    .marubatsu "星期一　"
  ; .marubatsu "かようび　"
    .marubatsu "星期二　"
  ; .marubatsu "すいようび　"
    .marubatsu "星期三　"
  ; .marubatsu "もくようび　"
    .marubatsu "星期四　"
.orga (0x0D5584 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "はるか　"
    .marubatsu "春香　　"
  ; .marubatsu "なつみ　"
    .marubatsu "夏实　　"
  ; .marubatsu "あきえ　"
    .marubatsu "秋绘　　"
  ; .marubatsu "ふゆこ　"
    .marubatsu "冬子　　"
  ; .marubatsu "げつようび　"
    .marubatsu "星期一　"
  ; .marubatsu "かようび　"
    .marubatsu "星期二　"
  ; .marubatsu "すいようび　"
    .marubatsu "星期三　"
  ; .marubatsu "もくようび　"
    .marubatsu "星期四　"

.loadtable "marubatsu_tbl\marubatsu_chs_33.tbl"
.orga (0x0D5692 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "マイコ　"
    .marubatsu "舞子　　"
  ; .marubatsu "ユウコ　"
    .marubatsu "夕子　　"
  ; .marubatsu "アユミ　"
    .marubatsu "步美　　"
  ; .marubatsu "ナツコ　"
    .marubatsu "奈津子　"
  ; .marubatsu "おしゃれなうでどけい　"
    .marubatsu "手表　　"
  ; .marubatsu "かわいいシール　"
    .marubatsu "贴纸　　"
  ; .marubatsu "ハートのピアス　"
    .marubatsu "耳坠　　"
  ; .marubatsu "バラのはなたば　"
    .marubatsu "花束　　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "さいご　"
    .marubatsu "最后　　"
.orga (0x0D572E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ぶしつのロッカー　"
    .marubatsu "储物柜　"
  ; .marubatsu "たいいくかんばき　"
    .marubatsu "鞋子　　"
  ; .marubatsu "スポーツかばん　"
    .marubatsu "包包　　"
  ; .marubatsu "うんどうようジャージ　"
    .marubatsu "运动服　"
  ; .marubatsu "１ばんめ　"
    .marubatsu "第１　　"
  ; .marubatsu "２ばんめ　"
    .marubatsu "第２　　"
  ; .marubatsu "３ばんめ　"
    .marubatsu "第３　　"
  ; .marubatsu "さいご　"
    .marubatsu "最后　　"
  ; .marubatsu "おしゃれなうでどけい　"
    .marubatsu "手表　　"
  ; .marubatsu "かわいいシール　"
    .marubatsu "贴纸　　"
  ; .marubatsu "ハートのピアス　"
    .marubatsu "耳坠　　"
  ; .marubatsu "バラのはなたば　"
    .marubatsu "花束　　"

.loadtable "marubatsu_tbl\marubatsu_chs_34.tbl"
.orga (0x0D583C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "サッカーぶ　"
    .marubatsu "足球部　"
  ; .marubatsu "やきゅうぶ　"
    .marubatsu "棒球部　"
  ; .marubatsu "すいえいぶ　"
    .marubatsu "游泳部　"
  ; .marubatsu "けんどうぶ　"
    .marubatsu "剑道部　"
  ; .marubatsu "１ばんすき　"
    .marubatsu "第１喜欢　"
  ; .marubatsu "２ばんめにすき　"
    .marubatsu "第２喜欢　"
  ; .marubatsu "３ばんめにすき　"
    .marubatsu "第３喜欢　"
  ; .marubatsu "４ばんめにすき　"
    .marubatsu "第４喜欢　"
.orga (0x0D58D8 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "こまつ　"
    .marubatsu "小松　　"
  ; .marubatsu "おおの　"
    .marubatsu "大野　　"
  ; .marubatsu "おおたき　"
    .marubatsu "大泷　　"
  ; .marubatsu "まつした　"
    .marubatsu "松下　　"
  ; .marubatsu "１ばんすき　"
    .marubatsu "第１喜欢　"
  ; .marubatsu "２ばんめにすき　"
    .marubatsu "第２喜欢　"
  ; .marubatsu "３ばんめにすき　"
    .marubatsu "第３喜欢　"
  ; .marubatsu "４ばんめにすき　"
    .marubatsu "第４喜欢　"

.loadtable "marubatsu_tbl\marubatsu_chs_35.tbl"
.orga (0x0D59E6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "かがわ　"
    .marubatsu "香川　　"
  ; .marubatsu "やまぐち　"
    .marubatsu "山口　　"
  ; .marubatsu "みやぎ　"
    .marubatsu "宫城　　"
  ; .marubatsu "ふくおか　"
    .marubatsu "福冈　　"
  ; .marubatsu "ばらばらじけん　"
    .marubatsu "分尸　　"
  ; .marubatsu "じゅうさつ　"
    .marubatsu "枪杀　　"
  ; .marubatsu "こうさつ　"
    .marubatsu "绞杀　　"
  ; .marubatsu "みすい　"
    .marubatsu "未遂　　"
  ; .marubatsu "ことし　"
    .marubatsu "今年　　"
  ; .marubatsu "１ねんまえ　"
    .marubatsu "１年前　"
  ; .marubatsu "３ねんまえ　"
    .marubatsu "３年前　"
  ; .marubatsu "４ねんまえ　"
    .marubatsu "４年前　"
.orga (0x0D5A82 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ちば　　"
    .marubatsu "千叶　　"
  ; .marubatsu "ふくしま　"
    .marubatsu "福岛　　"
  ; .marubatsu "やまがた　"
    .marubatsu "山形　　"
  ; .marubatsu "ながの　"
    .marubatsu "长野　　"
  ; .marubatsu "ことし　"
    .marubatsu "今年　　"
  ; .marubatsu "１ねんまえ　"
    .marubatsu "１年前　"
  ; .marubatsu "３ねんまえ　"
    .marubatsu "３年前　"
  ; .marubatsu "４ねんまえ　"
    .marubatsu "４年前　"
  ; .marubatsu "ばらばらじけん　"
    .marubatsu "分尸　　"
  ; .marubatsu "じゅうさつ　"
    .marubatsu "枪杀　　"
  ; .marubatsu "こうさつ　"
    .marubatsu "绞杀　　"
  ; .marubatsu "みすい　"
    .marubatsu "未遂　　"

.loadtable "marubatsu_tbl\marubatsu_chs_36.tbl"
.orga (0x0D5B90 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "しごとのはなし　"
    .marubatsu "工作话题　"
  ; .marubatsu "れんあいのそうだん　"
    .marubatsu "恋爱话题　"
  ; .marubatsu "そうおんのくじょう　"
    .marubatsu "噪音抱怨　"
  ; .marubatsu "おかねのはなし　"
    .marubatsu "金钱话题　"
  ; .marubatsu "ともだち　"
    .marubatsu "朋友　　"
  ; .marubatsu "となり　"
    .marubatsu "邻居　　"
  ; .marubatsu "こいびと　"
    .marubatsu "恋人　　"
  ; .marubatsu "あに　　"
    .marubatsu "哥哥　　"
  ; .marubatsu "６じ　　"
    .marubatsu "６点　　"
  ; .marubatsu "７じ　　"
    .marubatsu "７点　　"
  ; .marubatsu "８じ　　"
    .marubatsu "８点　　"
  ; .marubatsu "９じ　　"
    .marubatsu "９点　　"
.orga (0x0D5C2C + ROM_EXPANSION_OFFSET)
  ; .marubatsu "やまだ　"
    .marubatsu "山田　　"
  ; .marubatsu "かわはら　"
    .marubatsu "川原　　"
  ; .marubatsu "たにぐち　"
    .marubatsu "谷口　　"
  ; .marubatsu "もり　　"
    .marubatsu "森　　　"
  ; .marubatsu "６じ　　"
    .marubatsu "６点　　"
  ; .marubatsu "７じ　　"
    .marubatsu "７点　　"
  ; .marubatsu "８じ　　"
    .marubatsu "８点　　"
  ; .marubatsu "９じ　　"
    .marubatsu "９点　　"
  ; .marubatsu "ともだち　"
    .marubatsu "朋友　　"
  ; .marubatsu "となり　"
    .marubatsu "邻居　　"
  ; .marubatsu "こいびと　"
    .marubatsu "恋人　　"
  ; .marubatsu "あに　　"
    .marubatsu "哥哥　　"

.loadtable "marubatsu_tbl\marubatsu_chs_37.tbl"
.orga (0x0D5D3A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "げつようび　"
    .marubatsu "星期一　"
  ; .marubatsu "かようび　"
    .marubatsu "星期二　"
  ; .marubatsu "もくようび　"
    .marubatsu "星期四　"
  ; .marubatsu "きんようび　"
    .marubatsu "星期五　"
  ; .marubatsu "スター　"
    .marubatsu "明星　　"
  ; .marubatsu "マフイア　"
    .marubatsu "黑手党　"
  ; .marubatsu "だいふごう　"
    .marubatsu "大富豪　"
  ; .marubatsu "はかせ　"
    .marubatsu "博士　　"
  ; .marubatsu "まずまずのけっか　"
    .marubatsu "马马虎虎　"
  ; .marubatsu "２はつでしとめた　"
    .marubatsu "２发解决　"
  ; .marubatsu "かんぺきなしごと　"
    .marubatsu "完美工作　"
  ; .marubatsu "にげられた　"
    .marubatsu "被他跑了　"
.orga (0x0D5DD6 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "アメリカ　"
    .marubatsu "美国　　"
  ; .marubatsu "ブラジル　"
    .marubatsu "巴西　　"
  ; .marubatsu "フランス　"
    .marubatsu "法国　　"
  ; .marubatsu "イギリス　"
    .marubatsu "英国　　"
  ; .marubatsu "まずまずのけっか　"
    .marubatsu "马马虎虎　"
  ; .marubatsu "２はつでしとめた　"
    .marubatsu "２发解决　"
  ; .marubatsu "かんぺきなしごと　"
    .marubatsu "完美工作　"
  ; .marubatsu "にげられた　"
    .marubatsu "被他跑了　"
  ; .marubatsu "スター　"
    .marubatsu "明星　　"
  ; .marubatsu "マフイア　"
    .marubatsu "黑手党　"
  ; .marubatsu "だいふごう　"
    .marubatsu "大富豪　"
  ; .marubatsu "はかせ　"
    .marubatsu "博士　　"

.loadtable "marubatsu_tbl\marubatsu_chs_38.tbl"
.orga (0x0D5EE4 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ウルウル　"
    .marubatsu "令人落泪　"
  ; .marubatsu "ワクワク　"
    .marubatsu "令人兴奋　"
  ; .marubatsu "ビクビク　"
    .marubatsu "令人不安　"
  ; .marubatsu "ドキドキ　"
    .marubatsu "令人心跳　"
  ; .marubatsu "１５０ページ　"
    .marubatsu "１５０页　"
  ; .marubatsu "１６０ページ　"
    .marubatsu "１６０页　"
  ; .marubatsu "１７０ページ　"
    .marubatsu "１７０页　"
  ; .marubatsu "１８０ページ　"
    .marubatsu "１８０页　"
  ; .marubatsu "たびだち　"
    .marubatsu "旅行　　"
  ; .marubatsu "つりきち　"
    .marubatsu "钓鱼　　"
  ; .marubatsu "うんめい　"
    .marubatsu "命运　　"
  ; .marubatsu "ときめき　"
    .marubatsu "悸动　　"
.orga (0x0D5F80 + ROM_EXPANSION_OFFSET)
  ; .marubatsu "シエーヌ　"
    .marubatsu "香奈儿　"
  ; .marubatsu "マリリン　"
    .marubatsu "玛里琳　"
  ; .marubatsu "ヨッシー　"
    .marubatsu "耀西　　"
  ; .marubatsu "ケイト　"
    .marubatsu "凯特　　"
  ; .marubatsu "たびだち　"
    .marubatsu "旅行　　"
  ; .marubatsu "つりきち　"
    .marubatsu "钓鱼　　"
  ; .marubatsu "うんめい　"
    .marubatsu "命运　　"
  ; .marubatsu "ときめき　"
    .marubatsu "悸动　　"
  ; .marubatsu "１５０ページ　"
    .marubatsu "１５０页　"
  ; .marubatsu "１６０ページ　"
    .marubatsu "１６０页　"
  ; .marubatsu "１７０ページ　"
    .marubatsu "１７０页　"
  ; .marubatsu "１８０ページ　"
    .marubatsu "１８０页　"

.loadtable "marubatsu_tbl\marubatsu_chs_39.tbl"
.orga (0x0D608E + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ナイフでころした　"
    .marubatsu "小刀杀害　"
  ; .marubatsu "カビンでころした　"
    .marubatsu "花瓶杀害　"
  ; .marubatsu "ジュウでころした　"
    .marubatsu "枪杀　　"
  ; .marubatsu "ドクヤクでころした　"
    .marubatsu "毒药杀死　"
  ; .marubatsu "５じにおこなった　"
    .marubatsu "５点　　"
  ; .marubatsu "６じにおこなった　"
    .marubatsu "６点　　"
  ; .marubatsu "７じにおこなった　"
    .marubatsu "７点　　"
  ; .marubatsu "８じにおこなった　"
    .marubatsu "８点　　"
  ; .marubatsu "ケイコをころした　"
    .marubatsu "杀了敬子　"
  ; .marubatsu "カズミをころした　"
    .marubatsu "杀了和美　"
  ; .marubatsu "ヨーコをころした　"
    .marubatsu "杀了洋子　"
  ; .marubatsu "ヒロコをころした　"
    .marubatsu "杀了广子　"
.orga (0x0D612A + ROM_EXPANSION_OFFSET)
  ; .marubatsu "ケイコがころした　"
    .marubatsu "敬子杀的　"
  ; .marubatsu "カズミがころした　"
    .marubatsu "和美杀的　"
  ; .marubatsu "ヨーコがころした　"
    .marubatsu "洋子杀的　"
  ; .marubatsu "ヒロコがころした　"
    .marubatsu "广子杀的　"
  ; .marubatsu "ケイコをころした　"
    .marubatsu "杀了敬子　"
  ; .marubatsu "カズミをころした　"
    .marubatsu "杀了和美　"
  ; .marubatsu "ヨーコをころした　"
    .marubatsu "杀了洋子　"
  ; .marubatsu "ヒロコをころした　"
    .marubatsu "杀了广子　"
  ; .marubatsu "５じにおこなった　"
    .marubatsu "５点　　"
  ; .marubatsu "６じにおこなった　"
    .marubatsu "６点　　"
  ; .marubatsu "７じにおこなった　"
    .marubatsu "７点　　"
  ; .marubatsu "８じにおこなった　"
    .marubatsu "８点　　"

